### ISSUE TITLE
[BUG] 真寻漂流瓶插件造成的napcat异常

### ISSUE THREAD

**Issue by LierJeo** [NapNeko/NapCatQQ#1]
### 系统版本

ubuntu22.04 server

### QQNT 版本

使用napcat-docker部署，默认未更改

### NapCat 版本

4.15号为止的版本（docker去哪里找版本号）

### OneBot 客户端

真寻bot

### 发生了什么?

漂流瓶插件项目地址 https://github.com/molanp/nonebot_zhenxun_plugin_bottle
当使用捡漂流瓶命令时，真寻bot日志报告ws断开连接，手机qq显示Linux客户端离线，仅5G在线。napcat容器日志见下方

### 如何复现

使用指令 扔漂流瓶+图片
然后再捡漂流瓶 触发
重复两次现象一致

### 期望的结果?

正常发送图片消息。
如果发送错误在日志打印错误信息。

### NapCat 运行日志

```shell
235,1781,Read map line: 7ffd9ba5d000-7ffd9ba7e000 rw-p 00000000 00:00 0                          [stack]

 235,1782,Read map line: 7ffd9bb3c000-7ffd9bb40000 r--p 00000000 00:00 0                          [vvar]

 235,1783,Read map line: 7ffd9bb40000-7ffd9bb42000 r-xp 00000000 00:00 0                          [vdso]

 235,1784,Read map line: ffffffffff600000-ffffffffff601000 --xp 00000000 00:00 0                  [vsyscall]

[BuglyService.cpp][handleSignal][382]Stack is succesfully dumped by libUnwind.
[BuglyService.cpp][handleSignal][384]Native stack:
$$00    pc 00000000000969fc    /usr/lib/x86_64-linux-gnu/libc.so.6 (pthread_kill+300) [x86_64::71a3399de893d2af81d6a30c62646e1e]
$$01    pc 0000000000042476    /usr/lib/x86_64-linux-gnu/libc.so.6 (raise+22) [x86_64::71a3399de893d2af81d6a30c62646e1e]
$$02    pc 00000000000287f3    /usr/lib/x86_64-linux-gnu/libc.so.6 (abort+211) [x86_64::71a3399de893d2af81d6a30c62646e1e]
$$03    pc 0000000009c947b2    /opt/QQ/qq [x86_64::418b5e6470d9b4ead85fd19f1a6b7c0a]
$$04    pc 0000000009c94896    /opt/QQ/qq [x86_64::418b5e6470d9b4ead85fd19f1a6b7c0a]
$$05    pc 000000000387360c    /opt/QQ/qq [x86_64::418b5e6470d9b4ead85fd19f1a6b7c0a]
$$06    pc 0000000002465e7f    /opt/QQ/resources/app/wrapper.node [x86_64::de618b7bec5291db0000000000000000]
$$07    pc 000000000227d1f3    /opt/QQ/resources/app/wrapper.node [x86_64::de618b7bec5291db0000000000000000]
$$08    pc 00000000020d2140    /opt/QQ/qq [x86_64::418b5e6470d9b4ead85fd19f1a6b7c0a]
$$09    pc 00000000020d0224    /opt/QQ/qq [x86_64::418b5e6470d9b4ead85fd19f1a6b7c0a]
$$10    pc 00000000021e1607    /opt/QQ/qq [x86_64::418b5e6470d9b4ead85fd19f1a6b7c0a]
$$11    pc 00000000020d0d8f    /opt/QQ/qq [x86_64::418b5e6470d9b4ead85fd19f1a6b7c0a]
$$12    pc 000000000225668d    /opt/QQ/qq [x86_64::418b5e6470d9b4ead85fd19f1a6b7c0a]
$$13    pc 00000000020d0224    /opt/QQ/qq [x86_64::418b5e6470d9b4ead85fd19f1a6b7c0a]
$$14    pc 00000000020d0224    /opt/QQ/qq [x86_64::418b5e6470d9b4ead85fd19f1a6b7c0a]
$$15    pc 000000000210fdc2    /opt/QQ/qq [x86_64::418b5e6470d9b4ead85fd19f1a6b7c0a]
$$16    pc 00000000021e372d    /opt/QQ/qq [x86_64::418b5e6470d9b4ead85fd19f1a6b7c0a]
$$17    pc 00000000020fd4be    /opt/QQ/qq [x86_64::418b5e6470d9b4ead85fd19f1a6b7c0a]
$$18    pc 00000000020cdd07    /opt/QQ/qq [x86_64::418b5e6470d9b4ead85fd19f1a6b7c0a]
$$19    pc 0000000003997f4e    /opt/QQ/qq [x86_64::418b5e6470d9b4ead85fd19f1a6b7c0a]
$$20    pc 0000000003998d9a    /opt/QQ/qq [x86_64::418b5e6470d9b4ead85fd19f1a6b7c0a]
$$21    pc 0000000003998f09    /opt/QQ/qq [x86_64::418b5e6470d9b4ead85fd19f1a6b7c0a]
$$22    pc 00000000039cac5d    /opt/QQ/qq [x86_64::418b5e6470d9b4ead85fd19f1a6b7c0a]
$$23    pc 00000000020d2140    /opt/QQ/qq [x86_64::418b5e6470d9b4ead85fd19f1a6b7c0a]
$$24    pc 00005606da6903fe    <unknown>
$$25    pc 00000000020cdddc    /opt/QQ/qq [x86_64::418b5e6470d9b4ead85fd19f1a6b7c0a]
$$26    pc 00000000020cdb07    /opt/QQ/qq [x86_64::418b5e6470d9b4ead85fd19f1a6b7c0a]
$$27    pc 000000000399803c    /opt/QQ/qq [x86_64::418b5e6470d9b4ead85fd19f1a6b7c0a]
$$28    pc 0000000003997d5b    /opt/QQ/qq (_ZN2v88internal9Execution4CallEPNS0_7IsolateENS0_6HandleINS0_6ObjectEEES6_iPS6_+155) [x86_64::418b5e6470d9b4ead85fd19f1a6b7c0a]
$$29    pc 000000000388c5d9    /opt/QQ/qq (_ZN2v88Function4CallENS_5LocalINS_7ContextEEENS1_INS_5ValueEEEiPS5_+841) [x86_64::418b5e6470d9b4ead85fd19f1a6b7c0a]
$$30    pc 0000000009bd9871    /opt/QQ/qq [x86_64::418b5e6470d9b4ead85fd19f1a6b7c0a]
$$31    pc 0000000009bd9a12    /opt/QQ/qq [x86_64::418b5e6470d9b4ead85fd19f1a6b7c0a]
$$32    pc 0000000009beeea0    /opt/QQ/qq [x86_64::418b5e6470d9b4ead85fd19f1a6b7c0a]
$$33    pc 0000000009d7b0d7    /opt/QQ/qq [x86_64::418b5e6470d9b4ead85fd19f1a6b7c0a]
$$34    pc 0000000009d7cfc7    /opt/QQ/qq [x86_64::418b5e6470d9b4ead85fd19f1a6b7c0a]
$$35    pc 0000000009d81db6    /opt/QQ/qq [x86_64::418b5e6470d9b4ead85fd19f1a6b7c0a]
$$36    pc 0000000009d8287c    /opt/QQ/qq [x86_64::418b5e6470d9b4ead85fd19f1a6b7c0a]
$$37    pc 000000000248baf4    /opt/QQ/qq [x86_64::418b5e6470d9b4ead85fd19f1a6b7c0a]
$$38    pc 0000000002490daa    /opt/QQ/qq [x86_64::418b5e6470d9b4ead85fd19f1a6b7c0a]

[BuglyService.cpp][handleSignal][386]Record map file of thread: 11
[BuglyService.cpp][handleSignal][396]Dumping of native stack finished.
 235,0001,Record EupInfo
 235,0002,EupInfo has been recorded.
 235,0003,Record native key-value list.
 235,0004,Native key-value list has been recorded.
 235,0005,Record native log.
 235,0000,Native log has not been initiated.
 235,0006,Native log has been recorded.
[BuglyService.cpp][clearEupInfo][283]Clear eupInfo object.
 235,0005,Try to unlock file: /root/.config/QQ/crash_files//../files/native_record_lock
 235,0006,Successfully unlock file: /root/.config/QQ/crash_files//../files/native_record_lock
[BuglyService.cpp][handleSignal][441]Restored signal handlers.
2024-04-16 02:22:42,432 INFO reaped unknown pid 8 (exit status 1)
```

### OneBot 客户端运行日志

```shell
04-16 10:29:25 [INFO] nonebot | Matcher <Matcher from basic_plugins.chat_history.chat_message, type=message, priority=1, temp=False> running complete
{'time': 1713234564, 'self_id': --------, 'post_type': 'message', 'sub_type': 'normal', 'user_id': ---------, 'message_type': 'group', 'message_id': 2644, 'message': [{'type': 'text', 'data': {'text': 'pick'}}], 'original_message': [{'type': 'text', 'data': {'text': 'pick'}}], 'raw_message': 'pick', 'font': 14, 'sender': {'user_id': ----------, 'nickname': '---', 'sex': None, 'age': None, 'card': 'ForE(ᗜ ˰ ᗜ)', 'area': None, 'level': None, 'role': 'admin', 'title': None}, 'to_me': False, 'reply': None, 'group_id': --------, 'anonymous': None, 'message_format': 'array', 'real_id': 2644}
04-16 10:29:25 [INFO] nonebot | Matcher <Matcher from my_plugins.intercept_withdraw, type=message, priority=1, temp=False> running complete
04-16 10:29:25 [INFO] nonebot | Event will be handled by <Matcher from my_plugins.nonebot_zhenxun_plugin_bottle, type=message, priority=5, temp=False>
04-16 10:29:25 [WARNING] nonebot | OneBot V11 | WebSocket for Bot ------- closed by peer
04-16 10:29:25 [INFO] websockets | connection closed
04-16 10:29:42 [INFO] uvicorn | ('172.17.0.5', 53740) - "WebSocket /onebot/v11/ws" [accepted]
04-16 10:29:42 [INFO] nonebot | OneBot V11 | Bot -------- connected
04-16 10:29:42 [INFO] websockets | connection open
04-16 10:29:55 [INFO] nonebot | Matcher <Matcher from my_plugins.nonebot_zhenxun_plugin_bottle, type=message, priority=5, temp=False> running complete
04-16 10:29:55 [ERROR] nonebot | Running matcher <Matcher from my_plugins.nonebot_zhenxun_plugin_bottle, type=message, priority=5, temp=False> failed.
Traceback (most recent call last):
  File "/home/zhenxun_bot/bot.py", line 22, in <module>
    nonebot.run()
  File "/usr/local/lib/python3.9/site-packages/nonebot/__init__.py", line 261, in run
    get_driver().run(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/nonebot/drivers/fastapi.py", line 170, in run
    uvicorn.run(
  File "/usr/local/lib/python3.9/site-packages/uvicorn/main.py", line 576, in run
    server.run()
  File "/usr/local/lib/python3.9/site-packages/uvicorn/server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/local/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/local/lib/python3.9/site-packages/nonebot/message.py", line 146, in _check_matcher
    await _run_matcher(Matcher, bot, event, state, stack, dependency_cache)
> File "/usr/local/lib/python3.9/site-packages/nonebot/message.py", line 196, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "/usr/local/lib/python3.9/site-packages/nonebot/internal/matcher.py", line 672, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "/usr/local/lib/python3.9/site-packages/nonebot/internal/matcher.py", line 639, in simple_run
    await handler(
  File "/usr/local/lib/python3.9/site-packages/nonebot/dependencies/__init__.py", line 92, in __call__
    return await self.call(**values)
  File "/home/zhenxun_bot/my_plugins/nonebot_zhenxun_plugin_bottle/__init__.py", line 114, in _
    await bot.send_group_forward_msg(group_id=event.group_id, messages=msg_list)
  File "/usr/local/lib/python3.9/site-packages/nonebot/internal/adapter/bot.py", line 117, in call_api
    raise exception
  File "/usr/local/lib/python3.9/site-packages/nonebot/internal/adapter/bot.py", line 94, in call_api
    result = await self.adapter._call_api(self, api, **data)
  File "/usr/local/lib/python3.9/site-packages/nonebot/adapters/onebot/v11/adapter.py", line 136, in _call_api
    raise NetworkError(f"WebSocket call api {api} timeout") from None
nonebot.adapters.onebot.v11.exception.NetworkError: <NetWorkError message=WebSocket call api send_group_forward_msg timeout>
```

04-16 10:29:42 [INFO] nonebot | OneBot V11 | Bot -------- connected 这里的重连是我重启了napcat容器

**Comment by linyuchen** [comment]
发送图片传入的file是文件名导致的，暂时不支持这种方式，下版本修复

**Comment by MliKiowa** [comment]
已修复
