### ISSUE TITLE
[BUG] 图片文件下载失败

### ISSUE THREAD

**Issue by NothAmor** [NapNeko/NapCatQQ#10]
### 系统版本

Windows10专业版

### QQNT 版本

9.9.9-23361 (64位)

### NapCat 版本

1.1.1

### OneBot 客户端

1

### 发生了什么?

写了一个简单的消息转发功能，当NapCat在接收图片信息时下载失败，感觉有点奇怪，很少一部分图片或表情正常转发，很大一部分图片下载失败，如下图就只有最后一个图片没有正常转发

![fd0018da2530a9ea4b9d05ead986a9dc](https://github.com/NapNeko/NapCatQQ/assets/18628718/54a1ae74-2551-48bf-920c-3437cf74b3f3)
![f92ffe8bfcaa9b6213780382526aa8df](https://github.com/NapNeko/NapCatQQ/assets/18628718/bbc00f26-77a7-4356-b31e-e50f7ad41d89)

### 如何复现

接收图片时

### 期望的结果?

正常下载图片并转发

### NapCat 运行日志

```shell
正在记录消息到数据库 7364158031059186902
ws 消息上报  {
  self_id: 359980882,
  user_id: 1565481748,
  time: 1714601653,
  message_id: 5,
  real_id: 5,
  message_type: 'private',
  sender: { user_id: 1565481748, nickname: '空虚公子', card: '' },
  raw_message: '[CQ:image,file=30E0643C9F194928021EE2787C223D60.png,url=https://gchat.qpic.cn/download?appid=1407&amp;fileid=CgoxNTY1NDgxNzQ4EhTKkkInXYZsUiki0lwZH0r1Tg779Bjni5oBIP4KKITx9_O87YUDUIC7Lw&amp;rkey=CAQSKAB6JWENi5LMk0kc62l8Pm3Jn1dsLZHyRLAnNmHGoZ3y_gDZPqZt-64&amp;spec=0,file_size=2524647]',
  font: 14,
  sub_type: 'friend',
  message: [ { data: [Object], type: 'image' } ],
  message_format: 'array',
  post_type: 'message'
}
收到正向Websocket消息 {
  action: 'send_group_msg',
  params: {
    group_id: 615383756,
    message: '[CQ:image,url=https://gchat.qpic.cn/download?appid=1407&amp;fileid=CgoxNTY1NDgxNzQ4EhTKkkInXYZsUiki0lwZH0r1Tg779Bjni5oBIP4KKITx9_O87YUDUIC7Lw&amp;rkey=CAQSKAB6JWENi5LMk0kc62l8Pm3Jn1dsLZHyRLAnNmHGoZ3y_gDZPqZt-64&amp;spec=0,file_size=2524647,file=30E0643C9F194928021EE2787C223D60.png]'
  },
  echo: 3
}
找到文件缓存 https://gchat.qpic.cn/download?appid=1407&fileid=CgoxNTY1NDgxNzQ4EhTKkkInXYZsUiki0lwZH0r1Tg779Bjni5oBIP4KKITx9_O87YUDUIC7Lw&rkey=CAQSKAB6JWENi5LMk0kc62l8Pm3Jn1dsLZHyRLAnNmHGoZ3y_gDZPqZt-64&spec=0
文件下载失败 https://gchat.qpic.cn/download?appid=1407&fileid=CgoxNTY1NDgxNzQ4EhTKkkInXYZsUiki0lwZH0r1Tg779Bjni5oBIP4KKITx9_O87YUDUIC7Lw&rkey=CAQSKAB6JWENi5LMk0kc62l8Pm3Jn1dsLZHyRLAnNmHGoZ3y_gDZPqZt-64&spec=0下载失败,Error: 
下载文件失败: Not Found
发生错误 Error: 文件下载失败https://gchat.qpic.cn/download?appid=1407&fileid=CgoxNTY1NDgxNzQ4EhTKkkInXYZsUiki0lwZH0r1Tg779Bjni5oBIP4KKITx9_O87YUDUIC7Lw&rkey=CAQSKAB6JWENi5LMk0kc62l8Pm3Jn1dsLZHyRLAnNmHGoZ3y_gDZPqZt-64&spec=0下
载失败,Error: 下载文件失败: Not Found
    at Object.seleJ (C:\Users\i\Desktop\NapCat.win32.x64\napcat.cjs:15:195148)
    at $c (C:\Users\i\Desktop\NapCat.win32.x64\napcat.cjs:15:197237)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async lv._handle (C:\Users\i\Desktop\NapCat.win32.x64\napcat.cjs:15:203322)
    at async lv.websocketHandle (C:\Users\i\Desktop\NapCat.win32.x64\napcat.cjs:15:176819)
    at async Om.handleAction (C:\Users\i\Desktop\NapCat.win32.x64\napcat.cjs:23:148351)
ws 消息上报  {
  status: 'failed',
  retcode: 1200,
  data: null,
  message: 'Error: 文件下载失败https://gchat.qpic.cn/download?appid=1407&fileid=CgoxNTY1NDgxNzQ4EhTKkkInXYZsUiki0lwZH0r1Tg779Bjni5oBIP4KKITx9_O87YUDUIC7Lw&rkey=CAQSKAB6JWENi5LMk0kc62l8Pm3Jn1dsLZHyRLAnNmHGoZ3y_gDZPqZt-64&spec=0下载失败,Error: 下载文件失败: Not Found\n' +
    '    at Object.seleJ (C:\\Users\\i\\Desktop\\NapCat.win32.x64\\napcat.cjs:15:195148)\n' +
    '    at $c (C:\\Users\\i\\Desktop\\NapCat.win32.x64\\napcat.cjs:15:197237)\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
    '    at async lv._handle (C:\\Users\\i\\Desktop\\NapCat.win32.x64\\napcat.cjs:15:203322)\n' +
    '    at async lv.websocketHandle (C:\\Users\\i\\Desktop\\NapCat.win32.x64\\napcat.cjs:15:176819)\n' +
    '    at async Om.handleAction (C:\\Users\\i\\Desktop\\NapCat.win32.x64\\napcat.cjs:23:148351)',
  wording: 'Error: 文件下载失败https://gchat.qpic.cn/download?appid=1407&fileid=CgoxNTY1NDgxNzQ4EhTKkkInXYZsUiki0lwZH0r1Tg779Bjni5oBIP4KKITx9_O87YUDUIC7Lw&rkey=CAQSKAB6JWENi5LMk0kc62l8Pm3Jn1dsLZHyRLAnNmHGoZ3y_gDZPqZt-64&spec=0下载失败,Error: 下载文件失败: Not Found\n' +
    '    at Object.seleJ (C:\\Users\\i\\Desktop\\NapCat.win32.x64\\napcat.cjs:15:195148)\n' +
    '    at $c (C:\\Users\\i\\Desktop\\NapCat.win32.x64\\napcat.cjs:15:197237)\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
    '    at async lv._handle (C:\\Users\\i\\Desktop\\NapCat.win32.x64\\napcat.cjs:15:203322)\n' +
    '    at async lv.websocketHandle (C:\\Users\\i\\Desktop\\NapCat.win32.x64\\napcat.cjs:15:176819)\n' +
    '    at async Om.handleAction (C:\\Users\\i\\Desktop\\NapCat.win32.x64\\napcat.cjs:23:148351)',
  echo: 3
}
```

**Comment by linyuchen** [comment]
图片问题下版本已修复，急着用可以到action下载最新beta版
