### ISSUE TITLE
[BUG] 启动失败 code: 'ERR_DLOPEN_FAILED'

### ISSUE THREAD

**Issue by y1meng** [NapNeko/NapCatQQ#12]
### 系统版本

Ubuntu 22.04.3 LTS

### QQNT 版本

Linux QQ 2.3.7-23361

### NapCat 版本

NapCatQQ v1.2.0(beta)

### OneBot 客户端

overflow 216

### 发生了什么?

执行napcat.sh文件，无法正确启动

### 如何复现

1.按照教程安装了Linux QQ 2.3.7-23361
但是运行`qq`命令 提示：
`
[0506/235513.745721:FATAL:electron_main_delegate.cc(294)] Running as root without --no-sandbox is not supported. See https://crbug.com/638180.
Trace/breakpoint trap (core dumped)
`
因为我的服务器没有gui，不确定这样是否算安装成功

2.运行`./napcat.sh`命令出现以下输出
`
/home/qq/node_modules/bindings/bindings.js:121
        throw e;
        ^
Error: /home/qq/node_modules/sqlite3/build/Release/node_sqlite3.node: cannot open shared object file: No such file or directory
    at process.func [as dlopen] (node:electron/js2c/asar_bundle:2:2792)
    at Module._extensions..node (node:internal/modules/cjs/loader:1356:18)
    at Object.func [as .node] (node:electron/js2c/asar_bundle:2:2792)
    at Module.load (node:internal/modules/cjs/loader:1126:32)
    at Module._load (node:internal/modules/cjs/loader:967:12)
    at u._load (node:electron/js2c/asar_bundle:2:14589)
    at Module.require (node:internal/modules/cjs/loader:1150:19)
    at require (node:internal/modules/cjs/helpers:119:18)
    at bindings (/home/qq/node_modules/bindings/bindings.js:112:48)
    at Object.<anonymous> (/home/qq/node_modules/sqlite3/lib/sqlite3-binding.js:1:37) {
  code: 'ERR_DLOPEN_FAILED'
}

Node.js v18.18.2
`

### 期望的结果?

不出现错误

**Comment by linyuchen** [comment]
检查下`/home/qq/node_modules/sqlite3/build/Release/node_sqlite3.node`是否存在，
如果不存在，你用release的版本或者Action里面的1.3.0的最新beta试试

**Comment by y1meng** [comment]
> 检查下`/home/qq/node_modules/sqlite3/build/Release/node_sqlite3.node`是否存在， 如果不存在，你用release的版本或者Action里面的1.3.0的最新beta试试
![image](https://github.com/NapNeko/NapCatQQ/assets/45099938/02e14c3f-315a-4012-9000-02b2fb4ffd28)
这个文件是存在的,我在release和action里面没有看到1.3.0

**Comment by linyuchen** [comment]
下错了版本？x64的下成了arm64？

**Comment by y1meng** [comment]
> 下错了版本？x64的下成了arm64？

确实换成x64版本就可以了,我以为能运行版本就没有问题，非常感谢您的帮助
