### ISSUE TITLE
[BUG] 下载base64文件时报错

### ISSUE THREAD

**Issue by Natane0808** [NapNeko/NapCatQQ#13]
### 系统版本

CentOS 9 Stream

### QQNT 版本

2.3.7-23361

### NapCat 版本

1.2.0

### OneBot 客户端

Overflow v2.16.0-a799c07-SNAPSHOT

### 发生了什么?

使用[bilibili-dynamic](https://github.com/Colter23/bilibili-dynamic-mirai-plugin)插件订阅查询动态时napCat报错

### 如何复现

输入命令 /bili new 928123

### 期望的结果?

正常返回生成的动态图片

### NapCat 运行日志

```shell
2024-05-06 07:32:24 W/Onebot: Request failed: [send_group_msg] app=NapCat.Onebot v1.2.0, message=Error: 文件下载失败uri !base64://iVBORw0KGgoAAAANSUhEUgAAA+gAAAMRCAYAAAB/[太长了此处省略base64格式]不存在 
    at Object.CcXvz (/usr/src/app/napcat/napcat.cjs:10049:13032)
    at createSendElements (/usr/src/app/napcat/napcat.cjs:10049:19373)
    at async SendGroupMsg._handle (/usr/src/app/napcat/napcat.cjs:10049:31772)
    at async SendGroupMsg.websocketHandle (/usr/src/app/napcat/napcat.cjs:10043:6389)
    at async OB11WebsocketServer.handleAction (/usr/src/app/napcat/napcat.cjs:10660:5664), retJson={"status":"failed","retcode":1200,"data":null,"message":"Error: 文件下载失败uri !base64://iVBORw0KGgoAAAANSUhEUgAAA+gAAAMRCAYAAAB/[太长了此处省略base64格式]
```

**Comment by linyuchen** [comment]
`!base64://`，前面这个感叹号是怎么回事

**Comment by MliKiowa** [comment]
给的URL有问题 非napcat问题
