### ISSUE TITLE
[BUG] 获取群文件失败，get_group_file_list返回空

### ISSUE THREAD

**Issue by Xuwznln** [NapNeko/NapCatQQ#178]
### 系统版本

Ubuntu 24.04

### QQNT 版本

9.9.12-26000

### NapCat 版本

1.7.1

### OneBot 客户端

/

### 发生了什么?

获取文件夹路径时产生错误，返回空列表
```json
{
    "status": "ok",
    "retcode": 0,
    "data": {
        "FileList": []
    },
    "message": "",
    "wording": "",
    "echo": null
}
```

### 如何复现

请求/get_group_file_list即可复现
```json
{
    "group_id":XXX,
    "start_index": 1,
    "file_count": 1
}
```

### 期望的结果?

正常返回文件列表

### NapCat 运行日志

```shell
(node:98723) UnhandledPromiseRejectionWarning: TypeError: Cannot read properties of undefined (reading 'bind')
    at NTEventWrapper.CreatEventFunction (file:///opt/QQ/resources/app/app_launcher/napcat/napcat.mjs:9576:21)
    at file:///opt/QQ/resources/app/app_launcher/napcat/napcat.mjs:9699:30
    at new Promise (<anonymous>)
    at NTEventWrapper.CallNormalEvent (file:///opt/QQ/resources/app/app_launcher/napcat/napcat.mjs:9662:12)
    at NTQQMsgApi.getGroupFileList (file:///opt/QQ/resources/app/app_launcher/napcat/napcat.mjs:10493:38)
    at GetGroupFileList._handle (file:///opt/QQ/resources/app/app_launcher/napcat/napcat.mjs:25763:34)
    at GetGroupFileList.handle (file:///opt/QQ/resources/app/app_launcher/napcat/napcat.mjs:21669:34)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async file:///opt/QQ/resources/app/app_launcher/napcat/napcat.mjs:22963:18
(node:98723) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 404)
```

**Comment by MliKiowa** [comment]
这个Api Tx改了 下个版本修
