### ISSUE TITLE
[BUG] 运行过程中会报错并退出程序

### ISSUE THREAD

**Issue by W1ndys** [NapNeko/NapCatQQ#195]
### 系统版本

Linux Ubuntu

### QQNT 版本

3.2.7

### NapCat 版本

1.7.3   1.7.1 都有

### OneBot 客户端

自己写的Python

### 发生了什么?

报错
```
file:///home/bot/NapCat.linux.x64/napcat.mjs:27386
      if (![GroupNotifyTypes.INVITE_ME, GroupNotifyTypes.ADMIN_SET, GroupNotifyTypes.ADMIN_UNSET, GroupNotifyTypes.ADMIN_UNSET_OTHER].includes(notifies[0].type)) {
                                                                                                                                                           ^

TypeError: Cannot read properties of undefined (reading 'type')
    at groupListener.onGroupNotifiesUpdated (file:///home/bot/NapCat.linux.x64/napcat.mjs:27386:156)
```
然后自动退出

### 如何复现

偶然事件

### 期望的结果?

正常运行

### NapCat 运行日志

```shell
file:///home/bot/NapCat.linux.x64/napcat.mjs:27386
      if (![GroupNotifyTypes.INVITE_ME, GroupNotifyTypes.ADMIN_SET, GroupNotifyTypes.ADMIN_UNSET, GroupNotifyTypes.ADMIN_UNSET_OTHER].includes(notifies[0].type)) {
                                                                                                                                                           ^

TypeError: Cannot read properties of undefined (reading 'type')
    at groupListener.onGroupNotifiesUpdated (file:///home/bot/NapCat.linux.x64/napcat.mjs:27386:156)
```

### OneBot 客户端运行日志

```shell
无
```

**Comment by MliKiowa** [comment]
使用一键脚本 提高版本

**Comment by MliKiowa** [comment]
或者docker

**Comment by W1ndys** [comment]
> 使用一键脚本 提高版本

一键脚本安装完成后报错啥意思
```
安装完成，请输入 xvfb-run qq --no-sandbox 命令启动。
保持后台运行 请输入 nohup xvfb-run qq --no-sandbox > nul 2> nul &
后台快速登录 请输入 nohup xvfb-run qq --no-sandbox -q QQ号码 > nul 2> nul &
注意，如使用了后台运行命令，请在结束SSH终端前使用exit退出登录。
root@w1ndys-qd:/home/w1ndys/napcatQQ/w1ndys-bot/new_app# xvfb-run qq --no-sandbox
/usr/bin/xvfb-run: 184: qq: not found
root@w1ndys-qd:/home/w1ndys/napcatQQ/w1ndys-bot/new_app# 
```

**Comment by W1ndys** [comment]
原来的也不能用了，怎么恢复
```
root@w1ndys-qd:/home/w1ndys/napcatQQ/NapCat.linux.x64# ./napcat.sh
[0802/003912.430424:FATAL:electron_main_delegate.cc(295)] Running as root without --no-sandbox is not supported. See https://crbug.com/638180.
./napcat.sh: line 21: 28037 Trace/breakpoint trap   (core dumped) /opt/QQ/qq "${SCRIPT_DIR}/napcat.mjs" "$@"

```

**Comment by W1ndys** [comment]
> 使用一键脚本 提高版本

现在最推荐的安装方法是脚本吗🤔

**Comment by MliKiowa** [comment]
对

**Comment by W1ndys** [comment]
> 对

感谢回复，那如果我想多开的话，脚本安装能不能实现
