### ISSUE TITLE
[BUG] 无法发送戳一戳

### ISSUE THREAD

**Issue by Ninethnine** [NapNeko/NapCatQQ#197]
### 系统版本

Linux Ubuntu Server 22.04 LTS 64bit

### QQNT 版本

3.2.10

### NapCat 版本

1.7.3

### OneBot 客户端

overflow-core-all-2.16.0-bc70f0b-20240728.084729-1-all.jar

### 发生了什么?

![image](https://github.com/user-attachments/assets/a873bde4-2e98-481f-96e5-79a6098c0b39)
发送戳一戳消息报错

### 如何复现

使机器人bot发送戳一戳消息

### 期望的结果?

正常发送戳一戳

### NapCat 运行日志

```shell
| 发生错误 TypeError: handlers[sendMsg.type] is not a function
    at createSendElements (file:///opt/QQ/resources/app/app_launcher/napcat/napcat.mjs:22057:46)
    at SendGroupMsg._handle (file:///opt/QQ/resources/app/app_launcher/napcat/napcat.mjs:22353:15)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async SendGroupMsg.websocketHandle (file:///opt/QQ/resources/app/app_launcher/napcat/napcat.mjs:21764:23)
    at async OB11WebsocketServer.handleAction (file:///opt/QQ/resources/app/app_launcher/napcat/napcat.mjs:27029:28)
```

**Comment by lumia1998** [comment]
机器人能发戳一戳吗
只知道能接受戳一戳动作知道是谁戳的

**Comment by Ninethnine** [comment]
> 机器人能发戳一戳吗 只知道能接受戳一戳动作知道是谁戳的

mirai文档是有发送戳一戳的功能的

**Comment by lumia1998** [comment]
mira以前用的icqq啊你说ntqq干嘛? ntqq还没

**Comment by Ninethnine** [comment]
> mira以前用的icqq啊你说ntqq干嘛? ntqq还没
哦这样吗，我的问题抱歉，马上close
