### ISSUE TITLE
无法发送本地图片[BUG] 

### ISSUE THREAD

**Issue by lumia1998** [NapNeko/NapCatQQ#198]
### 系统版本

docker latest

### QQNT 版本

最新

### NapCat 版本

1.7.3

### OneBot 客户端

koishi

### 发生了什么?

首先koishi和napcat是2个docker,然后我koishi的目录挂载到napcat的/koishi,这样后koishi发送他<img src="file:///koishi/data/assets/e1653df8ed3fd56712a95c9fca67f6450bb76747-3D263A5DB8837EAAC5460709DB7AFA04.png"/>这张图的时候napcat的/koishi/data/assets也是有这张图的,但是是发送失败的在下面

可以看到uci的地址是错误的应该是file:///xxxx而不是/xxx,但是后面显示的url路径是对的

### 如何复现

koishi使用dialogue插件发送
 # 指令 图片
之后qq里使用指令调用dialogue发送图片就能复现

### 期望的结果?

让他正常运行

### NapCat 运行日志

```shell
文件下载失败 uri /koishi/data/assets/e1653df8ed3fd56712a95c9fca67f6450bb76747-3D263A5DB8837EAAC5460709DB7AFA04.png 解析失败,TypeError: Invalid URL 可能/koishi/data/assets/e1653df8ed3fd56712a95c9fca67f6450bb76747-3D263A5DB8837EAAC5460709DB7AFA04.png不存在 
2024-08-02 10:54:41 [[91mERROR[39m] [35m亚托莉(1533812459)[39m | 发生错误 Error: 文件下载失败uri /koishi/data/assets/e1653df8ed3fd56712a95c9fca67f6450bb76747-3D263A5DB8837EAAC5460709DB7AFA04.png 解析失败,TypeError: Invalid URL 可能/koishi/data/assets/e1653df8ed3fd56712a95c9fca67f6450bb76747-3D263A5DB8837EAAC5460709DB7AFA04.png不存在
    at handleOb11FileLikeMessage (file:///usr/src/app/napcat/napcat.mjs:21882:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Object.image (file:///usr/src/app/napcat/napcat.mjs:21936:57)
    at async Promise.all (index 0)
    at async createSendElements (file:///usr/src/app/napcat/napcat.mjs:22063:15)
    at async SendGroupMsg._handle (file:///usr/src/app/napcat/napcat.mjs:22353:9)
    at async SendGroupMsg.websocketHandle (file:///usr/src/app/napcat/napcat.mjs:21764:23)
    at async ReverseWebsocket.onmessage (file:///usr/src/app/napcat/napcat.mjs:27137:28)
    at async WebSocket.<anonymous> (file:///usr/src/app/napcat/napcat.mjs:27177:7)
```

### OneBot 客户端运行日志

```shell
session Error: Error with request send_group_msg, args: {"group_id":872966382,"message":[{"type":"image","data":{"file":"/koishi/data/assets/e1653df8ed3fd56712a95c9fca67f6450bb76747-3D263A5DB8837EAAC5460709DB7AFA04.png","cache":0}}]}, retcode: 1200
                            at _Internal._get (/koishi/node_modules/koishi-plugin-adapter-onebot/lib/index.js:120:11)
                            at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
                            at async _Internal.<computed> [as sendGroupMsg] (/koishi/node_modules/koishi-plugin-adapter-onebot/lib/index.js:160:20)
                            at async OneBotMessageEncoder.flush (/koishi/node_modules/koishi-plugin-adapter-onebot/lib/index.js:781:330)
                            at async OneBotMessageEncoder.send (/koishi/node_modules/@satorijs/core/lib/index.cjs:616:5)
                            at async Proxy.sendMessage (/koishi/node_modules/@satorijs/core/lib/index.cjs:346:22)
                            at async _MessageBuffer._flush (/koishi/node_modules/koishi-plugin-dialogue/lib/index.js:493:20)
                            at async _MessageBuffer.end (/koishi/node_modules/koishi-plugin-dialogue/lib/index.js:512:5)
                            at async triggerDialogue (/koishi/node_modules/koishi-plugin-dialogue/lib/index.js:581:3)
                            at async /koishi/node_modules/koishi-plugin-dialogue/lib/index.js:596:12
```

**Comment by lumia1998** [comment]
使用lagrange对接koishi的话是能发出图片的

**Comment by MliKiowa** [comment]
有没有原始post数据

**Comment by lumia1998** [comment]
> 有没有原始post数据

这个要在哪里看啊

**Comment by MliKiowa** [comment]
你看看日志

**Comment by lumia1998** [comment]
> 你看看日志

napcat的日志吗?log文件夹的文件还是直接看的日志

**Comment by MliKiowa** [comment]
两边的日志

**Comment by MliKiowa** [comment]
还有文件位置 docker映射配置

**Comment by lumia1998** [comment]
napcat docker配置:
![QQ_1722908085982](https://github.com/user-attachments/assets/d46e6757-446d-4e23-ad9f-ca5e40d042ad)
koishi docker配置:
![QQ_1722908135754](https://github.com/user-attachments/assets/d6a77dcc-609d-4cad-87c0-5b7f11a5f525)

koishi使用的插件:dialogue

dialogue的发送图片路径:<img src="file:///koishi/data/assets/bdd32cf8bd7721f232e8fb1e9b5b361ca026c359-5FF4C41B50DE4757A298AC776FAE6E7B.png"/>

发送图片错误的日志:
koishi:
```
2024-08-06 09:32:31 [I] adapter connect to server: ws://10.1.2.10:23001/
2024-08-06 09:37:22 [W] session Error: Error with request send_group_msg, args: {"group_id":872966382,"message":[{"type":"image","data":{"file":"/koishi/data/assets/bdd32cf8bd7721f232e8fb1e9b5b361ca026c359-5FF4C41B50DE4757A298AC776FAE6E7B.png","cache":0}}]}, retcode: 1200
                            at _Internal._get (/koishi/node_modules/koishi-plugin-adapter-onebot/lib/index.js:120:11)
                            at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
                            at async _Internal.<computed> [as sendGroupMsg] (/koishi/node_modules/koishi-plugin-adapter-onebot/lib/index.js:160:20)
                            at async OneBotMessageEncoder.flush (/koishi/node_modules/koishi-plugin-adapter-onebot/lib/index.js:781:330)
                            at async OneBotMessageEncoder.send (/koishi/node_modules/@satorijs/core/lib/index.cjs:616:5)
                            at async Proxy.sendMessage (/koishi/node_modules/@satorijs/core/lib/index.cjs:346:22)
                            at async _MessageBuffer._flush (/koishi/node_modules/koishi-plugin-dialogue/lib/index.js:493:20)
                            at async _MessageBuffer.end (/koishi/node_modules/koishi-plugin-dialogue/lib/index.js:512:5)
                            at async triggerDialogue (/koishi/node_modules/koishi-plugin-dialogue/lib/index.js:581:3)
                            at async /koishi/node_modules/koishi-plugin-dialogue/lib/index.js:596:12
```

napcat日志:
```
2024-08-06 09:37:19 [INFO] 亚托莉(1533812459) | 群[测试群(872966382)] Lumia(1921620642): # ppp  [图片|https://multimedia.nt.qq.com.cn/download?appid=1407&fileid=CgoxOTIxNjIwNjQyEhS90yz4vXch8jLo-x6bWzYcoCbDWRiygwEg_wookq2JrJ3fhwNQgL2jAQ&spec=0&rkey=CAQSKAB6JWENi5LMhn0DVhkGsr-Tc5nkABfEUB1EGN5QLIonlrzwXFHcFIg] 
2024-08-06 09:37:20 [INFO] 亚托莉(1533812459) | 发送消息 给群聊 群[测试群(872966382)] : 问答已添加，编号为 21。 
2024-08-06 09:37:22 [INFO] 亚托莉(1533812459) | 群[测试群(872966382)] Lumia(1921620642): ppp 
2024-08-06 09:37:22 [ERROR] 亚托莉(1533812459) | 文件下载失败 uri /koishi/data/assets/bdd32cf8bd7721f232e8fb1e9b5b361ca026c359-5FF4C41B50DE4757A298AC776FAE6E7B.png 解析失败,TypeError: Invalid URL 可能/koishi/data/assets/bdd32cf8bd7721f232e8fb1e9b5b361ca026c359-5FF4C41B50DE4757A298AC776FAE6E7B.png不存在 
2024-08-06 09:37:22 [ERROR] 亚托莉(1533812459) | 发生错误 Error: 文件下载失败uri /koishi/data/assets/bdd32cf8bd7721f232e8fb1e9b5b361ca026c359-5FF4C41B50DE4757A298AC776FAE6E7B.png 解析失败,TypeError: Invalid URL 可能/koishi/data/assets/bdd32cf8bd7721f232e8fb1e9b5b361ca026c359-5FF4C41B50DE4757A298AC776FAE6E7B.png不存在
    at handleOb11FileLikeMessage (file:///usr/src/app/napcat/napcat.mjs:22238:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Object.image (file:///usr/src/app/napcat/napcat.mjs:22292:57)
    at async Promise.all (index 0)
    at async createSendElements (file:///usr/src/app/napcat/napcat.mjs:22419:15)
    at async SendGroupMsg._handle (file:///usr/src/app/napcat/napcat.mjs:22705:9)
    at async SendGroupMsg.websocketHandle (file:///usr/src/app/napcat/napcat.mjs:22122:23)
    at async OB11WebsocketServer.handleAction (file:///usr/src/app/napcat/napcat.mjs:27562:28) 
```

koishi的图片存放位置:
![QQ_1722908488126](https://github.com/user-attachments/assets/13f5c9ec-35ba-42be-957d-377b1ab7c6f7)

![QQ_1722908564373](https://github.com/user-attachments/assets/c9a47a8b-0f72-4f1b-9248-9bc2938a0095)

napcat挂载koishi文件夹后图片的位置:
![QQ_1722908704084](https://github.com/user-attachments/assets/7e479438-425c-43ee-93e3-e4698b267ed8)

**Comment by MliKiowa** [comment]
可能插件传了file又传url nc有限file

**Comment by lumia1998** [comment]
> 可能插件传了file又传url nc有限file

我能想到的是koishi发这个图的时候转base64发,但是那个插件一年不更新了请问napcat这有什么解决办法吗?因为lagrange是能发出来的

**Comment by MliKiowa** [comment]
进docker 替换下napcat试试 https://github.com/NapNeko/NapCatQQ/actions/runs/10259584119

**Comment by MliKiowa** [comment]
应该修好了 还有问题群里at下我

**Comment by lumia1998** [comment]
确实修好了,感谢
