### ISSUE TITLE
[BUG] 合并转发消息报错，一段时间后发送成功

### ISSUE THREAD

**Issue by deoxyszc** [NapNeko/NapCatQQ#210]
### 系统版本

ubuntu docker环境

### QQNT 版本

linuxqq_3.2.12

### NapCat 版本

v1.7.7

### OneBot 客户端

nonebot-adapter-onebot 2.2.3

### 发生了什么?

合并转发消息报错，但是一段时间后消息还是成功发出去了

### 如何复现

1. 使用反向ws连接bot
2. bot构建了一条合并转发消息
3. 日志报错，提示NodeIKernelProfileService/fetchUserDetailInfo超时
4. 20分钟后，提示消息转发失败，但实际上该合并转发消息成功发出

### 期望的结果?

可以正常发出合并转发消息

### NapCat 运行日志

```shell
2024-08-05T12:02:33.032272562+08:00 2024-08-05 12:02:33 [INFO] *(*) | 发送消息 给私聊 *: 
2024-08-05T12:02:33.032363754+08:00 由 Another Indie Studio Limited 公司发行的游戏 失落城堡: 遗迹守护者 (¥12.00) 在 UTC 时间 Aug.05 15:00 即将推出免费游玩，预计截至 Aug.19 15:00。 
2024-08-05T12:02:33.477428747+08:00 2024-08-05 12:02:33 [INFO] *(*) | 获取文件类型 png /root/.config/QQ/NapCat/temp/c56b53c1-7586-4e09-9fcd-8679fef5bcb3rawmen-165o9.png 
2024-08-05T12:02:34.467715495+08:00 2024-08-05 12:02:34 [INFO] *(*) | 获取文件类型 jpg /root/.config/QQ/NapCat/temp/0d7c79eb-1f46-40cd-a514-ac3c61449f55apex-legends-1lcnz.jpg 
2024-08-05 12:02:38 [ERROR] *(*) | Error: Timeout: NTEvent EventName:NodeIKernelProfileService/fetchUserDetailInfo ListenerName:NodeIKernelProfileListener/onUserDetailInfoChanged EventRet:
2024-08-05T12:02:38.210684704+08:00 {}
2024-08-05T12:02:38.210701501+08:00 
2024-08-05T12:02:38.210715314+08:00     at Timeout.databack [as _onTimeout] (file:///usr/src/app/napcat/napcat.mjs:9834:18)
2024-08-05T12:02:38.210728933+08:00     at listOnTimeout (node:internal/timers:573:17)
2024-08-05T12:02:38.210741669+08:00     at process.processTimers (node:internal/timers:514:7) 
2024-08-05T12:02:39.275470856+08:00 2024-08-05 12:02:39 [ERROR] *(*) | Error: Timeout: NTEvent EventName:NodeIKernelProfileService/fetchUserDetailInfo ListenerName:NodeIKernelProfileListener/onUserDetailInfoChanged EventRet:
2024-08-05T12:02:39.275547078+08:00 {}
2024-08-05T12:02:39.275562109+08:00 
2024-08-05T12:02:39.275575785+08:00     at Timeout.databack [as _onTimeout] (file:///usr/src/app/napcat/napcat.mjs:9834:18)
2024-08-05T12:02:39.275590612+08:00     at listOnTimeout (node:internal/timers:573:17)
2024-08-05T12:02:39.275605744+08:00     at process.processTimers (node:internal/timers:514:7) 
2024-08-05T12:02:40.078140864+08:00 2024-08-05 12:02:40 [ERROR] *(*) | Error: Timeout: NTEvent EventName:NodeIKernelProfileService/fetchUserDetailInfo ListenerName:NodeIKernelProfileListener/onUserDetailInfoChanged EventRet:
2024-08-05T12:02:40.078216447+08:00 {}
2024-08-05T12:02:40.078233612+08:00 
2024-08-05T12:02:40.078249893+08:00     at Timeout.databack [as _onTimeout] (file:///usr/src/app/napcat/napcat.mjs:9834:18)
2024-08-05T12:02:40.078264253+08:00     at listOnTimeout (node:internal/timers:573:17)
    at process.processTimers (node:internal/timers:514:7) 
2024-08-05T12:02:40.394077911+08:00 2024-08-05 12:02:40 [ERROR] *(*) | Error: Timeout: NTEvent EventName:NodeIKernelProfileService/fetchUserDetailInfo ListenerName:NodeIKernelProfileListener/onUserDetailInfoChanged EventRet:
2024-08-05T12:02:40.394156652+08:00 {}
2024-08-05T12:02:40.394171388+08:00 
2024-08-05T12:02:40.394187768+08:00     at Timeout.databack [as _onTimeout] (file:///usr/src/app/napcat/napcat.mjs:9834:18)
2024-08-05T12:02:40.394203740+08:00     at listOnTimeout (node:internal/timers:573:17)
2024-08-05T12:02:40.394217145+08:00     at process.processTimers (node:internal/timers:514:7) 
2024-08-05T12:22:49.920878631+08:00 2024-08-05 12:22:49 [INFO] *(*) | 发送消息 给群聊 群[] : [json|{"data":"{\"app\":\"com.tencent.multimsg\",\"config\":{\"autosize\":1,\"forward\":1,\"round\":1,\"type\":\"normal\",\"width\":300},\"desc\":\"[聊天记录]\",\"extra\":\"{\\\"filename\\\":\\\"0533b598-3d86-489b-9eb7-d1494796cbc1\\\",\\\"tsum\\\":6}\\n\",\"meta\":{\"detail\":{\"news\":[{\"text\":\"*: [图片]\\n\\nFREE now :: LumbearJack (¥52.00)\\n快快拿起你的斧头，砍掉和回收挡路的人造物件，与迷人\"},{\"text\":\"*: \\n由 Another Indie Studio Limited 公司发行的游戏 失落城堡: 遗迹守护者 (¥12.00) 在 U\"},{\"text\":\"*: \\n由 Serenity Forge 公司发行的游戏 《LISA: Definitive Edition》 (¥108.00) 在\"},{\"text\":\"*: [图片]\\n\\nFREE now :: 《RAWMEN: Food Fighter Arena》🍜 (0)\\n《RAWMEN》将竞技场\"}],\"resid\":\"0k8mIV7ifECcOVuH7DJFHUBf8x67D4gD7xJzbDwGyHpFQP5G6CTtmNWQPVWWpcwP\",\"source\":\"*的聊天记录\",\"summary\":\"查看6条转发消息\",\"uniseq\":\"0533b598-3d86-489b-9eb7-d1494796cbc1\"}},\"prompt\":\"[聊天记录]\",\"ver\":\"0.0.0.5\",\"view\":\"contact\"}\n"}] 
2024-08-05T12:22:50.062490445+08:00 2024-08-05 12:22:50 [INFO] *(*) |
 发送消息 给群聊 群[] : [json|{"data":"{\"app\":\"com.tencent.multimsg\",\"config\":{\"autosize\":1,\"forward\":1,\"round\":1,\"type\":\"normal\",\"width\":300},\"desc\":\"[聊天记录]\",\"extra\":\"{\\\"filename\\\":\\\"6bfbf1fd-c46b-4a10-8ce8-d2ac1dd1901c\\\",\\\"tsum\\\":6}\\n\",\"meta\":{\"detail\":{\"news\":[{\"text\":\"*: [图片]\\n\\nFREE now :: LumbearJack (¥52.00)\\n快快拿起你的斧头，砍掉和回收挡路的人造物件，与迷人\"},{\"text\":\"*: \\n由 Another Indie Studio Limited 公司发行的游戏 失落城堡: 遗迹守护者 (¥12.00) 在 U\"},{\"text\":\"*: \\n由 Serenity Forge 公司发行的游戏 《LISA: Definitive Edition》 (¥108.00) 在\"},{\"text\":\"*: [图片]\\n\\nFREE now :: 《RAWMEN: Food Fighter Arena》🍜 (0)\\n《RAWMEN》将竞技场\"}],\"resid\":\"tWaHJkdeeyQ4x/Bcx3e0Nd6JxIziSHe0GscVkdPFW4CuXQqny9f8IjJdi7lWxijZ\",\"source\":\"*的聊天记录\",\"summary\":\"查看6条转发消息\",\"uniseq\":\"6bfbf1fd-c46b-4a10-8ce8-d2ac1dd1901c\"}},\"prompt\":\"[聊天记录]\",\"ver\":\"0.0.0.5\",\"view\":\"contact\"}\n"}] 
2024-08-05T12:22:53.570951932+08:00 2024-08-05 12:22:53 [ERROR] *(*) | forward failed Error: Timeout: NTEvent EventName:NodeIKernelMsgService/multiForwardMsgWithComment ListenerName:NodeIKernelMsgListener/onMsgInfoListUpdate EventRet:
2024-08-05T12:22:53.571018241+08:00 {}
2024-08-05T12:22:53.571034978+08:00 
2024-08-05T12:22:53.571051979+08:00     at Timeout.databack [as _onTimeout] (file:///usr/src/app/napcat/napcat.mjs:9834:18)
2024-08-05T12:22:53.571066228+08:00     at listOnTimeout (node:internal/timers:573:17)
2024-08-05T12:22:53.571079278+08:00     at process.processTimers (node:internal/timers:514:7) 
2024-08-05T12:22:53.571093167+08:00 2024-08-05 12:22:53 [ERROR] *(*) | 发生错误 Error: 发送转发消息失败
2024-08-05T12:22:53.571109207+08:00     at GoCQHTTPSendGroupForwardMsg._handle (fil
e:///usr/src/app/napcat/napcat.mjs:22692:15)
2024-08-05T12:22:53.571124571+08:00     at async GoCQHTTPSendGroupForwardMsg.websocketHandle (file:///usr/src/app/napcat/napcat.mjs:22116:23)
2024-08-05T12:22:53.571138323+08:00     at async ReverseWebsocket.onmessage (file:///usr/src/app/napcat/napcat.mjs:27553:28)
    at async WebSocket.<anonymous> (file:///usr/src/app/napcat/napcat.mjs:27593:7) 
2024-08-05T12:22:53.610904731+08:00 2024-08-05 12:22:53 [ERROR] *(*) | forward failed Error: Timeout: NTEvent EventName:NodeIKernelMsgService/multiForwardMsgWithComment ListenerName:NodeIKernelMsgListener/onMsgInfoListUpdate EventRet:
2024-08-05T12:22:53.610949988+08:00 {}
2024-08-05T12:22:53.610963540+08:00 
2024-08-05T12:22:53.610977382+08:00     at Timeout.databack [as _onTimeout] (file:///usr/src/app/napcat/napcat.mjs:9834:18)
2024-08-05T12:22:53.610992935+08:00     at listOnTimeout (node:internal/timers:573:17)
2024-08-05T12:22:53.611008129+08:00     at process.processTimers (node:internal/timers:514:7) 
2024-08-05T12:22:53.611021894+08:00 2024-08-05 12:22:53 [ERROR] *(*) | 发生错误 Error: 发送转发消息失败
2024-08-05T12:22:53.611034502+08:00     at GoCQHTTPSendGroupForwardMsg._handle (file:///usr/src/app/napcat/napcat.mjs:22692:15)
2024-08-05T12:22:53.611072799+08:00     at async GoCQHTTPSendGroupForwardMsg.websocketHandle (file:///usr/src/app/napcat/napcat.mjs:22116:23)
2024-08-05T12:22:53.611090732+08:00     at async ReverseWebsocket.onmessage (file:///usr/src/app/napcat/napcat.mjs:27553:28)
2024-08-05T12:22:53.611103625+08:00     at async WebSocket.<anonymous> (file:///usr/src/app/napcat/napcat.mjs:27593:7) 
2024-08-05T12:23:51.292191722+08:00 2024-08-05 12:23:51 [INFO] *(*) | 发送消息 给群聊 群[] : [json|{"data":"{\"app\":\"com.tencent.multimsg\",\"config\":{\"autosize\":1,\"forward\":1,\"round\":1,\"type\":\"normal\",\"width\":300},\"desc\":\"[聊天记录]\",\"extra\":\"{\\\"filename\\\":\\\"f2af9232-9860-4d28-8d46-955fdb0ab2de\\\",\\\"tsum\\\":6}\\n\",\"meta\":{\"detail\":{\"news\":[{\"text\":\"*: [图片]\\n\\nFREE now :: LumbearJack (¥52.00)\\n快快拿起你的斧头，砍掉和回收挡路的人造物件，与迷人\"},{\"text\":\"*: \\n��
� Another Indie Studio Limited 公司发行的游戏 失落城堡: 遗迹守护者 (¥12.00) 在 U\"},{\"text\":\"*: \\n由 Serenity Forge 公司发行的游戏 《LISA: Definitive Edition》 (¥108.00) 在\"},{\"text\":\"*: [图片]\\n\\nFREE now :: 《RAWMEN: Food Fighter Arena》🍜 (0)\\n《RAWMEN》将竞技场\"}],\"resid\":\"r0kyMpldyOM7irLYw3SUPZb64MDP6MT1X4F9VMG1jcpTy9IchzPbLKF/mdd7jy+T\",\"source\":\"*的聊天记录\",\"summary\":\"查看6条转发消息\",\"uniseq\":\"f2af9232-9860-4d28-8d46-955fdb0ab2de\"}},\"prompt\":\"[聊天记录]\",\"ver\":\"0.0.0.5\",\"view\":\"contact\"}\n"}]
```

### OneBot 客户端运行日志

```shell
2024-08-05T12:01:31.257556255+08:00 08-05 12:01:31 [ERROR] services | GROUP * epic免费游戏推送错误 <class 'nonebot.adapters.onebot.v11.exception.NetworkError'>: NetWorkError(message='WebSocket call api send_group_forward_msg timeout')
08-05 12:02:01 [ERROR] services | GROUP 80463549 epic免费游戏推送错误 <class 'nonebot.adapters.onebot.v11.exception.NetworkError'>: NetWorkError(message='WebSocket call api send_group_forward_msg timeout')
2024-08-05T12:02:31.272277092+08:00 08-05 12:02:31 [ERROR] services | GROUP * epic免费游戏推送错误 <class 'nonebot.adapters.onebot.v11.exception.NetworkError'>: NetWorkError(message='WebSocket call api send_group_forward_msg timeout')
2024-08-05T12:03:01.276874786+08:00 08-05 12:03:01 [ERROR] services | GROUP * epic免费游戏推送错误 <class 'nonebot.adapters.onebot.v11.exception.NetworkError'>: NetWorkError(message='WebSocket call api send_group_forward_msg timeout')
```

**Comment by MliKiowa** [comment]
更新新版本试试

**Comment by MliKiowa** [comment]
如果还有问题再开issue
