### ISSUE TITLE
[BUG] 无法发送图片

### ISSUE THREAD

**Issue by chuxiaaaa** [NapNeko/NapCatQQ#223]
### 系统版本

Windows Server 2019 DataCenter 64bit CN

### QQNT 版本

9.9.15.26702

### NapCat 版本

1.8.4

### OneBot 客户端

没有使用OneBot 

### 发生了什么?

文本消息可以正常发送，图片无法发出

**调用代码**

```
收到正向Websocket消息 {"action":"send_group_msg","params":{"group_id":group_id,"message":[{"type":"image","data":{"file":"file:///C:\\Users\\Administrator\\Desktop\\测试\\data\\image\\测试\\1167460506.png","type":"","subType":"0","cache":0}}]},"echo":"8cfff871-f892-4662-bb7e-0627a5aaa31a"} 
```

**错误日志**
见 NapCat 运行日志

**补充说明**

- 在旧版本 1.6.1 发送图片没有这个问题
- ~~同一台服务器上的另一个QQ没问题，相同的NapCat版本，相同的调用程序。没问题的QQ一开始也无法正常发送图片，后来在低版本(1.7.2)NapCat发送一张小图片就没问题了，升级到1.8.4版本测试也是正常的~~，正常使用了一个早上之后到下午也出现了大部分图片无法发送
- 尝试过修改 napcat.mjs 文件的超时时间，但依旧无法发送出图片

### 如何复现

不确定

### 期望的结果?

正常发送图片

### NapCat 运行日志

```shell
2024-08-08 09:00:47 [ERROR] Robot(RobotQQ) | 发生错误 Error: Timeout: NTEvent EventName:NodeIKernelMsgService/sendMsg ListenerName:NodeIKernelMsgListener/onMsgInfoListUpdate EventRet:
{
    "result": -1,
    "errMsg": "rich media transfer failed"
}

    at Timeout.databack [as _onTimeout] (file:///C:/Users/Administrator/Desktop/NapCat.win32.x64%20(6)/NapCat.win32.x64/napcat.mjs:9890:18)
    at listOnTimeout (node:internal/timers:573:17)
    at process.processTimers (node:internal/timers:514:7)
```

**Comment by chuxiaaaa** [comment]
1.6.7版本似乎也能正常使用，QQ客户端都是9.9.12，怀疑可能是9.9.15导致的问题

**Comment by airdm** [comment]
2024-08-10 10:22:23 [ERROR] BOT(123456) | 发生错误 Error: Timeout: NTEvent EventName:NodeIKernelMsgService/sendMsg ListenerName:NodeIKernelMsgListener/onMsgInfoListUpdate EventRet:
{}

    at Timeout.databack [as _onTimeout] (file:///E:/QQNT/resources/app/app_launcher/napcat/napcat.mjs:9892:18)
    at listOnTimeout (node:internal/timers:573:17)
    at process.processTimers (node:internal/timers:514:7)

同样问题,无法发送图片. 刚启动前几秒可以发出图片,也就能前几秒能正常发,之后就一直报错.[9.9.15] [1.8.6]

**Comment by chuxiaaaa** [comment]
> 2024-08-10 10:22:23 [ERROR] BOT(123456) | 发生错误 Error: Timeout: NTEvent EventName:NodeIKernelMsgService/sendMsg ListenerName:NodeIKernelMsgListener/onMsgInfoListUpdate EventRet: {}
> 
> ```
> at Timeout.databack [as _onTimeout] (file:///E:/QQNT/resources/app/app_launcher/napcat/napcat.mjs:9892:18)
> at listOnTimeout (node:internal/timers:573:17)
> at process.processTimers (node:internal/timers:514:7)
> ```
> 
> 同样问题,无法发送图片. 刚启动前几秒可以发出图片,也就能前几秒能正常发,之后就一直报错.[9.9.15] [1.8.6]

打开QQ客户端，看看有没有红色感叹号，或者自己尝试发图看看能不能发出去

**Comment by airdm** [comment]
> > 2024-08-10 10:22:23 [ERROR] BOT(123456) | 发生错误 Error: Timeout: NTEvent EventName:NodeIKernelMsgService/sendMsg ListenerName:NodeIKernelMsgListener/onMsgInfoListUpdate EventRet: {}
> > ```
> > at Timeout.databack [as _onTimeout] (file:///E:/QQNT/resources/app/app_launcher/napcat/napcat.mjs:9892:18)
> > at listOnTimeout (node:internal/timers:573:17)
> > at process.processTimers (node:internal/timers:514:7)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 同样问题,无法发送图片. 刚启动前几秒可以发出图片,也就能前几秒能正常发,之后就一直报错.[9.9.15] [1.8.6]
> 
> 打开QQ客户端，看看有没有红色感叹号，或者自己尝试发图看看能不能发出去

我更新了最新版本的QQ已经可以正常使用了.

**Comment by Wesley-Young** [comment]
> 我更新了最新版本的QQ已经可以正常使用了.

@airdm @chuxiaaaa 使用最新版本的 QQ 和 NapCat (V2.0.7) 测试，问题是否仍存在？如果问题解决或 7 天内无回复，则该 issue 将以 completed 的状态关闭。

**Comment by airdm** [comment]
> > 我更新了最新版本的QQ已经可以正常使用了.
> 
> @airdm @chuxiaaaa 使用最新版本的 QQ 和 NapCat (V2.0.7) 测试，问题是否仍存在？如果问题解决或 7 天内无回复，则该 issue 将以 completed 的状态关闭。

2.0.11版本 发送图片报错

PayloadTooLargeError: request entity too large
    at readStream (E:\QQNT\resources\app\app_launcher\napcat\node_modules\raw-body\index.js:163:17)
    at getRawBody (E:\QQNT\resources\app\app_launcher\napcat\node_modules\raw-body\index.js:116:12)
    at read (E:\QQNT\resources\app\app_launcher\napcat\node_modules\body-parser\lib\read.js:76:3)
    at jsonParser (E:\QQNT\resources\app\app_launcher\napcat\node_modules\body-parser\lib\types\json.js:141:5)
    at Layer.handleRequest (E:\QQNT\resources\app\app_launcher\napcat\node_modules\router\lib\layer.js:102:15)
    at trimPrefix (E:\QQNT\resources\app\app_launcher\napcat\node_modules\router\index.js:337:13)
    at E:\QQNT\resources\app\app_launcher\napcat\node_modules\router\index.js:295:9
    at processParams (E:\QQNT\resources\app\app_launcher\napcat\node_modules\router\index.js:575:12)
    at next (E:\QQNT\resources\app\app_launcher\napcat\node_modules\router\index.js:289:5)
    at Function.handle (E:\QQNT\resources\app\app_launcher\napcat\node_modules\router\index.js:183:3)

**Comment by MliKiowa** [comment]
传递非base64数据

**Comment by airdm** [comment]
> 传递非base64数据

用的是CQ 发送的 base64格式 同样的格式内容 1.8.6 可以正常发送

**Comment by MliKiowa** [comment]
> > > 我更新了最新版本的QQ已经可以正常使用了.
> > 
> > 
> > @airdm @chuxiaaaa 使用最新版本的 QQ 和 NapCat (V2.0.7) 测试，问题是否仍存在？如果问题解决或 7 天内无回复，则该 issue 将以 completed 的状态关闭。
> 
> 2.0.11版本 发送图片报错
> 
> PayloadTooLargeError: request entity too large at readStream (E:\QQNT\resources\app\app_launcher\napcat\node_modules\raw-body\index.js:163:17) at getRawBody (E:\QQNT\resources\app\app_launcher\napcat\node_modules\raw-body\index.js:116:12) at read (E:\QQNT\resources\app\app_launcher\napcat\node_modules\body-parser\lib\read.js:76:3) at jsonParser (E:\QQNT\resources\app\app_launcher\napcat\node_modules\body-parser\lib\types\json.js:141:5) at Layer.handleRequest (E:\QQNT\resources\app\app_launcher\napcat\node_modules\router\lib\layer.js:102:15) at trimPrefix (E:\QQNT\resources\app\app_launcher\napcat\node_modules\router\index.js:337:13) at E:\QQNT\resources\app\app_launcher\napcat\node_modules\router\index.js:295:9 at processParams (E:\QQNT\resources\app\app_launcher\napcat\node_modules\router\index.js:575:12) at next (E:\QQNT\resources\app\app_launcher\napcat\node_modules\router\index.js:289:5) at Function.handle (E:\QQNT\resources\app\app_launcher\napcat\node_modules\router\index.js:183:3)

已修

**Comment by MliKiowa** [comment]
尝试26909呢
