### ISSUE TITLE
[BUG]  time out超时

### ISSUE THREAD

**Issue by swyefun** [NapNeko/NapCatQQ#229]
### 系统版本

termux+proot+Ubuntu20.04(成分有点复杂)

### QQNT 版本

3.2.7－19863

### NapCat 版本

1.8.4

### OneBot 客户端

未配置

### 发生了什么?

报错Error: Timeout: NTEvent EventName:NodeIKernelProfileService/getUserDetailInfoWithBizInfo ListenerName:NodeIKernelProfileListener/onProfileDetailInfoChanged EventRet:
{}

    at Timeout.databack [as _onTimeout] (file:///root/NapCat.linux.arm64/napcat.mjs:9890:18)
    at listOnTimeout (node:internal/timers:569:17)
    at process.processTimers (node:internal/timers:512:7) 
这个问题在未配置地址时也会出现
[日志.log](https://github.com/user-attachments/files/16547796/default.log)

### 如何复现

1进入目录
2运行自动登录
3报错

### 期望的结果?

正常运行

### NapCat 运行日志

```shell
2024-08-08 20:05:08 [INFO] () | [QQ版本兼容性检测] 3.2.7-23361 版本兼容性不佳，可能会导致一些功能无法正常使用 
2024-08-08 20:05:09 [INFO] () | [NapCat] [WebUi] Current WebUi is running at http://0.0.0.0:6099 
2024-08-08 20:05:09 [INFO] () | [NapCat] [WebUi] Login URL is http://0.0.0.0:6099/webui 
2024-08-08 20:05:09 [INFO] () | [NapCat] [WebUi] Login Token is 114514 
2024-08-08 20:05:09 [INFO] () | -q 指令指定使用最近的QQ进行快速登录 
2024-08-08 20:05:09 [INFO] () | 正在快速登录  3985849709 
2024-08-08 20:05:10 [DEBUG] () | 检测更新异常 Error: Unexpected status code: 301
    at IncomingMessage.<anonymous> (file:///root/NapCat.linux.arm64/napcat.mjs:9610:22)
    at IncomingMessage.emit (node:events:529:35)
    at endReadableNT (node:internal/streams/readable:1368:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) 
2024-08-08 20:05:14 [INFO] () | [NapCat] 当前版本: 1.8.4 
2024-08-08 20:05:14 [DEBUG] () | [NapCat] 当前已是最新版本 
2024-08-08 20:05:16 [DEBUG] () | 配置文件/root/NapCat.linux.arm64/config/napcat.json已加载 {"name
```

### OneBot 客户端运行日志

```shell
无
```

**Comment by swyefun** [comment]
> 提高QQ版本

Linux 3.2.7-23361更到了这个版本还是一样的问题

**Comment by swyefun** [comment]
![Screenshot_2024_0808_210249](https://github.com/user-attachments/assets/6a3ab714-8140-41a7-a6fc-0f7b7c5168cd)

**Comment by swyefun** [comment]
我知道了文档里面是旧版本我下的是旧版，对不起打扰了是我的问题

**Comment by swyefun** [comment]
更新
