### ISSUE TITLE
[BUG？] 单向好友临时会话无法发送消息

### ISSUE THREAD

**Issue by miiiiiint** [NapNeko/NapCatQQ#237]
### 系统版本

Microsoft Windows 11 专业版

### QQNT 版本

9.9.12-25493

### NapCat 版本

 1.8.6

### OneBot 客户端

nonebot

### 发生了什么?

等待一段时间后，消息发送失败

### 如何复现

bot账号设置正确回答问题添加好友。
其他账号与bot账号此时可以进行会话，但是对于bot账户来说是临时会话。
bot无法在这个会话发送消息。
bot尝试在这个会话发送消息时会出现报错。

### 期望的结果?

正常发送消息

### NapCat 运行日志

```shell
发生错误 Error: Timeout: NTEvent EventName:NodeIKernelMsgService/sendMsg ListenerName:NodeIKernelMsgListener/onMsgInfoListUpdate EventRet:
{
    "result": 1,
    "errMsg": ""
}

    at Timeout.databack [as _onTimeout] (file:///C:/Program%20Files/Tencent/QQNT/resources/app/app_launcher/napcat/napcat.mjs:9892:18)
    at listOnTimeout (node:internal/timers:573:17)
    at process.processTimers (node:internal/timers:514:7)
```

### OneBot 客户端运行日志

```shell
nonebot.adapters.onebot.v11.exception.ActionFailed: ActionFailed(status='failed', retcode=1200, data=None, message='Error: Timeout: NTEvent EventName:NodeIKernelMsgService/sendMsg ListenerName:NodeIKernelMsgListener/onMsgInfoListUpdate EventRet:\n{\n    "result": 1,\n    "errMsg": ""\n}\n\n    at Timeout.databack [as _onTimeout] (file:///C:/Program%20Files/Tencent/QQNT/resources/app/app_launcher/napcat/napcat.mjs:9892:18)\n    at listOnTimeout (node:internal/timers:573:17)\n    at process.processTimers (node:internal/timers:514:7)', wording='Error: Timeout: NTEvent EventName:NodeIKernelMsgService/sendMsg ListenerName:NodeIKernelMsgListener/onMsgInfoListUpdate EventRet:\n{\n    "result": 1,\n    "errMsg": ""\n}\n\n    at Timeout.databack [as _onTimeout] (file:///C:/Program%20Files/Tencent/QQNT/resources/app/app_launcher/napcat/napcat.mjs:9892:18)\n    at listOnTimeout (node:internal/timers:573:17)\n    at process.processTimers (node:internal/timers:514:7)', echo='1')
```

**Comment by airdm** [comment]
你要不要先尝试更新QQ到最新版本试一试?

**Comment by miiiiiint** [comment]
当前已经是最新版本

**Comment by miiiiiint** [comment]
在执行 getUidByUin无法获取到有效的uid，uid为undefined

**Comment by MliKiowa** [comment]
后期将会解决

**Comment by MliKiowa** [comment]
2.2.5已修

**Comment by MliKiowa** [comment]
如果仍有问题开issue
