### ISSUE TITLE
[BUG] 无法发送音乐卡片信息

### ISSUE THREAD

**Issue by Hydrogens2** [NapNeko/NapCatQQ#238]
### 系统版本

Ubuntu 20.04 LTS

### QQNT 版本

3.2.7-23361

### NapCat 版本

1.8.6

### OneBot 客户端

nonebot

### 发生了什么?

正确配置签名服务器的情况下，无法发送音乐卡片信息，不论是自定义卡片信息或是网易云音乐卡片信息。

### 如何复现

1. 生成如下消息段：
 自定义：msg = MessageSegment("music", {"type": "custom", "url": _url, "audio": _audio, "voice": _audio, "title": _name, "content": content, "image": _picurl})
 网易云音乐卡片：msg = MessageSegment.music("163", nid)

2. 发送该消息：
await nonebot.get_bot().call_api("send_msg", group_id=int(gid), message=msg)
await bot.send(event=event, message=Message(msg))

### 期望的结果?

正常发送音乐卡片信息。

### NapCat 运行日志

```shell
2024-08-12 11:28:49 [ERROR] Bot(114514) | 生成音乐消息失败 Error: Unexpected status code: 500
    at IncomingMessage.<anonymous> (file:///home/ubuntu/NapCat.linux.x64/napcat.mjs:9612:22)
    at IncomingMessage.emit (node:events:529:35)
    at endReadableNT (node:internal/streams/readable:1368:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
2024-08-12 11:28:49 [ERROR] Bot(114514) | 发生错误 消息体无法解析, 请检查是否发送了不支持的消息类型
2024-08-12 11:28:50 [ERROR] Bot(114514) | 生成音乐消息失败 Error: Unexpected status code: 500
    at IncomingMessage.<anonymous> (file:///home/ubuntu/NapCat.linux.x64/napcat.mjs:9612:22)
    at IncomingMessage.emit (node:events:529:35)
    at endReadableNT (node:internal/streams/readable:1368:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
2024-08-12 11:28:50 [ERROR] Bot(114514) | 发生错误 消息体无法解析, 请检查是否发送了不支持的消息类型
```

**Comment by MliKiowa** [comment]
服务器返回的500

**Comment by Hydrogens2** [comment]
> 服务器返回的500

是指的签名服务器吗

**Comment by MliKiowa** [comment]
对的 可能挂了

**Comment by Starrain08** [comment]
> 对的 可能挂了

额，有解决办法嘛？

**Comment by Hydrogens2** [comment]
> > 对的 可能挂了
> 
> 额，有解决办法嘛？

sign server 似乎已经修好了

**Comment by FadeJay** [comment]
大佬，想问下签名服务器要怎么做呀，没找到相关的文档说明
