### ISSUE TITLE
[BUG] 发送消息时出错，但能够正常接收消息

### ISSUE THREAD

**Issue by RainyHallways** [NapNeko/NapCatQQ#262]
### 系统版本

Ubuntu 22.04LTS

### QQNT 版本

3.2.12-26909

### NapCat 版本

2.0.24

### OneBot 客户端

正向WS

### 发生了什么?

2024-08-15 22:07:06 [ERROR] nicname(xxxxxxx) | 发>生错误 Error: Timeout: NTEvent EventName:NodeIKernelMsgService/sendMsg ListenerName:NodeIKernelMsgListener/onMsgInfoListUpdate EventRet:                       {                                                        "result": 0,                                         "errMsg": ""                                     }                                                                                                             at Timeout.databack [as _onTimeout] (file:///opt/QQ/resources/app/app_launcher/napcat/napcat.mjs:1119:18)                                                      at listOnTimeout (node:internal/timers:573:17)       at process.processTimers (node:internal/timers:514:7)

### 如何复现

-

### 期望的结果?

正常发送消息

### NapCat 运行日志

```shell
2024-08-15 22:07:06 [ERROR] nickname(xxxxxxxxx) | 发>生错误 Error: Timeout: NTEvent EventName:NodeIKernelMsgService/sendMsg ListenerName:NodeIKernelMsgListener/onMsgInfoListUpdate EventRet:                       {                                                        "result": 0,                                         "errMsg": ""                                     }                                                                                                             at Timeout.databack [as _onTimeout] (file:///opt/QQ/resources/app/app_launcher/napcat/napcat.mjs:1119:18)                                                      at listOnTimeout (node:internal/timers:573:17)       at process.processTimers (node:internal/timers:514:7)
```

### OneBot 客户端运行日志

```shell
-
```

**Comment by MliKiowa** [comment]
发送了什么内容

**Comment by RainyHallways** [comment]
2024-08-16 07:20:52 [INFO]   | 发送 -> 群聊  泥耶耶 加入了服务器                                                 2024-08-16 07:20:52 [INFO]   | 发送 -> 群聊  泥耶耶 加入了 服务器                                               2024-08-16 07:21:02 [ERROR]  | 发 生错误 Error: Timeout: NTEvent EventName:NodeIKernelMsgService/sendMsg ListenerName:NodeIKernelMsgListener/onMsgInfoListUpdate EventRet:                       {                                                        "result": 0,                                         "errMsg": ""                                     }                                                                                                             at Timeout.databack [as _onTimeout] (file:///opt/QQ/resources/app/app_launcher/napcat/napcat.mjs:1119:18)                                                      at listOnTimeout (node:internal/timers:573:17)       at process.processTimers (node:internal/timers:514:7)
2024-08-16 07:21:02 [ERROR]  | 发 生错误 Error: Timeout: NTEvent EventName:NodeIKernelMsgService/sendMsg ListenerName:NodeIKernelMsgListener/onMsgInfoListUpdate EventRet:
{
    "result": 0,                                         "errMsg": ""
}                                                                                                             at Timeout.databack [as _onTimeout] (file:///opt/QQ/resources/app/app_launcher/napcat/napcat.mjs:1119:18)
    at listOnTimeout (node:internal/timers:573:17)
    at process.processTimers (node:internal/timers:514:7)

**Comment by RainyHallways** [comment]
重新登陆后恢复正常

**Comment by cnxysoft** [comment]
> 重新登陆后恢复正常

恭喜。如若再次复现，建议将NC升级至最新版本后再试。
