### ISSUE TITLE
[BUG] 发送消息报错，接收消息正常

### ISSUE THREAD

**Issue by RainyHallways** [NapNeko/NapCatQQ#263]
### 系统版本

Ubuntu 22.04LTS

### QQNT 版本

3.2.12-26909

### NapCat 版本

2.0.24

### OneBot 客户端

正向WS

### 发生了什么?

2024-08-15 22:07:06 [ERROR] nickname(xxxxxxxx) | 发生错误 Error: Timeout: NTEvent EventName:NodeIKernelMsgService/sendMsg ListenerName:NodeIKernelMsgListener/onMsgInfoListUpdate EventRet:                       {                                                        "result": 0,                                         "errMsg": ""                                     }                                                                                                             at Timeout.databack [as _onTimeout] (file:///opt/QQ/resources/app/app_launcher/napcat/napcat.mjs:1119:18)                                                      at listOnTimeout (node:internal/timers:573:17)       at process.processTimers (node:internal/timers:514:7)

### 如何复现

-

### 期望的结果?

正常发送消息

### NapCat 运行日志

```shell
2024-08-15 22:07:06 [ERROR] nickname(xxxxxxxxx) | 发生错误 Error: Timeout: NTEvent EventName:NodeIKernelMsgService/sendMsg ListenerName:NodeIKernelMsgListener/onMsgInfoListUpdate EventRet:                       {                                                        "result": 0,                                         "errMsg": ""                                     }                                                                                                             at Timeout.databack [as _onTimeout] (file:///opt/QQ/resources/app/app_launcher/napcat/napcat.mjs:1119:18)                                                      at listOnTimeout (node:internal/timers:573:17)       at process.processTimers (node:internal/timers:514:7)
```

### OneBot 客户端运行日志

```shell
-
```

**Comment by RainyHallways** [comment]
网络不好，提交重复了（
