### ISSUE TITLE
[BUG] 无法获取到手机QQNT发送的图片

### ISSUE THREAD

**Issue by BlackcatWatcher** [NapNeko/NapCatQQ#265]
### 系统版本

Win 10

### QQNT 版本

9.9.15-26909

### NapCat 版本

V2.0.25

### OneBot 客户端

自制

### 发生了什么?

无法获取到手机QQ发送的图片，电脑QQ发送的可以正常获取。
1、用V2.0.25利用get_image获取图片或ocr_image时，情况见运行日志。
2、用V1.6.3利用get_image获取图片时，获取图片超时。

### 如何复现

1、使用最新版手机QQNT，发送图片。
2、使用get_image获取图片。

### 期望的结果?

正常获取图片。
（另外V1.6.3已经失效了，运行后收到消息直接崩溃）

### NapCat 运行日志

```shell
2024-08-16 00:37:30 [INFO] 机器人() | 接收 <- 群聊 (群 的 ) 分析 [图片 27DE4EA7A8E250029F25016E9CA01238.jpg]
2024-08-16 00:37:30 [ERROR] 机器人() | 发生错误 OCR 27DE4EA7A8E250029F25016E9CA01238.jpg失败,image字段可能格式不正确
2024-08-16 00:37:30 [ERROR] 机器人() | 发生错误 Error: file not found
    at GetImage._handle (file:///C:/QQNT/NapCat/napcat.mjs:28635:11)
    at async GetImage.websocketHandle (file:///C:/QQNT/NapCat/napcat.mjs:23293:23)
    at async OB11ActiveWebSocketAdapter.handleMessage (file:///C:/QQNT/NapCat/napcat.mjs:23970:23)
【使用get_image?file=27DE4EA7A8E250029F25016E9CA01238.jpg】
2024-08-16 00:38:13 [ERROR] 机器人() | 发生错误 Error: file not found
    at GetImage._handle (file:///C:/QQNT/NapCat/napcat.mjs:28635:11)
    at async GetImage.handle (file:///C:/QQNT/NapCat/napcat.mjs:23280:23)
    at async OB11PassiveHttpAdapter.handleRequest (file:///C:/QQNT/NapCat/napcat.mjs:24071:24)
```

**Comment by MliKiowa** [comment]
好的 上报有链接 为什么不用链接呢

**Comment by BlackcatWatcher** [comment]
> 好的 上报有链接 为什么不用链接呢

QQNT上报的链接都是加密的，贴到浏览器里是获取不了的。非NT的客户端或者非NT的发送端得到的链接才能获取到图片。

**Comment by MliKiowa** [comment]
有链接上报的 可以打开

**Comment by BlackcatWatcher** [comment]
> 有链接上报的 可以打开
获取到的链接：https://multimedia.nt.qq.com.cn/download?appid=1407&amp;fileid=***;spec=0&amp;rkey=***
贴到浏览器打开出现：{"retcode":-5503010,"retmsg":"invalid rkey","retryflag":1}

**Comment by MliKiowa** [comment]
> > 有链接上报的 可以打开
> > 获取到的链接：https://multimedia.nt.qq.com.cn/download?appid=1407&amp;fileid=***;spec=0&amp;rkey=***
> > 贴到浏览器打开出现：{"retcode":-5503010,"retmsg":"invalid rkey","retryflag":1}

需要反转义啊

**Comment by MliKiowa** [comment]
你用cq需要处理 消息段解json就好了

**Comment by BlackcatWatcher** [comment]
> 你用cq需要处理 消息段解json就好了

大意了，成功了
