### ISSUE TITLE
[BUG] 升级到 v2 后无法发送视频

### ISSUE THREAD

**Issue by qianxuu** [NapNeko/NapCatQQ#275]
### 系统版本

Docker

### QQNT 版本

Docker latest v2.0.31

### NapCat 版本

Docker latest v2.0.31

### OneBot 客户端

nonebot-adapter-onebot v2.4.4

### 发生了什么?

容器更新到 latest v2.x 后发送视频失败，原 latest v1.x 正常，降级回 v1.8.6 正常

### 如何复现

传入 bytes 数据类型发送视频

### 期望的结果?

视频发送成功

### NapCat 运行日志

```shell
2024-08-18 19:35:17 [ERROR] bot(123456) | 发生错误 Error: Timeout: NTEvent EventName:NodeIKernelMsgService/sendMsg ListenerName:NodeIKernelMsgListener/onMsgInfoListUpdate EventRet:
{
    "result": -1,
    "errMsg": "rich media transfer failed"
}
    at Timeout.databack [as _onTimeout] (file:///usr/src/app/napcat/napcat.mjs:1119:18)
    at listOnTimeout (node:internal/timers:573:17)
    at process.processTimers (node:internal/timers:514:7) 
```

### OneBot 客户端运行日志

```shell
08-18 19:35:17 [ERROR] plugin | 视频发送失败: ActionFailed(status='failed', retcode=1200, data=None, message='Error: Timeout: NTEvent EventName:NodeIKernelMsgService/sendMsg ListenerName:NodeIKernelMsgListener/onMsgInfoListUpdate EventRet:\n{\n    "result": -1,\n    "errMsg": "rich media transfer failed"\n}\n\n    at Timeout.databack [as _onTimeout] (file:///usr/src/app/napcat/napcat.mjs:1119:18)\n    at listOnTimeout (node:internal/timers:573:17)\n    at process.processTimers (node:internal/timers:514:7)', wording='Error: Timeout: NTEvent EventName:NodeIKernelMsgService/sendMsg ListenerName:NodeIKernelMsgListener/onMsgInfoListUpdate EventRet:\n{\n    "result": -1,\n    "errMsg": "rich media transfer failed"\n}\n\n    at Timeout.databack [as _onTimeout] (file:///usr/src/app/napcat/napcat.mjs:1119:18)\n    at listOnTimeout (node:internal/timers:573:17)\n    at process.processTimers (node:internal/timers:514:7)', echo='15389')
```

**Comment by MliKiowa** [comment]
原始post数据示例

**Comment by qianxuu** [comment]
> 原始post数据示例

```
2024-08-18 23:14:07 [DEBUG] bot(123456) | [OneBot] [WebSocket Client] 收到正向Websocket消息 {"action":"send_msg","params":{"user_id":123456,"message_type":"private","message":[{"type":"video","data":{"file":"base64://AAAAIGZ0eXBpc29tAAACAGlzb21pc28yYXZjMW1wNDEAAlOBbW9vdgAAAGxtdmhkAAAAAAAAAAAAAAAAAAAD6AAB2WEAAQAAAQAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAwABMSl0cmFrAAAAXHRraGQAAAADAAAAAAAAAAAAAAABAAAAAAAB2QsAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAABAAAAABQAAAALQAAAAAAAwZWR0cwAAAChlbHN0AAAAAAAAAAIAAAAX/////wABAAAAAdkLAAAIUAABAAAAATCVbWRpYQAAACBtZGhkAAAAAAAAAAAAAAAAAAA+gAAdkLBVxAAAAAAALWhkbHIAAAAAAAAAAHZpZGUAAAAAAAAAAAAAAAB...","cache":null,"proxy":null,"timeout":null}}]},"echo":"15493"} 
```

**Comment by cnxysoft** [comment]
此问题将在下一版本修复。
