### ISSUE TITLE
[BUG] 成功发送了图片但仍然报错

### ISSUE THREAD

**Issue by forchannot** [NapNeko/NapCatQQ#28]
### 系统版本

win server 2022

### QQNT 版本

QQ9.9.9.23361_x64

### NapCat 版本

1.3.5

### OneBot 客户端

nonebot-adapter-onebot-v11

### 发生了什么?

bot发送了某条带图片的消息，发送成功了，但是控制台报错

### 如何复现

发送图片（应该？）

### 期望的结果?

不报错

### NapCat 运行日志

```shell
2024-05-19 16:48:49 [DEBUG] 波奇呀波奇(xxxxxx) 
收到反向Websocket消息 {"action":"send_msg","params":{"user_id":xxxxxx,"group_id":xxxxxx,"message_type":"group","message":[{"type":"at","data":{"qq":"xxxxxx"}},{"type":"text","data":{"text":" "}},{"type":"image","data":{"file":"base64:///9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAYEBQYFBAYGBQYHBwYIChAKCgkJChQODwwQFxQYGBcUFhYaHSUfGhsjHBYWICwgIyYnKSopGR8tMC0oMCUoKSj/2wBDAQcHBwoIChMKChMoGhYaKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCj/wAARCAeoBDgDASIAAhEBAxEB/8QAHwAAAQUBAQEBAQEAAAAAAAAAAAECAwQFBgcICQoL/8QAtRAAAgEDAwIEAwUFBAQAAAF9AQIDAAQRBRIhMUEGE1FhByJxFDKBkaEII0KxwRVS0fAkM2JyggkKFhcYGRolJicoKSo0NTY3ODk6Q0RFRkdISUpTVFVWV1hZWmNkZWZnaGlqc3R1dnd4eXqDhIWGh4iJipKTlJWWl5iZmqKjpKWmp6ipqrKztLW2t7i5usLDxMXGx8jJytLT1NX...","type":null,"cache":"true","proxy":"true","timeout":null}}]},"echo":"256"} 

2024-05-19 16:48:49 [INFO] 波奇呀波奇(2029172546) 
获取文件类型 jpg C:\Users\Administrator\Documents\Tencent Files\NapCat\temp\7276624a-b960-4732-8002-18bde9e51ae0 

2024-05-19 16:48:49 [DEBUG] 波奇呀波奇(xxxxxx) 
图片信息 {"md5HexStr":"b2d9feae5179bf12238742373377a50f","fileSize":"436644","picWidth":1080,"picHeight":1960,"fileName":"7276624a-b960-4732-8002-18bde9e51ae0.jpg","sourcePath":"C:\\Users\\Administrator\\Documents\\Tencent Files\\xxxxxx\\nt_qq\\nt_data\\Pic\\2024-05\\Ori\\b2d9feae5179bf12238742373377a50f.jpg","original":true,"picType":1000,"picSubType":0,"fileUuid":"","fileSubId":"","thumbFileSize":0,"summary":""} 

2024-05-19 16:48:49 [INFO] 波奇呀波奇(xxxxxx) 
发送消息 给群聊 群[fanco(xxxxxx)] : @😘(xxxxxxx) 
[图片]https://gchat.qpic.cn/gchatpic_new/0/0-0-B2D9FEAE5179BF12238742373377A50F/0
 

2024-05-19 16:48:49 [DEBUG] 波奇呀波奇(xxxxxx) 
记录消息到数据库, 消息长id: 7444847292992317995, 短id: -2147453865 

2024-05-19 16:48:49 [DEBUG] 波奇呀波奇(xxxxxx) 
更新消息, shortId:undefined, seq: 22354, msgId: 7444847292992317995 

2024-05-19 16:48:49 [ERROR] 波奇呀波奇(xxxxxx) 
发生错误 {"errno":-4058,"syscall":"unlink","code":"ENOENT","path":"C:\\Users\\Administrator\\Documents\\Tencent Files\\NapCat\\temp\\7276624a-b960-4732-8002-18bde9e51ae0.jpg"} 

2024-05-19 16:48:49 [DEBUG] 波奇呀波奇(xxxxxx) 
ws 消息上报 ws://127.0.0.1:15600/onebot/v11/ws {"status":"failed","retcode":1200,"data":null,"message":"Error: ENOENT: no such file or directory, unlink 'C:\\Users\\Administrator\\Documents\\Tencent Files\\NapCat\\temp\\7276624a-b960-4732-8002-18bde9e51ae0.jpg'\n    at Object.unlinkSync (node:fs:1883:3)\n    at C:\\Users\\Administrator\\Desktop\\NapCat\\napcat.cjs:21726:16932\n    at Array.forEach (<anonymous>)\n    at SendMsg._handle (C:\\Users\\Administrator\\Desktop\\NapCat\\napcat.cjs:21726:16898)\n    at async SendMsg.websocketHandle (C:\\Users\\Administrator\\Desktop\\NapCat\\napcat.cjs:21718:8212)\n    at async Revers...","wording":"Error: ENOENT: no such file or directory, unlink 'C:\\Users\\Administrator\\Documents\\Tencent Files\\NapCat\\temp\\7276624a-b960-4732-8002-18bde9e51ae0.jpg'\n    at Object.unlinkSync (node:fs:1883:3)\n    at C:\\Users\\Administrator\\Desktop\\NapCat\\napcat.cjs:21726:16932\n    at Array.forEach (<anonymous>)\n    at SendMsg._handle (C:\\Users\\Administrator\\Desktop\\NapCat\\napcat.cjs:21726:16898)\n    at async SendMsg.websocketHandle (C:\\Users\\Administrator\\Desktop\\NapCat\\napcat.cjs:21718:8212)\n    at async Revers...","echo":"256"}
```

### OneBot 客户端运行日志

```shell
05-19 16:48:50 [ERROR] nonebot | Running Matcher(type='message', module=LittlePaimon.plugins.star_rail_info, lineno=28) failed.
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\LittlePaimon\bot.py", line 42, in <module>
    nonebot.run(app="__mp_main__:app", access_log=False)
  File "C:\Users\Administrator\Desktop\LittlePaimon\.venv\Lib\site-packages\nonebot\__init__.py", line 335, in run
    get_driver().run(*args, **kwargs)
  File "C:\Users\Administrator\Desktop\LittlePaimon\.venv\Lib\site-packages\nonebot\drivers\fastapi.py", line 186, in run
    uvicorn.run(
  File "C:\Users\Administrator\Desktop\LittlePaimon\.venv\Lib\site-packages\uvicorn\main.py", line 575, in run
    server.run()
  File "C:\Users\Administrator\Desktop\LittlePaimon\.venv\Lib\site-packages\uvicorn\server.py", line 65, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\asyncio\runners.py", line 190, in run
    return runner.run(main)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 640, in run_until_complete
    self.run_forever()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 607, in run_forever
    self._run_once()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 1922, in _run_once
    handle._run()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\Administrator\Desktop\LittlePaimon\.venv\Lib\site-packages\nonebot\message.py", line 476, in check_and_run_matcher
    await _run_matcher(
> File "C:\Users\Administrator\Desktop\LittlePaimon\.venv\Lib\site-packages\nonebot\message.py", line 428, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "C:\Users\Administrator\Desktop\LittlePaimon\.venv\Lib\site-packages\nonebot\internal\matcher\matcher.py", line 850, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "C:\Users\Administrator\Desktop\LittlePaimon\.venv\Lib\site-packages\nonebot\internal\matcher\matcher.py", line 825, in simple_run
    await handler(
  File "C:\Users\Administrator\Desktop\LittlePaimon\.venv\Lib\site-packages\nonebot\dependencies\__init__.py", line 94, in __call__
    return await cast(Callable[..., Awaitable[R]], self.call)(**values)
  File "C:\Users\Administrator\Desktop\LittlePaimon\LittlePaimon\plugins\star_rail_info\__init__.py", line 94, in panel_cmd_handler
    await panel_cmd.finish(
  File "C:\Users\Administrator\Desktop\LittlePaimon\.venv\Lib\site-packages\nonebot\internal\matcher\matcher.py", line 582, in finish
    await cls.send(message, **kwargs)
  File "C:\Users\Administrator\Desktop\LittlePaimon\.venv\Lib\site-packages\nonebot\internal\matcher\matcher.py", line 566, in send
    return await bot.send(event=event, message=_message, **kwargs)
  File "C:\Users\Administrator\Desktop\LittlePaimon\.venv\Lib\site-packages\nonebot\adapters\onebot\v11\bot.py", line 228, in send
    return await self.__class__.send_handler(self, event, message, **kwargs)
  File "C:\Users\Administrator\Desktop\LittlePaimon\.venv\Lib\site-packages\nonebot\adapters\onebot\v11\bot.py", line 181, in send
    return await bot.send_msg(**params)
  File "C:\Users\Administrator\Desktop\LittlePaimon\.venv\Lib\site-packages\nonebot\internal\adapter\bot.py", line 122, in call_api
    raise exception
  File "C:\Users\Administrator\Desktop\LittlePaimon\.venv\Lib\site-packages\nonebot\internal\adapter\bot.py", line 97, in call_api
    result = await self.adapter._call_api(self, api, **data)
  File "C:\Users\Administrator\Desktop\LittlePaimon\.venv\Lib\site-packages\nonebot\adapters\onebot\v11\adapter.py", line 147, in _call_api
    return handle_api_result(await self._result_store.fetch(seq, timeout))
  File "C:\Users\Administrator\Desktop\LittlePaimon\.venv\Lib\site-packages\nonebot\adapters\onebot\v11\utils.py", line 58, in handle_api_result
    raise ActionFailed(**result)
nonebot.adapters.onebot.v11.exception.ActionFailed: ActionFailed(status='failed', retcode=1200, data=None, message="Error: ENOENT: no such file or directory, unlink 'C:\\Users\\Administrator\\Documents\\Tencent Files\\NapCat\\temp\\7276624a-b960-4732-8002-18bde9e51ae0.jpg'\n    at Object.unlinkSync (node:fs:1883:3)\n    at C:\\Users\\Administrator\\Desktop\\NapCat\\napcat.cjs:21726:16932\n    at Array.forEach (<anonymous>)\n    at SendMsg._handle (C:\\Users\\Administrator\\Desktop\\NapCat\\napcat.cjs:21726:16898)\n    at async SendMsg.websocketHandle (C:\\Users\\Administrator\\Desktop\\NapCat\\napcat.cjs:21718:8212)\n    at async ReverseWebsocket.onmessage (C:\\Users\\Administrator\\Desktop\\NapCat\\napcat.cjs:22353:6179)\n    at async WebSocket.<anonymous> (C:\\Users\\Administrator\\Desktop\\NapCat\\napcat.cjs:22353:9567)", wording="Error: ENOENT: no such file or directory, unlink 'C:\\Users\\Administrator\\Documents\\Tencent Files\\NapCat\\temp\\7276624a-b960-4732-8002-18bde9e51ae0.jpg'\n    at Object.unlinkSync (node:fs:1883:3)\n    at C:\\Users\\Administrator\\Desktop\\NapCat\\napcat.cjs:21726:16932\n    at Array.forEach (<anonymous>)\n    at SendMsg._handle (C:\\Users\\Administrator\\Desktop\\NapCat\\napcat.cjs:21726:16898)\n    at async SendMsg.websocketHandle (C:\\Users\\Administrator\\Desktop\\NapCat\\napcat.cjs:21718:8212)\n    at async ReverseWebsocket.onmessage (C:\\Users\\Administrator\\Desktop\\NapCat\\napcat.cjs:22353:6179)\n    at async WebSocket.<anonymous> (C:\\Users\\Administrator\\Desktop\\NapCat\\napcat.cjs:22353:9567)", echo='256')
```

**Comment by MliKiowa** [comment]
图片清理问题

**Comment by forchannot** [comment]
怎么解决呢

**Comment by MliKiowa** [comment]
https://github.com/NapNeko/NapCatQQ/actions/runs/9147748794 这个版本试试

**Comment by forchannot** [comment]
测试了之前报错的几个命令，目前看下来可以了
