### ISSUE TITLE
[BUG] 2.0.34nc通过反向ws链接get_file获取群文件失败

### ISSUE THREAD

**Issue by zyna** [NapNeko/NapCatQQ#283]
### 系统版本

win11

### QQNT 版本

9.9.15-26909

### NapCat 版本

2.0.34

### OneBot 客户端

自开发

### 发生了什么?

通过get_file提示file not found

### 如何复现

通过get_file获取群文件

### 期望的结果?

得到文件base64

### NapCat 运行日志

```shell
{"echo":"507488883135479809","message":"Error: file not found\n    at GetFile._handle (file:///D:/ncqq/LiteLoaderQQNT/plugins/NapCat/napcat.mjs:25628:11)\n    at async GetFile.websocketHandle (file:///D:/ncqq/LiteLoaderQQNT/plugins/NapCat/napcat.mjs:20286:23)\n    at async OB11ActiveWebSocketAdapter.handleMessage (file:///D:/ncqq/LiteLoaderQQNT/plugins/NapCat/napcat.mjs:20963:23)","wording":"Error: file not found\n    at GetFile._handle (file:///D:/ncqq/LiteLoaderQQNT/plugins/NapCat/napcat.mjs:25628:11)\n    at async GetFile.websocketHandle (file:///D:/ncqq/LiteLoaderQQNT/plugins/NapCat/napcat.mjs:20286:23)\n    at async OB11ActiveWebSocketAdapter.handleMessage (file:///D:/ncqq/LiteLoaderQQNT/plugins/NapCat/napcat.mjs:20963:23)","status":"failed","retcode":1200}
```

### OneBot 客户端运行日志

```shell
无
```

**Comment by MliKiowa** [comment]
最近几个版本修复

**Comment by MliKiowa** [comment]
已修
