### ISSUE TITLE
[BUG] 返回下载文件错误

### ISSUE THREAD

**Issue by Ray-lea** [NapNeko/NapCatQQ#290]
### 系统版本

Windows Server 2022 Datacenter 21H2

### QQNT 版本

9.9.15-27254

### NapCat 版本

2.1.0

### OneBot 客户端

TRSS-Yunzai-dd6cb0d263c4d3f2388408d898f182c459756ef7

### 发生了什么?

无法正常下载文件

### 如何复现

1.使用插件[https://github.com/snowtafir/yuki-plugin](url)
2.使用“`#yuki帮助`”

### 期望的结果?

正常返回图片内容

### NapCat 运行日志

```shell
2024-08-21 09:23:13 [INFO] 洛箐箐(XXX) | 接收 <- 群聊 (群 XXX 的 XXX) #yuki帮助 
2024-08-21 09:23:13 [DEBUG] 洛箐箐(XXX) | 收到新消息 RawMessage {"msgId":"7405397186152549531","msgRandom":"1209131861","msgSeq":"607240","cntSeq":"0","chatType":2,"msgType":2,"subMsgType":1,"sendType":0,"senderUid":"u_6GiTlp1z_h62IJI9l9ngaA","peerUid":"XXX","channelId":"","guildId":"","guildCode":"0","fromUid":"0","fromAppid":"0","msgTime":"1724203393","msgMeta":{},"sendStatus":2,"sendRemarkName":"","sendMemberName":"叱咤月海鱼鱼猫","sendNickName":"","guildName":"","channelName":"","elements":[{"elementType":1,"elementId":"7405397186152549530","elementGroupId":0,"extBufForUI":{},"textElement":{"content":"#yuki帮助","atType":0,"atUid":"0","atTinyId":"0","atNtUid":"","subElementType":0,"atChannelId":"0","linkInfo":null,"atRoleId":"0","atRoleColor":0,"atRoleName":"","needNotify":0},"faceElement":null,"marketFaceElement":null,"replyElement":null,"picElement":null,"pttElement":null,"videoElement":null,"grayTipElement":null,"arkElement":null,"fileElement":null,"liveGiftElement":null,"markdownElement":null,"structLongMsgElement":null,"multiForwardMsgElement":null,"giphyElement":null,"walletElement":null,"inlineKeyboardElement":null,"textGiftElement":null,"calendarElement":null,"yoloGameResultElement":null,"avRecordElement":null,"structMsgElement":null,"faceBubbleElement":null,"shareLocationElement":null,"tofuRecordElement":null,"taskTopMsgElement":null,"recommendedMsgElement":null,"actionBarElement":null,"prologueMsgElement":null}],"records":[],"emojiLikesList":[],"commentCnt":"0","directMsgFlag":0,"directMsgMembers":[],"peerName":"『放逐之城贴吧官方群","freqLimitInfo":null,"editable":false,"avatarMeta":"","avatarPendant":"","feedId":"","roleId":"0","timeStamp":"0","clientIdentityInfo":null,"isImportMsg":false,"atType":0,"roleType":0,"fromChannelRoleInfo":{"roleId":"0","name":"","color":0},"fromGuildRoleInfo":{"roleId":"0","name":"","color":0},"levelRoleInfo":{"roleId":"0","name":"","color":0},"recallTime":"0","isOnlineMsg":true,"generalFlags":{},"clientSeq":"0","fileGroupSize":null,"foldingInfo":null,"multiTransInfo":null,"senderUin":"XXX","peerUin":"XXX","msgAttrs":{},"anonymousExtInfo":null,"nameType":0,"avatarFlag":0,"extInfoForUI":null,"personalMedal":null,"categoryManage":0,"msgEventInfo":null,"sourceType":1,"id":1243724403} 
2024-08-21 09:23:13 [DEBUG] 洛箐箐(XXX) | 转化为 OB11Message {"self_id":XXX,"user_id":XXX,"time":1724203393,"message_id":1243724403,"message_seq":1243724403,"real_id":1243724403,"message_type":"group","sender":{"user_id":XXX,"nickname":"柑橘味青柠","card":"叱咤月海鱼鱼猫","role":"owner"},"raw_message":"#yuki帮助","font":14,"sub_type":"normal","message":[{"data":{"text":"#yuki帮助"},"type":"text"}],"message_format":"array","post_type":"message","group_id":XXX} 
2024-08-21 09:23:13 [DEBUG] 洛箐箐(XXX) | ProfileListener has no method onMemberInfoChange 
2024-08-21 09:23:13 [DEBUG] 洛箐箐(XXX) | ProfileListener has no method onMemberListChange 
2024-08-21 09:23:14 [DEBUG] 洛箐箐(XXX) | ProfileListener has no method onMemberInfoChange 
2024-08-21 09:23:20 [DEBUG] 洛箐箐(XXX) | ProfileListener has no method onGroupListUpdate 
2024-08-21 09:23:21 [DEBUG] 洛箐箐(XXX) | ProfileListener has no method onMemberInfoChange 
2024-08-21 09:23:21 [DEBUG] 洛箐箐(XXX) | ProfileListener has no method onMemberListChange 
2024-08-21 09:23:21 [DEBUG] 洛箐箐(XXX) | ProfileListener has no method onMemberInfoChange 
2024-08-21 09:23:22 [DEBUG] 洛箐箐(XXX) | [OneBot] [WebSocket Client] 收到正向Websocket消息 {"action":"send_msg","params":{"group_id":XXX,"message":[{"type":"image","data":{"file":"{\"0\":137,\"1\":80,\"2\":78,\"3\":71,\"4\":13,\"5\":10,\"6\":26,\"7\":10,\"8\":0,\"9\":0,\"10\":0,\"11\":13,\"12\":73,\"13\":72,\"14\":68,\"15\":82,\"16\":0,\"17\":0,\"18\":4,\"19\":158,\"20\":0,\"21\":0,\"22\":6,\"23\":156,\"24\":8,\"25\":2,\"26\":0,\"27\":0,\"28\":0,\"29\":210,\"30\":38,\"31\":195,\"32\":159,\"33\":0,\"34\":0,\"35\":0,\"36\":1,\"37\":115,\"38\":82,\"39\":71,\"40\":66,\"41\":0,\"42\":174,\"43\":206,\"44\":28,\"45\":233,\"46\":0,\"47\":0,\"48\":32,\"49\":0,\"50\":73,\"51\":68,\"52\":65,\"53\":84,\"54\":120,\"55\":156,\"56\":236,\"57\":221,\"58\":217,\"59\":111,\"60\":29,\"61\":105,\"62\":154,\"63\":231,..."}}]},"echo":"01J5S8FZR1SQGD16Z4GCHNS0EE"} 
2024-08-21 09:23:22 [ERROR] 洛箐箐(XXX) | 文件下载失败 未知文件类型 
2024-08-21 09:23:22 [ERROR] 洛箐箐(XXX) | 发生错误 Error: 文件下载失败未知文件类型
    at handleOb11FileLikeMessage (file:///C:/Users/Administrator/Desktop/NapCat.win32.x64/napcat.mjs:15898:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Object.image (file:///C:/Users/Administrator/Desktop/NapCat.win32.x64/napcat.mjs:15954:70)
    at async Promise.all (index 0)
    at async createSendElements (file:///C:/Users/Administrator/Desktop/NapCat.win32.x64/napcat.mjs:16078:15)
    at async SendMsg._handle (file:///C:/Users/Administrator/Desktop/NapCat.win32.x64/napcat.mjs:23576:9)
    at async SendMsg.websocketHandle (file:///C:/Users/Administrator/Desktop/NapCat.win32.x64/napcat.mjs:23298:23)
    at async OB11ActiveWebSocketAdapter.handleMessage (file:///C:/Users/Administrator/Desktop/NapCat.win32.x64/napcat.mjs:23985:23)
```

### OneBot 客户端运行日志

```shell
[09:23:13.938][INFO][XXX, 叱咤月海鱼鱼猫(X)][#yuki帮助][yuki-help(yukiHelp)][开始处理]
[09:23:17.234][INFO][TRSSYz] [puppeteer] success
[09:23:18.931][MARK][TRSSYz] [图片生成][yukiHelp][1次] 1190.12kb 1697ms
[09:23:20.959][INFO][X=> X] 发送群消息：[{"type":"image","data":{"file":"{\"0\":137,\"1\":80,\"2\":78,\"3\":71,\"4\":13,\"5\":1
0,\"6\":26,\"7\":10,\"8\":0,\"9\":0,\"10\":0,\"11\":13,\"12\":73,\"13\":72,\"14\":68,\"15\":82,\"16\":0,\"17\":0,\"18\":4,\"19\":158,\"20\":0,\"2
1\":0,\"22\":6,\"23\":156,\"24\":8,\"25\":2,\"26\":0,\"27\":0,\"28\":0,\"29\":210,\"30\":38,\"31\":195,\"32\":159,\"33\":0,\"34\":0,\"35\":0,\"36
\":1,\"37\":115,\"38\":82,\"39\":71,\"40\":66,\"41\":0,\"42\":174,\"43\":206,\"44\":28,\"45\":233,\"46\":0,\"47\":0,\"48\":32,\"49\":0,\"50\":73,
\"51\":68,\"52\":65,\"53\":84,\"54\":120,\"55\":156,\"56\":236,\"57\":221,\"58\":217,\"59\":111,\"60\":29,\"61\":105,\"62\":154,\"63\":231,\"64\"
:247,\"65\":239,\"66\":27,\"67\":17,\"68\":103,\"69\":223,\"70\":184,\"71\":175,\"72\":162,\"73\":246,\"74\":84,\"75\":238,\"76\":107,\"77\":87,\
"78\":117,\"79\":85,\"80\":102,\"81\":117,\"82\":117,\"83\":247,\"84\":216,\"85\":51,\"86\":13,\"87\":12,\"88\":230,\"89\":114,\"90\":110,\"91\":
124,\"92\":105,\"93\":255,\"94\":19,\"95\":254,\"96\":7,\"97\":108,\"98\":192,\"99\":128,\"100\":97,\"101\":248,\"102\":118,\"103\":46,\"104\":23
6,\"105\":43,\"106\":251,\"107\":102,\"108\":224,\"109\":1,\"110\":198,\"111\":192,\"112\":192,\"113\":221,\"114\":70,\"115\":143,\"116\":209,\"1
17\":61,\"118\":168,\"119\":174,\"120\":173,\"121\":171,\"122\":50,\"123\":179,\"124\":178,\"125\":178,\"126\":114,\"127\":215,\"128\":150,\"129\
":162,\"130\":36,\"131\":238,\"132\":60,\"133\":228,\"134\":217,\"135\":215,\"136\":136,\"137\":120,\"138\":125,\"139\":17,\"140\":113,\"141\":18
4,\"142\":233,\"143\":144,\"144\":34,\"145\":69,\"146\":74,\"147\":41,\"148\":74,\"149\":191,\"150\":79,\"151\":103,\"152\":170,\"153\":40,\"154\
":242,\"155\":48,\"156\":34,\"157\":14,\"158\":149,\"159\":23,\"160\":250,\"161\":245,\"162\":243,\"163\":188,\"164\":207,\"165\":99,\"166\":172,
\"167\":181,\"168\":136,\"169\":136,\"170\":136,\"171\":136,\"172\":136,\"173\":136,\"174\":200,\"175\":121,\"176\":230,\"177\":252,\"178\":208,\
"179\":15,\"180\":32,\"181\":34,\"182\":34,\"183\":34,\"184\":34,\"185\":34,\"186\":34,\"187\":167,\"188\":165,\"189\":104,\"190\":39,\"191\":34,
\"192\":34,\"193\":34,\"194\":34,\"195\":34,\"196\":114,\"197\":238,\"198\":41,\"199\":218,\"200\":137,\"201\":136,\"202\":136,\"203\":136,\"204\
":136,\"205\":136,\"206\":156,\"207\":123,\"208\":138,\"209\":118,\"210\":34,\"211\":34,\"212\":34,\"213\":34,\"214\":34,\"215\":34,\"216\":231,\
"217\":158,\"218\":162,\"219\":157,\"220\":136,\"221\":136,\"222\":136,\"223\":136,\"224\":136,\"225\":200,\"226\":185,\"227\":167,\"228\":104,\"
229\":39,\"230\":34,\"231\":34,\"232\":34,\"233\":34,\"234\":34,\"235\":114,\"236\":238,\"237\":41,\"238\":218,\"239\":137,\"240\":136,\"241\":13
6,\"242\":136,\"243\":136,\"244\":136,\"245\":156,\"246\":123,\"247\":138,\"248\":118,\"249\":34,\"250\":34,\"251\":34,\"252\":34,\"253\":34,\"25
4\":34,\"255\":231,\"256\":158,\"257\":162,\"258\":157,\"259\":136,\"260\":136,\"261\":136,\"262\":136,\"263\":136,\"264\":200,\"265\":185,\"266\
":167,\"267\":104,\"268\":39,\"269\":34,\"270\":34,\"271\":34,\"272\":34,\"273\":34,\"274\":114,\"275\":238,\"276\":41,\"277\":218,\"278\":137,\"
279\":136,\"280\":136,\"281\":136,\"282\":136,\"283\":136,\"284\":156,\"285\":123,\"286\":138,\"287\":118,\"288\":34,\"289\":34,\"290\":34,\"291\
":34,\"292\":34,\"293\":34,\"294\":231,\"295\":158,\"296\":162,\"297\":157,\"298\":136,\"299\":136,\"300\":136,\"301\":136,\"302\":136,\"303\":20
0,\"304\":185,\"305\":167,\"306\":104,\"307\":39,\"308\":34,\"309\":34,\"310\":34,\"311\":34,\"312\":34,\"313\":114,\"314\":238,\"315\":41,\"316\
":218,\"317\":137,\"318\":136,\"319\":136,\"320\":136,\"321\":136,\"322\":136,\"323\":156,\"324\":123,\"325\":138,\"326\":118,\"327\":34,\"328\":
34,\"329\":34,\"330\":34,\"331\":34,\"332\":34,\"333\":231,\"334\":158,\"335\":162,\"336\":157,\"337\":136,\"338\":136,\"339\":136,\"340\":136,\"
341\":136,\"342\":200,\"343\":185,\"344\":231,\"345\":61,\"346\":187,\"347\":91,\"348\":89,\"349\":0,\"350\":12,\"351\":214,\"352\":70,\"353\":31
,\"354\":97,\"355\":48,\"356\":207,\"357\":238,\"358\":238,\"359\":34,\"360\":34,\"361\":34,\"362\":34,\"363\":34,\"364\":34,\"365\":207,\"366\":
156,\"367\":101,\"368\":16,\"369\":127,\"370\":140,\"371\":217,\"372\":201,\"373\":68,\"374\":79,\"375\":195,\"376\":83,\"377\":142,\"378\":118,\
"379\":54,\"380\":206,\"381\":114,\"382\":59,\"383\":41,\"384\":206,\"385\":134,\"386\":22,\"387\":51,\"388\":136,\"389\":121,\"390\":34,\"391\":
34,\"392\":34,\"393\":34,\"394\":34,\"395\":34,\"396\":47,\"397\":3,\"398\":131,\"399\":13,\"400\":173,\"401\":49,\"402\":134,\"403\":56,\"404\":
237,\"405\":217,\"406\":56,\"407\":233,\"408\":157,\"409\":93,\"410\":204,\"411\":51,\"412\":59,\"413\":53,\"414\":180,\"415\":51,\"416\":22,\"41
7\":61,\"418\":165,\"419\":5,\"420\":176,\"421\":214,\"422\":98,\"423\":49,\"424\":123,\"425\":239,\"426\":181,\"427\":243,\"428\":30,\"429\":148
,\"430\":241,\"431\":68,\"432\":68,\"433\":68,\"434\":68,\"435\":68,\"436\":228,\"437\":69,\"438\":101,\"439\":14,\"440\":254,\"441\":54,\"442\":
78,\"443\":119,\"444\":59,\"445\":95,\"446\":50,\"447\":156,\"448\":85,\"449\":192,\"450\":123,\"451\":10,\"452\":85,\"453\":187,\"454\":193,\"45
5\":147,\"456\":89,\"457\":107,\"458\":9,\"459\":177,\"460\":214,\"461\":134,\"462\":97,\"463\":136,\"464\":197,\"465\":90,\"466\":107,\"467\":19
5,\"468\":232,\"469\":127,\"470\":118,\"471\":95,\"472\":102,\"473\":158,\"474\":94,\"475\":182,\"476\":20,\"477\":17,\"478\":17,\"479\":17,\"480
\":17,\"481\":17,\"482\":249,\"483\":129,\"484\":24,\"485\":99,\"486\":118,\"487\":130,\"488\":156,\"489\":193,\"490\":24,\"491\":199,\"492\":24,
\"493\":12,\"494\":78,\"495\":156,\"496\":238,\"497\":162,\"498\":218,\"499\":87,\"500\":20,\"501\":136,\"502\":226,\"503\":111,\"504\":56,\"505\
":117,\"506\":192,\"507\":59,\"508\":235,\"509\":100,\"510\":181,\"511\":83,\"512\":150,\"513\":179,\"514\":54,\"515\":12,\"516\":194,\"517\":160
,\"518\":231,\"519\":83,\"520\":235,\"521\":82,\"522\":110,\"523\":153,\"524\":74,\"525\":135,\"526\":150,\"527\":79,\"528\":199,\"529\":183,\"53
0\":126,\"531\":64,\"532\":24,\"533\":63,\"534\":184,\"535\":234,\"536\":118,\"537\":34,\"538\":34,\"539\":34,\"540\":34,\"541\":34,\"542\":242,\
"543\":66,\"544\":50,\"545\":198,\"546\":144,\"547\":116,\"548\":73,\"549\":186,\"550\":54,\"551\":235,\"552\":81,\"553\":74,\"554\":219,\"555\":
209,\"556\":140,\"557\":201,\"558\":167,\"559\":156,\"560\":164,\"561\":103,\"562\":28,\"563\":99,\"564\":140,\"565\":49,\"566\":142,\"567\":137,
\"568\":162,\"569\":29,\"570\":6,\"571\":227,\"572\":236,\"573\":137,\"574\":116,\"575\":167,\"576\":72,\"577\":119,\"578\":103,\"579\":95,\"580\
":181,\"581\":139,\"582\":170,\"583\":115,\"584\":65,\"585\":175,\"586\":31,\"587\":174,\"588\":55,\"589\":204,\"590\":173,\"591\":109,\"592\":24
3,\"593\":176,\"594\":230,\"595\":108,\"596\":119,\"597\":76,\"598\":63,\"599\":116,\"600\":92,\"601\":135,\"602\":232,\"603\":13,\"604\":104,\"6
05\":122,\"606\":138,\"607\":136,\"608\":136,\"609\":136,\"610\":136,\"611\":136,\"612\":188,\"613\":224,\"614\":44,\"615\":22,\"616\":172,\"617\
":13,\"618\":131,\"619\":48,\"620\":244,\"621\":28,\"622\":59,\"623\":146,\"624\":182,\"625\":115,\"626\":69,\"627\":255,\"628\":202,\"629\":136,
\"630\":153,\"631\":200,\"632\":187,\"633\":73,\"634\":207,\"635\":113,\"636\":29,\"637\":227,\"638\":196,\"639\":69,\"640\":60,\"641\":136,\"642
\":51,\"643\":222,\"644\":41,\"645\":157,\"646\":113,\"647\":213,\"648\":206,\"649\":134,\"650\":54,\"651\":12,\"652\":66,\"653\":191,\"654\":210
,\"655\":226,\"656\":86,\"657\":217,\"658\":249,\"659\":106,\"660\":195,\"661\":219,\"662\":104,\"663\":155,\"664\":92,\"665\":146,\"666\":185,\"
667\":2,\"668\":147,\"669\":57,\"670\":242,\"671\":73,\"672\":210,\"673\":30,\"674\":9,\"675\":87,\"676\":201,\"677\":78,\"678\":68,\"679\":68,\"
680\":68,\"681\":68,\"682\":68,\"683\":94,\"684\":112,\"685\":214,\"686\":210,\"687\":11,\"688\":233,\"689\":250,\"690\":212,\"691\":123,\"692\":
108,\"693\":182,\"694\":88,\"695\":170,\"696\":217,\"697\":102,\"698\":207,\"699\":159,\"700\":204,\"701\":6,\"702\":175,\"703\":78,\"704\":112,\
"705\":101,\"706\":204,\"707\":45,\"708\":102,\"709\":28,\"710\":215,\"711\":49,\"712\":174,\"713\":193,\"714\":193,\"715\":184,\"716\":38,\"717\
":170,\"718\":221,\"719\":89,\"720\":236,\"721\":190,\"722\":10,\"723\":222,\"724\":9,\"725\":157,\"726\":93,\"727\":180,\"728\":179,\"729\":88,\
"730\":107,\"731\":3,\"732\":63,\"733\":8,\"734\":54,\"735\":26,\"736\":230,\"737\":143,\"738\":171,\"739\":238,\"740\":87,\"741\":155,\"742\":11
0,\"743\":58,\"744\":193,\"745\":107,\"746\":19,\"747\":92,\"748\":27,\"749\":101,\"750\":166,\"751\":64,\"752\":46,\"753\":113,\"754\":54,\"755\
":119,\"756\":17,\"757\":17,\"758\":17,\"759\":17,\"760\":17,\"761\":17,\"762\":57,\"763\":95,\"764\":26,\"765\":61,\"766\":86,\"767\":27,\"768\"
:220,\"769\":217,\"770\":230,\"771\":187,\"772\":205,\"773\":160,\"774\":235,\"775\":247,\"776\":111,\"777\":140,\"778\":219,\"779\":215,\"780\":
167,\"781\":220,\"782\":177,\"783\":188,\"784\":155,\"785\":112,\"786\":113,\"787\":49,\"788\":174,\"789\":137,\"790\":50,\"791\":222,\"792\":110
,\"793\":115,\"794\":230,\"795\":19,\"796\":229,\"797\":187,\"798\":179,\"799\":136,\"800\":118,\"801\":131,\"802\":49,\"803\":152,\"804\":129,\"
805\":31,\"806\":132,\"807\":43,\"808\":117,\"809\":243,\"810\":241,\"811\":146,\"812\":119,\"813\":183,\"814\":106,\"815\":230,\"816\":11,\"817\
":252,\"818\":120,\"819\":158,\"820\":139,\"821\":37,\"822\":210,\"823\":207,\"824\":112,\"825\":117,\"826\":158,\"827\":136,\"828\":136,\"829\":
136,\"830\":136,\"831\":136,\"832\":200,\"833\":243,\"834\":169,\"835\":237,\"836\":115,\"837\":191,\"838\":202,\"839\":39,\"840\":203,\"841\":22
5,\"842\":195,\"843\":106,\"844\":255,\"845\":98,\"846\":41,\"847\":124,\"848\":123,\"849\":214,\"850\":157,\"851\":42,\"852\":56,\"853\":9,\"854
\":215,\"855\":120,\"856\":198,\"857\":120,\"858\":187,\"859\":233,\"860\":110,\"861\":119,\"862\":138,\"863\":230,\"864\":9,\"865\":3,\"866\":22
2,\"867\":169,\"868\":115,\"869\":215,\"870\":3... 17852447 more characters
[09:23:22.732][ERRO][X] 发送消息错误 [
  {
    type: 'image',
    file: Uint8Array(1218682) [
                         137,                     80,                78,                    71,
                          13,                     10,                26,                    10,
                           0,                      0,                 0,                    13,
                          73,                     72,                68,                    82,
                           0,                      0,                 4,                   158,
                           0,                      0,                 6,                   156,
                           8,                      2,                 0,                     0,
                           0,                    210,                38,                   195,
                         159,                      0,                 0,                     0,
                           1,                    115,                82,                    71,
                          66,                      0,               174,                   206,
                          28,                    233,                 0,                     0,
                          32,                      0,                73,                    68,
                          65,                     84,               120,                   156,
                         236,                    221,               217,                   111,
                          29,                    105,               154,                   231,
                         247,                    239,                27,                    17,
                         103,                    223,               184,                   175,
                         162,                    246,                84,                   238,
                         107,                     87,               117,                    85,
                         102,                    117,               117,                   247,
                         216,                     51,                13,                    12,
                         230,                    114,               110,                   124,
                         105,                    255,                19,                   254,
                           7,                    108,               192,                   128,
      ... 1218582 more items, [BYTES_PER_ELEMENT]: 1, [length]: 1218682, [byteLength]: 1218682,
             [byteOffset]: 0,
      [buffer]: ArrayBuffer { byteLength: 1218682 }
    ],
    name: undefined
  },
  [length]: 1
] Error
    at OneBotv11Adapter.sendApi (file:///C:/Users/Administrator/Desktop/Yunzai/plugins/adapter/OneBotv11.js:21:19)
    at Object.sendApi (file:///C:/Users/Administrator/Desktop/Yunzai/plugins/adapter/OneBotv11.js:709:41)
    at file:///C:/Users/Administrator/Desktop/Yunzai/plugins/adapter/OneBotv11.js:113:23
    at OneBotv11Adapter.sendMsg (file:///C:/Users/Administrator/Desktop/Yunzai/plugins/adapter/OneBotv11.js:91:22)
    at async e.reply (file:///C:/Users/Administrator/Desktop/Yunzai/lib/plugins/loader.js:470:15)
    at async YukiHelp.yukiHelp (file:///C:/Users/Administrator/Desktop/Yunzai/plugins/yuki-plugin/apps/help.js:48:9)
    at async PluginsLoader.deal (file:///C:/Users/Administrator/Desktop/Yunzai/lib/plugins/loader.js:262:41) {
  [stack]: 'Error\n' +
    '    at OneBotv11Adapter.sendApi (file:///C:/Users/Administrator/Desktop/Yunzai/plugins/adapter/OneBotv11.js:21:19)\n' +
    '    at Object.sendApi (file:///C:/Users/Administrator/Desktop/Yunzai/plugins/adapter/OneBotv11.js:709:41)\n' +
    '    at file:///C:/Users/Administrator/Desktop/Yunzai/plugins/adapter/OneBotv11.js:113:23\n' +
    '    at OneBotv11Adapter.sendMsg (file:///C:/Users/Administrator/Desktop/Yunzai/plugins/adapter/OneBotv11.js:91:22)\n' +
    '    at async e.reply (file:///C:/Users/Administrator/Desktop/Yunzai/lib/plugins/loader.js:470:15)\n' +
    '    at async YukiHelp.yukiHelp (file:///C:/Users/Administrator/Desktop/Yunzai/plugins/yuki-plugin/apps/help.js:48:9)\n' +
    '    at async PluginsLoader.deal (file:///C:/Users/Administrator/Desktop/Yunzai/lib/plugins/loader.js:262:41)',
  action: 'send_msg',
  params: {
    group_id: X,
    message: [
      {
        type: 'image',
        data: {
          type: undefined,
          file: '{"0":137,"1":80,"2":78,"3":71,"4":13,"5":10,"6":26,"7":10,"8":0,"9":0,"10":0,"11":13,"12":73,"13":72,"14":68,"15":82,"16":0,"17"
:0,"18":4,"19":158,"20":0,"21":0,"22":6,"23":156,"24":8,"25":2,"26":0,"27":0,"28":0,"29":210,"30":38,"31":195,"32":159,"33":0,"34":0,"35":0,"36":
1,"37":115,"38":82,"39":71,"40":66,"41":0,"42":174,"43":206,"44":28,"45":233,"46":0,"47":0,"48":32,"49":0,"50":73,"51":68,"52":65,"53":84,"54":12
0,"55":156,"56":236,"57":221,"58":217,"59":111,"60":29,"61":105,"62":154,"63":231,"64":247,"65":239,"66":27,"67":17,"68":103,"69":223,"70":184,"7
1":175,"72":162,"73":246,"74":84,"75":238,"76":107,"77":87,"78":117,"79":85,"80":102,"81":117,"82":117,"83":247,"84":216,"85":51,"86":13,"87":12,
"88":230,"89":114,"90":110,"91":124,"92":105,"93":255,"94":19,"95":254,"96":7,"97":108,"98":192,"99":128,"100":97,"101":248,"102":118,"103":46,"1
04":236,"105":43,"106":251,"107":102,"108":224,"109":1,"110":198,"111":192,"112":192,"113":221,"114":70,"115":143,"116":209,"117":61,"118":168,"1
19'... 15424040 more characters,
          name: undefined
        }
      },
      [length]: 1
    ]
  },
  echo: '01J5S8FZR1SQGD16Z4GCHNS0EE',
  error: {
    status: 'failed',
    retcode: 1200,
    data: null,
    message: 'Error: 文件下载失败未知文件类型\n' +
      '    at handleOb11FileLikeMessage (file:///C:/Users/Administrator/Desktop/NapCat.win32.x64/napcat.mjs:15898:11)\n' +
      '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
      '    at async Object.image (file:///C:/Users/Administrator/Desktop/NapCat.win32.x64/napcat.mjs:15954:70)\n' +
      '    at async Promise.all (index 0)\n' +
      '    at async createSendElements (file:///C:/Users/Administrator/Desktop/NapCat.win32.x64/napcat.mjs:16078:15)\n' +
      '    at async SendMsg._handle (file:///C:/Users/Administrator/Desktop/NapCat.win32.x64/napcat.mjs:23576:9)\n' +
      '    at async SendMsg.websocketHandle (file:///C:/Users/Administrator/Desktop/NapCat.win32.x64/napcat.mjs:23298:23)\n' +
      '    at async OB11ActiveWebSocketAdapter.handleMessage (file:///C:/Users/Administrator/Desktop/NapCat.win32.x64/napcat.mjs:23985:23)',
    wording: 'Error: 文件下载失败未知文件类型\n' +
      '    at handleOb11FileLikeMessage (file:///C:/Users/Administrator/Desktop/NapCat.win32.x64/napcat.mjs:15898:11)\n' +
      '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
      '    at async Object.image (file:///C:/Users/Administrator/Desktop/NapCat.win32.x64/napcat.mjs:15954:70)\n' +
      '    at async Promise.all (index 0)\n' +
      '    at async createSendElements (file:///C:/Users/Administrator/Desktop/NapCat.win32.x64/napcat.mjs:16078:15)\n' +
      '    at async SendMsg._handle (file:///C:/Users/Administrator/Desktop/NapCat.win32.x64/napcat.mjs:23576:9)\n' +
      '    at async SendMsg.websocketHandle (file:///C:/Users/Administrator/Desktop/NapCat.win32.x64/napcat.mjs:23298:23)\n' +
      '    at async OB11ActiveWebSocketAdapter.handleMessage (file:///C:/Users/Administrator/Desktop/NapCat.win32.x64/napcat.mjs:23985:23)',
    echo: '01J5S8FZR1SQGD16Z4GCHNS0EE',
    raw: '{"status":"failed","retcode":1200,"data":null,"message":"Error: 文件下载失败未知文件类型\\n    at handleOb11FileLikeMessage (file:///C:
/Users/Administrator/Desktop/NapCat.win32.x64/napcat.mjs:15898:11)\\n    at process.processTicksAndRejections (node:internal/process/task_queues:
95:5)\\n    at async Object.image (file:///C:/Users/Administrator/Desktop/NapCat.win32.x64/napcat.mjs:15954:70)\\n    at async Promise.all (index
 0)\\n    at async createSendElements (file:///C:/Users/Administrator/Desktop/NapCat.win32.x64/napcat.mjs:16078:15)\\n    at async SendMsg._handl
e (file:///C:/Users/Administrator/Desktop/NapCat.win32.x64/napcat.mjs:23576:9)\\n    at async SendMsg.websocketHandle (file:///C:/Users/Administr
ator/Desktop/NapCat.win32.x64/napcat.mjs:23298:23)\\n    at async OB11ActiveWebSocketAdapter.handleMessage (file:///C:/Users/Administrator/Deskto
p/NapCat.win32.x64/napcat.mjs:23985:23)","wording":"Error: 文件下载失败未知文件类型\\n    at handleOb11FileLikeMessage (file:///C:/Users/Administ
rator/Desktop/NapCat.win32.x'... 752 more characters
  }
```

**Comment by MliKiowa** [comment]
更新trss

**Comment by Ray-lea** [comment]
> 更新trss

已经是最新了，仍然有此问题

**Comment by MliKiowa** [comment]
去trss开issue

**Comment by Ray-lea** [comment]
> 去trss开issue

好的
