### ISSUE TITLE
[增强] 删除群公告

### ISSUE THREAD

**Issue by intling-luo** [NapNeko/NapCatQQ#299]
### 系统版本

win11 x64 23H2 22635.4076

### QQNT 版本

9.9.15-27333 (64位)

### NapCat 版本

V2.2.5

### OneBot 客户端

我不确定,但是在这里[koishi的onebot适配器](https://github.com/koishijs/koishi-plugin-adapter-onebot?tab=readme-ov-file)

### 发生了什么?

我在koishi插件开发中用到了管理群公告的功能,但获取群公告的接口似乎不起作用

于是我尝试使用postman用get请求的方式,来调用NapCat提供的群公告管理接口:
我尝试调用__send_group_notice发送群公告,bot顺利的发送了公告
但当我尝试使用get_group_notice来获取群公告时,返回了:
```json
{
    "status": "failed",
    "retcode": 200,
    "data": null,
    "message": "Error: 获取公告失败",
    "wording": "Error: 获取公告失败",
    "echo": null
}
```

### 如何复现

使用_get_group_notice接口,填入任意群号

### 期望的结果?

正常来说应当返回一个群公告集合

**另外,NapCat用了好久都超级稳定方便,大佬的项目真的超级好用❤️
还有,非常希望大佬另外能加入删除群公告的接口❤️❤️❤️
在go-cq-http时代就一直想要这个功能了...bot只会发要手动删好难受😭😭😭**

### NapCat 运行日志

```shell
2024-08-24 22:46:58 [DEBUG] 若雨(xx) | ProfileListener has no method onGroupNotifiesUnreadCountUpdated 
2024-08-24 22:46:58 [DEBUG] 若雨(xx) | ProfileListener has no method onGroupNotifiesUnreadCountUpdated 
2024-08-24 22:47:19 [ERROR] 若雨(xx) | 发生错误 Error: 获取公告失败
    at GetGroupNotice._handle (file:///C:/Users/xx/Documents/LiteloaderQQNT/plugins/NapCat.Framework/napcat.mjs:27243:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async GetGroupNotice.handle (file:///C:/Users/xx/Documents/LiteloaderQQNT/plugins/NapCat.Framework/napcat.mjs:20370:23)
    at async OB11PassiveHttpAdapter.handleRequest (file:///C:/Users/xx/Documents/LiteloaderQQNT/plugins/NapCat.Framework/napcat.mjs:21653:24) 
2024-08-24 22:49:02 [ERROR] 若雨(xx) | 发生错误 Error: 获取公告失败
    at GetGroupNotice._handle (file:///C:/Users/xx/Documents/LiteloaderQQNT/plugins/NapCat.Framework/napcat.mjs:27243:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async GetGroupNotice.handle (file:///C:/Users/xx/Documents/LiteloaderQQNT/plugins/NapCat.Framework/napcat.mjs:20370:23)
    at async OB11PassiveHttpAdapter.handleRequest (file:///C:/Users/xx/Documents/LiteloaderQQNT/plugins/NapCat.Framework/napcat.mjs:21653:24) 
2024-08-24 22:49:03 [ERROR] 若雨(xx) | 发生错误 Error: 获取公告失败
    at GetGroupNotice._handle (file:///C:/Users/xx/Documents/LiteloaderQQNT/plugins/NapCat.Framework/napcat.mjs:27243:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async GetGroupNotice.handle (file:///C:/Users/xx/Documents/LiteloaderQQNT/plugins/NapCat.Framework/napcat.mjs:20370:23)
    at async OB11PassiveHttpAdapter.handleRequest (file:///C:/Users/xx/Documents/LiteloaderQQNT/plugins/NapCat.Framework/napcat.mjs:21653:24)
```

### OneBot 客户端运行日志

```shell
024-08-24 22:34:24 [W] app Error: Error with request _get_group_notice, args: {"group_id":xx}, retcode: 1200
                            at _Internal._get (D:\koishi\dev\koishi-app\node_modules\koishi-plugin-adapter-onebot\lib\index.js:119:11)
                            at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
                            at async _Internal.<computed> [as getGroupNotice] (D:\koishi\dev\koishi-app\node_modules\koishi-plugin-adapter-onebot\lib\index.js:152:20)
```

**Comment by MliKiowa** [comment]
已修 https://github.com/NapNeko/NapCatQQ/actions/runs/10539558443

**Comment by MliKiowa** [comment]
在这里面可以拿到最新测试版本

**Comment by intling-luo** [comment]
> 已修 https://github.com/NapNeko/NapCatQQ/actions/runs/10539558443

谢谢大佬!
另外,删除群公告的功能有望吗😭

**Comment by intling-luo** [comment]
谢谢大佬!!!😭

**Comment by MliKiowa** [comment]
> > 已修 https://github.com/NapNeko/NapCatQQ/actions/runs/10539558443
> 
> 谢谢大佬! 另外,删除群公告的功能有望吗😭

可以做 但是今晚太晚了

**Comment by MliKiowa** [comment]
已兼容 https://github.com/NapNeko/NapCatQQ/actions/runs/10539712463
api: _del_group_notice
参数: group_id feed_id 
feed_id从获取中取
