### ISSUE TITLE
[BUG] 未知条件下，通过 `HttpPost` 的快捷回复功能无效并报错

### ISSUE THREAD

**Issue by Delsin-Yu** [NapNeko/NapCatQQ#322]
### 系统版本

Debian GNU/Linux 12 (bookworm)

### QQNT 版本

3.2.12-26909

### NapCat 版本

2.0.37

### OneBot 客户端

通过 `HttpPost` 和 `HttpApi` 通信的独立 `ASP.Net Minimal API` 客户端

### 发生了什么?

在使用 `HttpPost` 的快捷回复功能发送特定Json文本时，无法正常回复，并且 `NapCat` 的控制台中会打印错误信息

### 如何复现

在接受到群消息类型的上报信息时，回复以下 Json 信息（部分信息已脱敏处理）
```json
{
  "reply": [
    {
      "type": "text",
      "data": {
        "text": "\u6765\u81eaXXXXXX(000000000)\u5bf9XXX(000000000)\u7684\u67e5\u8be2\uff1a\n\u6b64\u7528\u6237\u7684\u5f53\u524d\u8bb0\u5f55\u6570\u91cf\uff1aX\n"
      }
    },
    {
      "type": "text",
      "data": {
        "text": "-------------------------------\n[000] XX\uff0cXXX(000000000)\uff1a\nXXXXXXX\n20XX August XX XX:XX:XXX\n"
      }
    },
    {
      "type": "image",
      "data": {
        "file": "file:///home/GroupModeratorBot/ImageDb/545D1BCB3XXXXXXXX2D39BC84D45D2.png"
      }
    },
    {
      "type": "image",
      "data": {
        "file": "file:///home/GroupModeratorBot/ImageDb/5E56129BXXXXXX971DD3CFBA5D79E.png"
      }
    }
  ]
}
```

### 期望的结果?

NapCat 客户端应当正确的发送reply信息中所指定的信息和图片

### NapCat 运行日志

*已脱敏的日志*
```log
2024-08-29 07:40:21 [INFO] BOTUSERNAME(<BOTQQID>) | 接收 <- 群聊 (群 <GROUPID> 的 <CLIENTQQID>) @BOTUSERNAME (<BOTQQID>)  查询 QQ <SEARCHQUERY> 
2024-08-29 07:40:21 [INFO] BOTUSERNAME(<BOTQQID>) | 发送 -> 群聊 (群 <GROUPID> 的 <BOTQQID>) [回复消息 群聊 (群 <GROUPID> 的 <CLIENTQQID>) @BOTUSERNAME (<BOTQQID>)  查询 QQ <SEARCHQUERY>] 来自<CLIENTNAME>(<CLIENTQQID>)对用户(<SEARCHQUERY>)的查询：
此用户的当前记录数量：1
 -------------------------------
[133] XX，XXX(00000000000)：
XXXXXXXX
20XX August XX XX:XX:XX
 [图片 545D1BCB3XXXXXXXX2D39BC84D45D2.png] [图片 5E56129BXXXXXX971DD3CFBA5D79E.png] 
(node:17034) UnhandledPromiseRejectionWarning: TypeError: Cannot read properties of undefined (reading '_log')
    at logError (file:///opt/QQ/resources/app/app_launcher/napcat/napcat.mjs:7853:10)
(Use `qq --trace-warnings ...` to show where the warning was created)
(node:17034) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 6)
```

### OneBot 客户端运行日志

通过 `HttpPost` 和 `HttpApi` 通信的独立 `ASP.Net Minimal API` 客户端，Http请求无异常。

**Comment by Delsin-Yu** [comment]
在以下版本中也可以复现

### QQNT 版本

3.2.12-240819

### NapCat 版本

2.2.24

### NapCat 运行日志

*已脱敏的日志*

```log
2024-08-29 08:27:42 [INFO] BOTUSERNAME | 接收 <- 群聊 (群 <GROUPID> 的 <CLIENTQQID>) @BOTUSERNAME (<BOTQQID>)  查询 QQ <SEARCHQUERY> 
2024-08-29 08:27:43 [INFO] BOTUSERNAME | 发送 -> 群聊 (群 <GROUPID> 的 <BOTQQID>) [回复消息 群聊 (群 <GROUPID> 的 <CLIENTQQID>) @BOTUSERNAME (<BOTQQID>)  查询 QQ <SEARCHQUERY>] 来自<CLIENTNAME>(<CLIENTQQID>)对用户(<SEARCHQUERY>)的查询：
此用户的当前记录数量：1
 -------------------------------
[133] XX，XXX(00000000000)：
XXXXXXXX
20XX August XX XX:XX:XX
 [图片 545D1BCB3XXXXXXXX2D39BC84D45D2.png] [图片 5E56129BXXXXXX971DD3CFBA5D79E.png] 
2024-08-29 08:27:57 [INFO] BOTUSERNAME | 接收 <- 群聊 (群 <GROUPID> 的 <CLIENTQQID>) 。。。。 
2024-08-29 08:27:57 [ERROR] BOTUSERNAME | Error: Timeout: NTEvent serviceAndMethod:NodeIKernelMsgService/sendMsg ListenerName:NodeIKernelMsgListener/onMsgInfoListUpdate EventRet:
{
    "result": 0,
    "errMsg": ""
}

    at Timeout.sendDataCallback [as _onTimeout] (file:///opt/QQ/resources/app/app_launcher/napcat/napcat.mjs:7458:18)
    at listOnTimeout (node:internal/timers:573:17)
    at process.processTimers (node:internal/timers:514:7)
```

**Comment by Delsin-Yu** [comment]
图被和谐了
