### ISSUE TITLE
[BUG] get_group_member_info timeout

### ISSUE THREAD

**Issue by 0x1227** [NapNeko/NapCatQQ#34]
### 系统版本

debian

### QQNT 版本

最新版

### NapCat 版本

最新版

### OneBot 客户端

最新版

### 发生了什么?

get_group_member_info api访问超时

### 如何复现

await bot.get_group_member_info(group_id = gid, user_id = uid)

### 期望的结果?

get_group_member_info 获取群成员信息

group_id | number (int64) | 群号
-- | -- | --
user_id | number (int64) | QQ 号
nickname | string | 昵称
card | string | 群名片／备注
sex | string | 性别，male 或 female 或 unknown
age | number (int32) | 年龄
area | string | 地区
join_time | number (int32) | 加群时间戳
last_sent_time | number (int32) | 最后发言时间戳
level | string | 成员等级
role | string | 角色，owner 或 admin 或 member
unfriendly | boolean | 是否不良记录成员
title | string | 专属头衔
title_expire_time | number (int32) | 专属头衔过期时间戳
card_changeable | boolean | 是否允许修改群名片

### NapCat 运行日志

```shell
2024-05-24 09:44:57 [INFO] (3243780392) 
{"errno":-111,"code":"ECONNREFUSED","syscall":"connect","address":"172.17.0.2","port":8890}
```

### OneBot 客户端运行日志

```shell
Traceback (most recent call last):
  File "<string>", line 15, in <module>
  File "/usr/local/lib/python3.12/site-packages/nonebot/__init__.py", line 335, in run
    get_driver().run(*args, **kwargs)
  File "/usr/local/lib/python3.12/site-packages/nonebot/drivers/fastapi.py", line 186, in run
    uvicorn.run(
  File "/usr/local/lib/python3.12/site-packages/uvicorn/main.py", line 575, in run
    server.run()
  File "/usr/local/lib/python3.12/site-packages/uvicorn/server.py", line 65, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/local/lib/python3.12/asyncio/runners.py", line 194, in run
    return runner.run(main)
  File "/usr/local/lib/python3.12/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
  File "/usr/local/lib/python3.12/site-packages/nonebot/message.py", line 466, in check_and_run_matcher
    if not await _check_matcher(
> File "/usr/local/lib/python3.12/site-packages/nonebot/message.py", line 361, in _check_matcher
    if not await Matcher.check_perm(bot, event, stack, dependency_cache):
  File "/usr/local/lib/python3.12/site-packages/nonebot/internal/matcher/matcher.py", line 375, in check_perm
    return event_type == (cls.type or event_type) and await cls.permission(
  File "/usr/local/lib/python3.12/site-packages/nonebot/internal/permission.py", line 73, in __call__
    results = await asyncio.gather(
  File "/usr/local/lib/python3.12/site-packages/nonebot/utils.py", line 236, in run_coro_with_catch
    return await coro
  File "/usr/local/lib/python3.12/site-packages/nonebot/dependencies/__init__.py", line 94, in __call__
    return await cast(Callable[..., Awaitable[R]], self.call)(**values)
  File "/root/data/src/plugins/g_admin.py", line 17, in _g_admin
    info = await bot.get_group_member_info(group_id = gid, user_id = uid)
  File "/usr/local/lib/python3.12/site-packages/nonebot/internal/adapter/bot.py", line 122, in call_api
    raise exception
  File "/usr/local/lib/python3.12/site-packages/nonebot/internal/adapter/bot.py", line 97, in call_api
    result = await self.adapter._call_api(self, api, **data)
  File "/usr/local/lib/python3.12/site-packages/nonebot/adapters/onebot/v11/adapter.py", line 149, in _call_api
    raise NetworkError(f"WebSocket call api {api} timeout") from None
nonebot.adapters.onebot.v11.exception.NetworkError: NetWorkError(message='WebSocket call api get_group_member_info timeout')
```

**Comment by MliKiowa** [comment]
https://github.com/NapNeko/NapCatQQ/actions/runs/9222322778 试试里面的版本

**Comment by MliKiowa** [comment]
测试如果有问题再reopen

**Comment by qianxuu** [comment]
v1.4.0 仍然超时
```
Traceback (most recent call last):                                                                                 
  File "<string>", line 15, in <module>                                                                                                                                                                                                
  File "/root/napcat/napcat-nb/.venv/lib/python3.11/site-packages/nonebot/__init__.py", line 335, in run
    get_driver().run(*args, **kwargs)                                                                              
  File "/root/napcat/napcat-nb/.venv/lib/python3.11/site-packages/nonebot/drivers/fastapi.py", line 186, in run                                                                                                                        
    uvicorn.run(                                                                                                   
  File "/root/napcat/napcat-nb/.venv/lib/python3.11/site-packages/uvicorn/main.py", line 575, in run        
    server.run()                                                                                                   
  File "/root/napcat/napcat-nb/.venv/lib/python3.11/site-packages/uvicorn/server.py", line 65, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
  File "/usr/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
  File "/root/napcat/napcat-nb/.venv/lib/python3.11/site-packages/nonebot/message.py", line 476, in check_and_run_matcher
    await _run_matcher(
> File "/root/napcat/napcat-nb/.venv/lib/python3.11/site-packages/nonebot/message.py", line 428, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "/root/napcat/napcat-nb/.venv/lib/python3.11/site-packages/nonebot/internal/matcher/matcher.py", line 850, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "/root/napcat/napcat-nb/.venv/lib/python3.11/site-packages/nonebot/internal/matcher/matcher.py", line 825, in simple_run
    await handler(
  File "/root/napcat/napcat-nb/.venv/lib/python3.11/site-packages/nonebot/dependencies/__init__.py", line 94, in __call__
    return await cast(Callable[..., Awaitable[R]], self.call)(**values)
  File "/root/napcat/napcat-nb/plugins/whoatme/__init__.py", line 63, in msg_handle
    at_target_name = await bot.get_group_member_info(group_id=ev.group_id, user_id=seg.data['qq'])
  File "/root/napcat/napcat-nb/.venv/lib/python3.11/site-packages/nonebot/internal/adapter/bot.py", line 122, in call_api
    raise exception
  File "/root/napcat/napcat-nb/.venv/lib/python3.11/site-packages/nonebot/internal/adapter/bot.py", line 97, in call_api
    result = await self.adapter._call_api(self, api, **data)
  File "/root/napcat/napcat-nb/.venv/lib/python3.11/site-packages/nonebot/adapters/onebot/v11/adapter.py", line 149, in _call_api
    raise NetworkError(f"WebSocket call api {api} timeout") from None
nonebot.adapters.onebot.v11.exception.NetworkError: NetWorkError(message='WebSocket call api get_group_member_info timeout')
```

**Comment by 0x1227** [comment]
> https://github.com/NapNeko/NapCatQQ/actions/runs/9222322778 试试里面的版本

1.4.0测试依然超时，这个构建出来的目录结构和发布版本不太一样，无法直接add到docker里使用！！！

**Comment by MliKiowa** [comment]
> > https://github.com/NapNeko/NapCatQQ/actions/runs/9222322778 试试里面的版本
> 
> 1.4.0测试依然超时！ 9222322778构建的测试依然超时！
> 
> @MliKiowa 大佬

你在tg或者q群吗
