### ISSUE TITLE
[BUG] overflow无法ws正向连接

### ISSUE THREAD

**Issue by dokurorz** [NapNeko/NapCatQQ#356]
### 系统版本

Debian 5.10.209-2

### QQNT 版本

3.2.12-27597

### NapCat 版本

2.4.4

### OneBot 客户端

Overflow v2.16.0-795845b-SNAPSHOT

### 发生了什么?

更新到2.4.4后，overflow正向连接到napcat，会断开连接，overflow报错如下，napcat内无日志，相同配置下nonebot和koishi均正常
```
2024-09-11 14:47:29 I/Onebot: Overflow v2.16.0-795845b-SNAPSHOT 正在运行
2024-09-11 14:47:29 I/Onebot: 连接到 WebSocket: ws://172.18.0.1:3001
2024-09-11 14:47:29 I/Onebot: ▌ 已连接到服务器 ┈━═☆
2024-09-11 14:47:29 E/top.mrxiaom.overflow.internal.deps.websocket.drafts.Draft_6455: Runtime exception during onWebsocketMessage
java.lang.UnsupportedOperationException: JsonNull
        at top.mrxiaom.overflow.internal.deps.gson.JsonElement.getAsString(JsonElement.java:187)
        at cn.evole.onebot.sdk.util.json.JsonsObject.optString(JsonsObject.java:68)
        at cn.evole.onebot.sdk.util.json.JsonsObject.optString(JsonsObject.java:64)
        at cn.evolvefield.onebot.client.handler.ActionHandler.onReceiveActionResp(ActionHandler.kt:36)
        at cn.evolvefield.onebot.client.connection.WSClient.onMessage(WSClient.kt:61)
        at top.mrxiaom.overflow.internal.deps.websocket.client.WebSocketClient.onWebsocketMessage(WebSocketClient.java:636)
        at top.mrxiaom.overflow.internal.deps.websocket.drafts.Draft_6455.processFrameText(Draft_6455.java:986)
        at top.mrxiaom.overflow.internal.deps.websocket.drafts.Draft_6455.processFrame(Draft_6455.java:910)
        at top.mrxiaom.overflow.internal.deps.websocket.WebSocketImpl.decodeFrames(WebSocketImpl.java:402)
        at top.mrxiaom.overflow.internal.deps.websocket.WebSocketImpl.decode(WebSocketImpl.java:241)
        at top.mrxiaom.overflow.internal.deps.websocket.client.WebSocketClient.run(WebSocketClient.java:516)
        at java.base/java.lang.Thread.run(Thread.java:829)

2024-09-11 14:47:29 E/Onebot: ▌ 出现错误 JsonNull 或未连接 ┈━═☆
2024-09-11 14:47:29 I/Onebot: ▌ 服务器连接因 未知原因 已关闭 (关闭码: NORMAL)
2024-09-11 14:47:39 W/Onebot: Request failed: [get_version_info, echo=0] Mutex is not locked
2024-09-11 14:47:39 E/Onebot: 未连接到 Onebot
```

之前使用的是1.8.6，可以正常连接，注意到之前有类似的issue[#307](https://github.com/NapNeko/NapCatQQ/issues/307)，不确实这次是哪边的问题，先反馈一下

### 如何复现

napcat配置
```
{
...
...
"ws": {
    "enable": true,
    "host": "0.0.0.0",
    "port": 3001
  },
...
...
 "token": "114514",
}
```

overflow配置
```
{
    "ws_host": "ws://172.18.0.1:3001",
    "reversed_ws_port": -1,
    "token": "114514",
    "retry_times": 5,
    "retry_wait_mills": 5000,
    "retry_rest_mills": 60000
}
```

### 期望的结果?

...

**Comment by MliKiowa** [comment]
尝试下反向连接

**Comment by MliKiowa** [comment]
给overflow提issue
