### ISSUE TITLE
[BUG] 戳一戳一直返回错误

### ISSUE THREAD

**Issue by zxmacc** [NapNeko/NapCatQQ#36]
### 系统版本

Linux ubuntu 22.04 lts

### QQNT 版本

3.2.8_240520

### NapCat 版本

v1.4.0

### OneBot 客户端

Overflow v2.16.0-f37b538-SNAPSHOT.1

### 发生了什么?

戳一戳一直返回发生错误

### 如何复现

1.下载napcat1.4.0
2.解压替换旧版napcat1.3.0文件
3.启动napcat
4.扫码登录
5.启动Overflow
6.连接正向ws
7.群内和私聊对机器人账号戳一戳
8.返回发生错误，群xxxxx不存在

### 期望的结果?

戳一戳正常返回

### NapCat 运行日志

```shell
2024-05-25 21:03:19 [INFO] 小辰(1xxxxx7) 
[私聊] 用户  32xxxxxxx4  对你戳一戳 

2024-05-25 21:03:19 [ERROR] 小辰(1xxxxxx7) 
发生错误 群0不存在 

2024-05-25 21:04:48 [INFO] 小辰(1xxxxxx7) 
[群聊] 群组  39xxxxxx1  戳一戳 

2024-05-25 21:04:49 [ERROR] 小辰(1xxxxxx7) 
发生错误 群39xxxxxx1不存在
```

### OneBot 客户端运行日志

```shell
2024-05-25 21:03:14 I/Onebot: Overflow v2.16.0-f37b538-SNAPSHOT.1 正在运行
2024-05-25 21:03:14 I/Onebot: 连接到 WebSocket: ws://127.0.0.1:4002
2024-05-25 21:03:14 I/main: mirai-console started successfully.
2024-05-25 21:03:14 I/Onebot: ▌ 已连接到服务器 ┈━═☆
2024-05-25 21:03:14 I/BiliBili Dynamic: BiliBili UID: 5xxxxxxx1
2024-05-25 21:03:14 I/Onebot: 服务端版本信息
{
  "status": "ok",
  "retcode": 0,
  "data": {
    "app_name": "NapCat.Onebot",
    "protocol_version": "v11",
    "app_version": "1.4.0"
  },
  "message": "",
  "wording": "",
  "echo": 0
}
2024-05-25 21:03:15 I/BiliBili Dynamic: 加载字体 LXGW WenKai 成功
2024-05-25 21:03:15 V/Bot.1992588307: Event: BotOnlineEvent(bot=Bot(1xxxxxxx7))
2024-05-25 21:03:19 W/Onebot: Request failed: [get_group_info] app=NapCat.Onebot v1.4.0, message=群0不存在, retJson
={"status":"failed","retcode":1200,"data":null,"message":"群0不存在","wording":"群0不存在","echo":20}
2024-05-25 21:03:19 W/stderr: Exception in thread "DefaultDispatcher-worker-11" java.lang.IllegalStateException: 无
  取得群 0 的信息
2024-05-25 21:03:19 W/stderr:   at top.mrxiaom.overflow.internal.utils.TransformerUtilsKt.group(TransformerUtils.kt:63)
2024-05-25 21:03:19 W/stderr:   at top.mrxiaom.overflow.internal.utils.TransformerUtilsKt$group$1.invokeSuspend(TransformerUtils.kt)
2024-05-25 21:03:19 W/stderr:   at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
2024-05-25 21:03:19 W/stderr:   at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:33)
2024-05-25 21:03:19 W/stderr:   at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
2024-05-25 21:03:19 W/stderr:   at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
2024-05-25 21:03:19 W/stderr:   at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
2024-05-25 21:03:19 W/stderr:   at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
2024-05-25 21:03:19 W/stderr:   at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
2024-05-25 21:03:19 W/stderr:   at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
2024-05-25 21:03:19 W/stderr:   at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
2024-05-25 21:03:19 W/stderr:   Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [CoroutineName(overflow), StandaloneCoroutine{Cancelling}@27ca9c1c, Dispatchers.Default]
2024-05-25 21:04:27 I/PetPet: PetTemplate/zun_point下载成功 (length:1)
2024-05-25 21:04:49 W/Onebot: Request failed: [get_group_info] app=NapCat.Onebot v1.4.0, message=群3918898971不存在
, retJson={"status":"failed","retcode":1200,"data":null,"message":"群3xxxxxxx1不存在","wording":"群3xxxxxxx1不存
  ","echo":22}
2024-05-25 21:04:49 W/stderr: Exception in thread "DefaultDispatcher-worker-8" java.lang.IllegalStateException: 无
  取得群 3xxxxxxx1 的信息
2024-05-25 21:04:49 W/stderr:   at top.mrxiaom.overflow.internal.utils.TransformerUtilsKt.group(TransformerUtils.kt:63)
2024-05-25 21:04:49 W/stderr:   at top.mrxiaom.overflow.internal.utils.TransformerUtilsKt$group$1.invokeSuspend(TransformerUtils.kt)
2024-05-25 21:04:49 W/stderr:   at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
2024-05-25 21:04:49 W/stderr:   at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:33)
2024-05-25 21:04:49 W/stderr:   at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
2024-05-25 21:04:49 W/stderr:   at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
2024-05-25 21:04:49 W/stderr:   at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
2024-05-25 21:04:49 W/stderr:   at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
2024-05-25 21:04:49 W/stderr:   at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
2024-05-25 21:04:49 W/stderr:   at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
2024-05-25 21:04:49 W/stderr:   at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
2024-05-25 21:04:49 W/stderr:   Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [CoroutineName(overflow), StandaloneCoroutine{Cancelling}@603708e1, Dispatchers.Default]
```

**Comment by MliKiowa** [comment]
非NC问题 这是自己在请求错误的group 其戳一戳 在群里无法获取操作者userid

**Comment by MliKiowa** [comment]
对了 群3xxxxxxx1 真的存在吗

**Comment by MR-MonkeyRay** [comment]
或者可以加一个配置忽略戳一戳嘛?
[文档](https://napneko.github.io/zh-CN/guide/config)里面没找到..
也或者可以在日志上减少错误输出的信息量?

**Comment by MliKiowa** [comment]
可以加一个 你也可以在overflow这边提 因为pc协议端都是这样 应该是下游兼容

**Comment by zxmacc** [comment]
> 对了 群3xxxxxxx1 Bot在群里吗

在的

**Comment by zxmacc** [comment]
那我先结束了
