### ISSUE TITLE
[BUG] Napcat无法正确获取rkey导致无法接收图片

### ISSUE THREAD

**Issue by HYY1116** [NapNeko/NapCatQQ#363]
### 系统版本

Windows10专业版

### QQNT 版本

9.9.15-27597

### NapCat 版本

2.5.0

### OneBot 客户端

Onebotv11

### 发生了什么?

在接收到图片时，控制台报错Get Rkey http://napcat-sign.wumiao.wang:2082/rkey Error  Error: Unexpected status code: 403，手动访问时发现出现CF的人机验证，可能是这个原因导致无法正常获取rkey

### 如何复现

发送图片后，控制台报错

手动访问http://napcat-sign.wumiao.wang:2082/rkey
![Uploading f7e0dc612e4ba0d641baade276deceaf.png…]()

### 期望的结果?

Napcat应当能正常获取到rkey

### NapCat 运行日志

```shell
2024-09-14 09:31:18 [ERROR]   | [Rkey] Get Rkey https://llob.linyuchen.net/rkey Error  Error: Unexpected status code: 403
    at IncomingMessage.<anonymous> (file:///   /NapCatNew/napcat.mjs:4930:22)
    at IncomingMessage.emit (node:events:531:35)
    at endReadableNT (node:internal/streams/readable:1696:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
2024-09-14 09:31:18 [ERROR]  | [Rkey] Get Rkey http://napcat-sign.wumiao.wang:2082/rkey Error  Error: Unexpected status code: 403
    at IncomingMessage.<anonymous> (file:///  /NapCatNew/napcat.mjs:4930:22)
    at IncomingMessage.emit (node:events:531:35)
    at endReadableNT (node:internal/streams/readable:1696:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
```

### OneBot 客户端运行日志

```shell
2024-09-14 09:31:18,651 [ OneBot11][     INFO] Bot:653709392 Channel:  User:  兔兔: [image]
2024-09-14 09:31:20,111 [  Default][    ERROR] Windows.Media.Ocr error: Traceback (most recent call last):
  File "C:\Users\HYY\Desktop\Amiya-Bot\plugins\amiyabot-arknights-recruit-2_9\main.py", line 272, in get_ocr_result
    pil_image = Image.open(BytesIO(img))
  File "C:\Users\HYY\Envs\Amiya\lib\site-packages\PIL\Image.py", line 3298, in open
    raise UnidentifiedImageError(msg)
PIL.UnidentifiedImageError: cannot identify image file <_io.BytesIO object at 0x000001A8219E3090>
2024-09-14 09:31:20,143 [ OneBot11][     INFO] Bot:653709392 Channel:  User:  兔兔: @HYY图片识别失败
```

**Comment by HYY1116** [comment]
![f7e0dc612e4ba0d641baade276deceaf](https://github.com/user-attachments/assets/98f4409e-eb8c-422f-b5d5-796450c395f0)
![QQ20240914-093410](https://github.com/user-attachments/assets/715fb010-1e05-4217-9387-cf79a6be6eef)

**Comment by MliKiowa** [comment]
这种情况你的ip脏了 我也没什么比较好的办法

**Comment by devil233-ui** [comment]
> 这种情况你的ip脏了 我也没什么比较好的办法

我只有群聊才会出现这问题，私聊是正常的。用的trss崽ws反接
![Image_1726461861041](https://github.com/user-attachments/assets/bc3a8381-cd3b-4a57-80f9-10cabe88374d)
