### ISSUE TITLE
[BUG] 语音转换失败 (Compiling function #52 failed: Wasm SIMD unsupported @+17323). Build with -sASSERTIONS for more info.)

### ISSUE THREAD

**Issue by rm7rzedg** [NapNeko/NapCatQQ#383]
### 系统版本

Windows10 Pro 22H2

### QQNT 版本

9.9.15-27597

### NapCat 版本

2.5.3

### OneBot 客户端

null(自己糊的接口)

### 发生了什么?

将ffmpeg的bin添加到环境变量,并在cmd中输入ffmpeg确认环境变量正确的情况下,退出QQ然后再打开之后(重开QQ是确保新加的环境变量被正确加载,`不是第一次可以用重启qq之后不能用的意思`) 发送语音消息时返回`语音转换失败, 请检查语音文件是否正常`

### 如何复现

按照说明添加ffmpeg
然后调用发送群消息api发送语音消息
```
curl --location 'http://104.1.2.3/send_group_msg' \
--header 'Host: abcdefg.lan' \
--header 'Content-Type: application/json' \
--data '{
  "group_id": 1234567890,
  "access_token": "hidden",
  "message": "[CQ:record,file=https://dds.dui.ai/runtime/v1/synthesize?voiceId=hchunf_ctn&text=%E6%82%A8%E5%A5%BD%E4%B8%96%E7%95%8C&speed=1&volume=100&audioType=mp3]"
}'
```

### 期望的结果?

正常发送消息

### NapCat 运行日志

```shell
2024-09-18 23:52:50 [DEBUG] () | [Core] [Config] 配置文件C:\Users\root\Documents\LiteloaderQQNT\plugins\NapCat.Framework\config\napcat_1234567890.json加载 {"fileLog":true,"consoleLog":true,"fileLogLevel":"debug","consoleLogLevel":"info"} 
2024-09-18 23:52:50 [DEBUG] () | [Core] [Config] 配置文件C:\Users\root\Documents\LiteloaderQQNT\plugins\NapCat.Framework\config\onebot11_1234567890.json加载 {"http":{"enable":true,"host":"","port":3000,"secret":"","enableHeart":false,"enablePost":true,"postUrls":["https://qqbot.localhost.lan/api/mirai"]},"ws":{"enable":false,"host":"","port":3001},"reverseWs":{"enable":false,"urls":[]},"GroupLocalTime":{"Record":false,"RecordList":[]},"debug":false,"heartInterval":30000,"messagePostFormat":"array","enableLocalFile2Url":true,"musicSignUrl":"","reportSelfMessage":false,"token":""} 
2024-09-18 23:52:50 [INFO] () | [Notice] [OneBot11] 
    HTTP服务 已启动, :3000
    HTTP上报服务 已启动, 上报地址: https://qqbot.localhost.lan/api/mirai
    WebSocket服务 未启动, :3001
    WebSocket反向服务 未启动, 反向地址:  
2024-09-18 23:52:50 [DEBUG] () | 加载36个群组缓存完成 
2024-09-18 23:52:50 [INFO] () | [OneBot] [HTTP Server Adapter] Start On Port 3000 
2024-09-18 23:52:50 [INFO] () | [NapCat] [WebUi] Current WebUi is running at http://0.0.0.0:6099 
2024-09-18 23:52:50 [INFO] () | [NapCat] [WebUi] Login Token is hiddentoken 
2024-09-18 23:52:50 [INFO] () | [NapCat] [WebUi] WebUi User  Panel Url: http://0.0.0.0:6099/webui?token=hiddentoken 
2024-09-18 23:52:50 [INFO] () | [NapCat] [WebUi] WebUi Local Panel Url: http://127.0.0.1:6099/webui?token=hiddentoken 
2024-09-18 23:52:54 [INFO] qqbot(1234567890) | [NapCat] [WebUi] WebUi Publish Panel Url: http://fe80::1:6099/webui/?token=hiddentoken 
2024-09-18 23:53:02 [INFO] qqbot(1234567890) | 语音文件C:\Users\root\Documents\Tencent Files\NapCat\temp\fab2f759-0d5b-4efe-af72-c95f85137924需要转换成silk 
2024-09-18 23:53:06 [ERROR] qqbot(1234567890) | convert silk failed RuntimeError: Aborted(CompileError: WebAssembly.instantiate(): Compiling function #52 failed: Wasm SIMD unsupported @+17323). Build with -sASSERTIONS for more info.
    at sa (C:\Users\root\Documents\LiteloaderQQNT\plugins\NapCat.Framework\node_modules\silk-wasm\lib\index.cjs:1:3236)
    at C:\Users\root\Documents\LiteloaderQQNT\plugins\NapCat.Framework\node_modules\silk-wasm\lib\index.cjs:1:3769 
2024-09-18 23:53:06 [ERROR] qqbot(1234567890) | 发生错误 Error: 语音转换失败, 请检查语音文件是否正常
    at NTQQFileApi.createValidSendPttElement (file:///C:/Users/root/Documents/LiteloaderQQNT/plugins/NapCat.Framework/napcat.mjs:5694:13)
    at async Promise.all (index 0)
    at async OneBotMsgApi.createSendElements (file:///C:/Users/root/Documents/LiteloaderQQNT/plugins/NapCat.Framework/napcat.mjs:25679:17)
    at async SendGroupMsg._handle (file:///C:/Users/root/Documents/LiteloaderQQNT/plugins/NapCat.Framework/napcat.mjs:33084:9)
    at async SendGroupMsg.handle (file:///C:/Users/root/Documents/LiteloaderQQNT/plugins/NapCat.Framework/napcat.mjs:32942:23)
    at async OB11PassiveHttpAdapter.handleRequest (file:///C:/Users/root/Documents/LiteloaderQQNT/plugins/NapCat.Framework/napcat.mjs:10050:24) 
2024-09-18 23:54:12 [INFO] qqbot(1234567890) | 语音文件C:\Users\root\Documents\Tencent Files\NapCat\temp\9e4c5968-fb81-4ce3-9953-615f2fd64bd9.mp3需要转换成silk 
2024-09-18 23:54:13 [ERROR] qqbot(1234567890) | convert silk failed RuntimeError: Aborted(CompileError: WebAssembly.instantiate(): Compiling function #52 failed: Wasm SIMD unsupported @+17323). Build with -sASSERTIONS for more info.
    at sa (C:\Users\root\Documents\LiteloaderQQNT\plugins\NapCat.Framework\node_modules\silk-wasm\lib\index.cjs:1:3236)
    at C:\Users\root\Documents\LiteloaderQQNT\plugins\NapCat.Framework\node_modules\silk-wasm\lib\index.cjs:1:3769 
2024-09-18 23:54:13 [ERROR] qqbot(1234567890) | 发生错误 Error: 语音转换失败, 请检查语音文件是否正常
    at NTQQFileApi.createValidSendPttElement (file:///C:/Users/root/Documents/LiteloaderQQNT/plugins/NapCat.Framework/napcat.mjs:5694:13)
    at async Promise.all (index 0)
    at async OneBotMsgApi.createSendElements (file:///C:/Users/root/Documents/LiteloaderQQNT/plugins/NapCat.Framework/napcat.mjs:25679:17)
    at async SendGroupMsg._handle (file:///C:/Users/root/Documents/LiteloaderQQNT/plugins/NapCat.Framework/napcat.mjs:33084:9)
    at async SendGroupMsg.handle (file:///C:/Users/root/Documents/LiteloaderQQNT/plugins/NapCat.Framework/napcat.mjs:32942:23)
    at async OB11PassiveHttpAdapter.handleRequest (file:///C:/Users/root/Documents/LiteloaderQQNT/plugins/NapCat.Framework/napcat.mjs:10050:24)
```

### OneBot 客户端运行日志

```shell
{
    "status": "failed",
    "retcode": 200,
    "data": null,
    "message": "Error: 语音转换失败, 请检查语音文件是否正常",
    "wording": "Error: 语音转换失败, 请检查语音文件是否正常",
    "echo": null
}
```

**Comment by MliKiowa** [comment]
cpu过老 不支持simd

**Comment by MliKiowa** [comment]
尝试换现代一点的机器 或者云服务器
