### ISSUE TITLE
[BUG] 发送部分经典表情，比如灯笼，会引起NapCatQQ 异常

### ISSUE THREAD

**Issue by 123233513** [NapNeko/NapCatQQ#385]
### 系统版本

Windows 11 家庭中文版 23H2

### QQNT 版本

QQ9.9.15.28131_x64

### NapCat 版本

2.6.9

### OneBot 客户端

OneBot 11

### 发生了什么?

使用 launcher.bat 启动NapCatQQ后，通过webui设置“启用正向 WebSocket 服务”，在postman 中连接 ws://127.0.0.1:3001，发送内容：
`{
    "action": "send_group_msg",
    "params": {
        "group_id": 371202800,
        "message":[{"type":"text","data":{"text":"表 情测试"}},{"type":"face","data":{"id":"138"}}]
    }
}`

引发异常，信息如下：
`{
    "status": "failed",
    "retcode": 1200,
    "data": null,
    "message": "TypeError: Cannot read properties of undefined (reading 'AniStickerType')\n    at Object.face (file:///C:/NapCatQQ/NapCatQQ/napcat.mjs:29639:16)\n    at OneBotMsgApi.createSendElements (file:///C:/NapCatQQ/NapCatQQ/napcat.mjs:29926:64)\n    at SendGroupMsg._handle (file:///C:/NapCatQQ/NapCatQQ/napcat.mjs:36706:85)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async SendGroupMsg.websocketHandle (file:///C:/NapCatQQ/NapCatQQ/napcat.mjs:36606:23)\n    at async OB11PassiveWebSocketAdapter.handleMessage (file:///C:/NapCatQQ/NapCatQQ/napcat.mjs:13687:21)",
    "wording": "TypeError: Cannot read properties of undefined (reading 'AniStickerType')\n    at Object.face (file:///C:/NapCatQQ/NapCatQQ/napcat.mjs:29639:16)\n    at OneBotMsgApi.createSendElements (file:///C:/NapCatQQ/NapCatQQ/napcat.mjs:29926:64)\n    at SendGroupMsg._handle (file:///C:/NapCatQQ/NapCatQQ/napcat.mjs:36706:85)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async SendGroupMsg.websocketHandle (file:///C:/NapCatQQ/NapCatQQ/napcat.mjs:36606:23)\n    at async OB11PassiveWebSocketAdapter.handleMessage (file:///C:/NapCatQQ/NapCatQQ/napcat.mjs:13687:21)",
    "echo": ""
}`

从 napcat.mjs 文件中找到了官方文件：// nt_qq\global\nt_data\Emoji\emoji-resource\face_config.json，没有找到 "QSid": "138",
经典的表情都在目录下 \nt_qq\global\nt_data\Emoji\emoji-resource\sysface_res\static

如果想发送face_config.json 没有涵盖的系统表情，该怎么发送？

### 如何复现

1、群里发送QQ经典表情中的"灯笼"，NapCatQQ 上报的消息是：,"message":[{"type":"face","data":{"id":"138"}}]
2、在postman 中连接 ws://127.0.0.1:3001，发送内容：
`{
    "action": "send_group_msg",
    "params": {
        "group_id": 371202899,
        "message":[{"type":"text","data":{"text":"表 情测试"}},{"type":"face","data":{"id":"138"}}]
    }
}`
即可触发异常。

### 期望的结果?

希望支持更多的系统自带表情。
如果发送的内容中包含了face_config.json不存在的face id，是否可以考虑过滤掉，而不影响其它能显示的内容？

### NapCat 运行日志

```shell
2024-09-19 19:52:35 [INFO] 散热管(169232923) | 接收 <- 群聊 (群 散热管371202800 的 123233513) 表情测试 [表情 ] 
2024-09-19 19:52:35 [DEBUG] 散热管(169232923) | 收到新消息 RawMessage {"msgId":"7416320841292325490","msgRandom":"471274235","msgSeq":"20692","cntSeq":"0","chatType":2,"msgType":2,"subMsgType":17,"sendType":0,"senderUid":"u_lsP8ErVVq6ccb3BV0X16_A","peerUid":"散热管371202800","channelId":"","guildId":"","guildCode":"0","fromUid":"0","fromAppid":"0","msgTime":"1726746755","msgMeta":{},"sendStatus":2,"sendRemarkName":"","sendMemberName":"【测试】℡雾季无雨★、","sendNickName":"","guildName":"","channelName":"","elements":[{"elementType":1,"elementId":"7416320841292325488","elementGroupId":0,"extBufForUI":{},"textElement":{"content":"表情测试","atType":0,"atUid":"0","atTinyId":"0","atNtUid":"","subElementType":0,"atChannelId":"0","linkInfo":null,"atRoleId":"0","atRoleColor":0,"atRoleName":"","needNotify":0},"faceElement":null,"marketFaceElement":null,"replyElement":null,"picElement":null,"pttElement":null,"videoElement":null,"grayTipElement":null,"arkElement":null,"fileElement":null,"liveGiftElement":null,"markdownElement":null,"structLongMsgElement":null,"multiForwardMsgElement":null,"giphyElement":null,"walletElement":null,"inlineKeyboardElement":null,"textGiftElement":null,"calendarElement":null,"yoloGameResultElement":null,"avRecordElement":null,"structMsgElement":null,"faceBubbleElement":null,"shareLocationElement":null,"tofuRecordElement":null,"taskTopMsgElement":null,"recommendedMsgElement":null,"actionBarElement":null,"prologueMsgElement":null},{"elementType":6,"elementId":"7416320841292325489","elementGroupId":0,"extBufForUI":{},"textElement":null,"faceElement":{"faceIndex":138,"faceText":null,"faceType":1,"packId":null,"stickerId":null,"sourceType":null,"stickerType":null,"resultId":null,"surpriseId":null,"randomType":null,"imageType":null,"pokeType":null,"spokeSummary":null,"doubleHit":null,"vaspokeId":null,"vaspokeName":null,"vaspokeMinver":null,"pokeStrength":null,"msgType":null,"faceBubbleCount":null,"oldVersionStr":null,"pokeFlag":null,"chainCount":null},"marketFaceElement":null,"replyElement":null,"picElement":null,"pttElement":null,"videoElement":null,"grayTipElement":null,"arkElement":null,"fileElement":null,"liveGiftElement":null,"markdownElement":null,"structLongMsgElement":null,"multiForwardMsgElement":null,"giphyElement":null,"walletElement":null,"inlineKeyboardElement":null,"textGiftElement":null,"calendarElement":null,"yoloGameResultElement":null,"avRecordElement":null,"structMsgElement":null,"faceBubbleElement":null,"shareLocationElement":null,"tofuRecordElement":null,"taskTopMsgElement":null,"recommendedMsgElement":null,"actionBarElement":null,"prologueMsgElement":null}],"records":[],"emojiLikesList":[],"commentCnt":"0","directMsgFlag":0,"directMsgMembers":[],"peerName":"测试群","freqLimitInfo":null,"editable":false,"avatarMeta":"","avatarPendant":"","feedId":"","roleId":"0","timeStamp":"0","clientIdentityInfo":null,"isImportMsg":false,"atType":0,"roleType":0,"fromChannelRoleInfo":{"roleId":"0","name":"","color":0},"fromGuildRoleInfo":{"roleId":"0","name":"","color":0},"levelRoleInfo":{"roleId":"0","name":"","color":0},"recallTime":"0","isOnlineMsg":true,"generalFlags":{},"clientSeq":"0","fileGroupSize":null,"foldingInfo":null,"multiTransInfo":null,"senderUin":"123233513","peerUin":"散热管371202800","msgAttrs":{},"anonymousExtInfo":null,"nameType":0,"avatarFlag":0,"extInfoForUI":null,"personalMedal":null,"categoryManage":0,"msgEventInfo":null,"sourceType":1,"id":479949812} 
2024-09-19 19:52:35 [DEBUG] 散热管(169232923) | 转化为 OB11Message {"self_id":169232923,"user_id":123233513,"time":1726746755,"message_id":479949812,"message_seq":479949812,"real_id":479949812,"message_type":"group","sender":{"user_id":123233513,"nickname":"℡雾季无雨★、","card":"【测试】℡雾季无雨★、","role":"member"},"raw_message":"表情测试[CQ:face,id=138]","font":14,"sub_type":"normal","message":[{"type":"text","data":{"text":"表情测试"}},{"type":"face","data":{"id":"138"}}],"message_format":"array","post_type":"message","group_id":散热管371202800} 
2024-09-19 19:54:04 [ERROR] 散热管(169232923) | 发生错误 TypeError: Cannot read properties of undefined (reading 'AniStickerType')
    at Object.face (file:///C:/NapCatQQ/NapCatQQ/napcat.mjs:29639:16)
    at OneBotMsgApi.createSendElements (file:///C:/NapCatQQ/NapCatQQ/napcat.mjs:29926:64)
    at SendGroupMsg._handle (file:///C:/NapCatQQ/NapCatQQ/napcat.mjs:36706:85)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async SendGroupMsg.websocketHandle (file:///C:/NapCatQQ/NapCatQQ/napcat.mjs:36606:23)
    at async OB11PassiveWebSocketAdapter.handleMessage (file:///C:/NapCatQQ/NapCatQQ/napcat.mjs:13687:21)
```

**Comment by MliKiowa** [comment]
下下个版本修复

**Comment by MliKiowa** [comment]
当前不影响使用

**Comment by MliKiowa** [comment]
https://github.com/NapNeko/NapCatQQ/commit/0dbfe8ca55b8a0780c0c7c17c73f7773d6b239cd

**Comment by MliKiowa** [comment]
以后空了 会补充这个的
