### ISSUE TITLE
[BUG] 初始化OneBot失败

### ISSUE THREAD

**Issue by bianyuan456** [NapNeko/NapCatQQ#412]
### 系统版本

windows 11

### QQNT 版本

9.9.15-28327 (64位)

### NapCat 版本

2.6.15

### OneBot 客户端

无

### 发生了什么?

 [ERROR] () | 初始化OneBot失败 TypeError: Cannot read properties of undefined (reading 'enable')
    at NapCatOneBot11Adapter.InitOneBot (file:///D:/ProgramFiles/NapCat/NapCatQQ/napcat.mjs:39151:33)
    at new NapCatOneBot11Adapter (file:///D:/ProgramFiles/NapCat/NapCatQQ/napcat.mjs:39143:10)
    at new NapCatShell (file:///D:/ProgramFiles/NapCat/NapCatQQ/napcat.mjs:40327:5)
    at NCoreInitShell (file:///D:/ProgramFiles/NapCat/NapCatQQ/napcat.mjs:40303:3)

### 如何复现

使用bat运行，bat的内容如下：
.\launcher.bat 2768885004
pause

运行后截图如下
![image](https://github.com/user-attachments/assets/d232878d-6e8a-4788-b493-a826fcfbd958)

重启电脑尝试过，还是一样的结果。
另外希望支持自定义QQNT目录的功能，这样就可以跟旧版本的QQNT共存，我是说直接改launcher.bat中的
SET QQPath=D:\ProgramFiles\NapCat\QQNT\QQ.exe
就可以实现跟旧版本的QQNT共存的话就好了，希望作者考虑支持这个功能。

### 期望的结果?

应该能成功创建onebot

### NapCat 运行日志

```shell
2024-09-28 16:21:09 [INFO] () | [NapCat] [Core] NapCat.Core Version: 2.6.15 
2024-09-28 16:21:10 [INFO] () | [NapCat] [WebUi] Current WebUi is running at http://0.0.0.0:6099 
2024-09-28 16:21:10 [INFO] () | [NapCat] [WebUi] Login Token is 2aee3kqevx4 
2024-09-28 16:21:10 [INFO] () | [NapCat] [WebUi] WebUi User  Panel Url: http://0.0.0.0:6099/webui?token=2aee3kqevx4 
2024-09-28 16:21:10 [INFO] () | [NapCat] [WebUi] WebUi Local Panel Url: http://127.0.0.1:6099/webui?token=2aee3kqevx4 
2024-09-28 16:21:10 [INFO] () | 核心登录服务连接成功! 
2024-09-28 16:21:10 [INFO] () | 正在快速登录  2768885004 
2024-09-28 16:21:11 [INFO] () | [NapCat] [WebUi] WebUi Publish Panel Url: http://60.210.204.220:6099/webui/?token=2aee3kqevx4 
2024-09-28 16:21:13 [DEBUG] () | 本账号数据/缓存目录： F:\WorkPlace\QQ\NapCat\data 
2024-09-28 16:21:13 [DEBUG] () | [Core] [Config] 配置文件D:\ProgramFiles\NapCat\NapCatQQ\config\napcat_2768885004.json加载 {"fileLog":true,"consoleLog":true,"fileLogLevel":"debug","consoleLogLevel":"info"} 
2024-09-28 16:21:13 [DEBUG] () | [Core] [Config] 配置文件D:\ProgramFiles\NapCat\NapCatQQ\config\onebot11_2768885004.json加载 {"http":{"enable":true,"port":3000,"postUrls":["http://127.0.0.1:3000/"]},"reportSelfMessage":true} 
2024-09-28 16:21:13 [ERROR] () | 初始化OneBot失败 TypeError: Cannot read properties of undefined (reading 'enable')
    at NapCatOneBot11Adapter.InitOneBot (file:///D:/ProgramFiles/NapCat/NapCatQQ/napcat.mjs:39151:33)
    at new NapCatOneBot11Adapter (file:///D:/ProgramFiles/NapCat/NapCatQQ/napcat.mjs:39143:10)
    at new NapCatShell (file:///D:/ProgramFiles/NapCat/NapCatQQ/napcat.mjs:40327:5)
    at NCoreInitShell (file:///D:/ProgramFiles/NapCat/NapCatQQ/napcat.mjs:40303:3) 
2024-09-28 16:21:13 [DEBUG] () | 加载9个群组缓存完成
```

**Comment by MliKiowa** [comment]
检查配置文件

**Comment by bianyuan456** [comment]
> 检查配置文件

是onebot11_2768885004.json 中的port和postUrls的端口写重复了，我的问题。。感谢解答
