### ISSUE TITLE
[BUG] constructSysMessage error

### ISSUE THREAD

**Issue by sckiyo** [NapNeko/NapCatQQ#417]
### 系统版本

docker arm64

### QQNT 版本

3.2.12-28327

### NapCat 版本

2.6.18

### OneBot 客户端

无

### 发生了什么?

满屏的报错

### 如何复现

正常启动

### 期望的结果?

正常运行

### NapCat 运行日志

```shell
2024-09-30 00:02:42 [[91mERROR[39m] () | constructSysMessage error:  RangeError: premature EOF
    at BinaryReader.assertBounds (file:///app/napcat/napcat.mjs:17042:19)
    at BinaryReader.bytes (file:///app/napcat/napcat.mjs:17131:14)
    at BinaryReader.string (file:///app/napcat/napcat.mjs:17138:45)
    at ReflectionBinaryReader.scalar (file:///app/napcat/napcat.mjs:18570:31)
    at ReflectionBinaryReader.read (file:///app/napcat/napcat.mjs:18493:50)
    at MessageType.internalBinaryRead (file:///app/napcat/napcat.mjs:19183:27)
    at ReflectionBinaryReader.read (file:///app/napcat/napcat.mjs:18498:45)
    at MessageType.internalBinaryRead (file:///app/napcat/napcat.mjs:19183:27)
    at decodeSysMessage (file:///app/napcat/napcat.mjs:19342:25)
    at OneBotMsgApi.parseSysMessage (file:///app/napcat/napcat.mjs:23986:20) 
2024-09-30 00:02:42 [[91mERROR[39m] () | constructSysMessage error:  RangeError: premature EOF
    at BinaryReader.assertBounds (file:///app/napcat/napcat.mjs:17042:19)
    at BinaryReader.bytes (file:///app/napcat/napcat.mjs:17131:14)
    at BinaryReader.string (file:///app/napcat/napcat.mjs:17138:45)
    at ReflectionBinaryReader.scalar (file:///app/napcat/napcat.mjs:18570:31)
    at ReflectionBinaryReader.read (file:///app/napcat/napcat.mjs:18493:50)
    at MessageType.internalBinaryRead (file:///app/napcat/napcat.mjs:19183:27)
    at ReflectionBinaryReader.read (file:///app/napcat/napcat.mjs:18498:45)
    at MessageType.internalBinaryRead (file:///app/napcat/napcat.mjs:19183:27)
    at decodeSysMessage (file:///app/napcat/napcat.mjs:19342:25)
    at OneBotMsgApi.parseSysMessage (file:///app/napcat/napcat.mjs:23986:20) 
2024-09-30 00:02:42 [[91mERROR[39m] () | constructSysMessage error:  RangeError: premature EOF
    at BinaryReader.assertBounds (file:///app/napcat/napcat.mjs:17042:19)
    at BinaryReader.bytes (file:///app/napcat/napcat.mjs:17131:14)
    at BinaryReader.string (file:///app/napcat/napcat.mjs:17138:45)
    at ReflectionBinaryReader.scalar (file:///app/napcat/napcat.mjs:18570:31)
    at ReflectionBinaryReader.read (file:///app/napcat/napcat.mjs:18493:50)
    at MessageType.internalBinaryRead (file:///app/napcat/napcat.mjs:19183:27)
    at ReflectionBinaryReader.read (file:///app/napcat/napcat.mjs:18498:45)
    at MessageType.internalBinaryRead (file:///app/napcat/napcat.mjs:19183:27)
    at decodeSysMessage (file:///app/napcat/napcat.mjs:19342:25)
    at OneBotMsgApi.parseSysMessage (file:///app/napcat/napcat.mjs:23986:20) 
2024-09-30 00:02:42 [[91mERROR[39m] () | constructSysMessage error:  RangeError: premature EOF
    at BinaryReader.assertBounds (file:///app/napcat/napcat.mjs:17042:19)
    at BinaryReader.bytes (file:///app/napcat/napcat.mjs:17131:14)
    at BinaryReader.string (file:///app/napcat/napcat.mjs:17138:45)
    at ReflectionBinaryReader.scalar (file:///app/napcat/napcat.mjs:18570:31)
    at ReflectionBinaryReader.read (file:///app/napcat/napcat.mjs:18493:50)
    at MessageType.internalBinaryRead (file:///app/napcat/napcat.mjs:19183:27)
    at ReflectionBinaryReader.read (file:///app/napcat/napcat.mjs:18498:45)
    at MessageType.internalBinaryRead (file:///app/napcat/napcat.mjs:19183:27)
    at decodeSysMessage (file:///app/napcat/napcat.mjs:19342:25)
    at OneBotMsgApi.parseSysMessage (file:///app/napcat/napcat.mjs:23986:20) 
2024-09-30 00:02:43 [[91mERROR[39m] () | constructSysMessage error:  RangeError: premature EOF
    at BinaryReader.assertBounds (file:///app/napcat/napcat.mjs:17042:19)
    at BinaryReader.bytes (file:///app/napcat/napcat.mjs:17131:14)
    at BinaryReader.string (file:///app/napcat/napcat.mjs:17138:45)
    at ReflectionBinaryReader.scalar (file:///app/napcat/napcat.mjs:18570:31)
    at ReflectionBinaryReader.read (file:///app/napcat/napcat.mjs:18493:50)
    at MessageType.internalBinaryRead (file:///app/napcat/napcat.mjs:19183:27)
    at ReflectionBinaryReader.read (file:///app/napcat/napcat.mjs:18498:45)
    at MessageType.internalBinaryRead (file:///app/napcat/napcat.mjs:19183:27)
    at decodeSysMessage (file:///app/napcat/napcat.mjs:19342:25)
    at OneBotMsgApi.parseSysMessage (file:///app/napcat/napcat.mjs:23986:20) 
2024-09-30 00:02:44 [[91mERROR[39m] () | constructSysMessage error:  RangeError: premature EOF
    at BinaryReader.assertBounds (file:///app/napcat/napcat.mjs:17042:19)
    at BinaryReader.bytes (file:///app/napcat/napcat.mjs:17131:14)
    at BinaryReader.string (file:///app/napcat/napcat.mjs:17138:45)
    at ReflectionBinaryReader.scalar (file:///app/napcat/napcat.mjs:18570:31)
    at ReflectionBinaryReader.read (file:///app/napcat/napcat.mjs:18493:50)
    at MessageType.internalBinaryRead (file:///app/napcat/napcat.mjs:19183:27)
    at ReflectionBinaryReader.read (file:///app/napcat/napcat.mjs:18498:45)
    at MessageType.internalBinaryRead (file:///app/napcat/napcat.mjs:19183:27)
    at decodeSysMessage (file:///app/napcat/napcat.mjs:19342:25)
    at OneBotMsgApi.parseSysMessage (file:///app/napcat/napcat.mjs:23986:20) 
2024-09-30 00:02:44 [[91mERROR[39m] () | constructSysMessage error:  RangeError: premature EOF
    at BinaryReader.assertBounds (file:///app/napcat/napcat.mjs:17042:19)
    at BinaryReader.bytes (file:///app/napcat/napcat.mjs:17131:14)
    at BinaryReader.string (file:///app/napcat/napcat.mjs:17138:45)
    at ReflectionBinaryReader.scalar (file:///app/napcat/napcat.mjs:18570:31)
    at ReflectionBinaryReader.read (file:///app/napcat/napcat.mjs:18493:50)
    at MessageType.internalBinaryRead (file:///app/napcat/napcat.mjs:19183:27)
    at ReflectionBinaryReader.read (file:///app/napcat/napcat.mjs:18498:45)
    at MessageType.internalBinaryRead (file:///app/napcat/napcat.mjs:19183:27)
    at decodeSysMessage (file:///app/napcat/napcat.mjs:19342:25)
    at OneBotMsgApi.parseSysMessage (file:///app/napcat/napcat.mjs:23986:20) 
2024-09-30 00:02:44 [[91mERROR[39m] () | constructSysMessage error:  RangeError: premature EOF
    at BinaryReader.assertBounds (file:///app/napcat/napcat.mjs:17042:19)
    at BinaryReader.bytes (file:///app/napcat/napcat.mjs:17131:14)
    at BinaryReader.string (file:///app/napcat/napcat.mjs:17138:45)
    at ReflectionBinaryReader.scalar (file:///app/napcat/napcat.mjs:18570:31)
    at ReflectionBinaryReader.read (file:///app/napcat/napcat.mjs:18493:50)
    at MessageType.internalBinaryRead (file:///app/napcat/napcat.mjs:19183:27)
    at ReflectionBinaryReader.read (file:///app/napcat/napcat.mjs:18498:45)
    at MessageType.internalBinaryRead (file:///app/napcat/napcat.mjs:19183:27)
    at decodeSysMessage (file:///app/napcat/napcat.mjs:19342:25)
    at OneBotMsgApi.parseSysMessage (file:///app/napcat/napcat.mjs:23986:20) 
2024-09-30 00:02:45 [[91mERROR[39m] () | constructSysMessage error:  RangeError: premature EOF
    at BinaryReader.assertBounds (file:///app/napcat/napcat.mjs:17042:19)
    at BinaryReader.bytes (file:///app/napcat/napcat.mjs:17131:14)
    at BinaryReader.string (file:///app/napcat/napcat.mjs:17138:45)
    at ReflectionBinaryReader.scalar (file:///app/napcat/napcat.mjs:18570:31)
    at ReflectionBinaryReader.read (file:///app/napcat/napcat.mjs:18493:50)
    at MessageType.internalBinaryRead (file:///app/napcat/napcat.mjs:19183:27)
    at ReflectionBinaryReader.read (file:///app/napcat/napcat.mjs:18498:45)
    at MessageType.internalBinaryRead (file:///app/napcat/napcat.mjs:19183:27)
    at decodeSysMessage (file:///app/napcat/napcat.mjs:19342:25)
    at OneBotMsgApi.parseSysMessage (file:///app/napcat/napcat.mjs:23986:20) 
2024-09-30 00:02:45 [[91mERROR[39m] () | constructSysMessage error:  RangeError: premature EOF
    at BinaryReader.assertBounds (file:///app/napcat/napcat.mjs:17042:19)
    at BinaryReader.bytes (file:///app/napcat/napcat.mjs:17131:14)
    at BinaryReader.string (file:///app/napcat/napcat.mjs:17138:45)
    at ReflectionBinaryReader.scalar (file:///app/napcat/napcat.mjs:18570:31)
    at ReflectionBinaryReader.read (file:///app/napcat/napcat.mjs:18493:50)
    at MessageType.internalBinaryRead (file:///app/napcat/napcat.mjs:19183:27)
    at ReflectionBinaryReader.read (file:///app/napcat/napcat.mjs:18498:45)
    at MessageType.internalBinaryRead (file:///app/napcat/napcat.mjs:19183:27)
    at decodeSysMessage (file:///app/napcat/napcat.mjs:19342:25)
    at OneBotMsgApi.parseSysMessage (file:///app/napcat/napcat.mjs:23986:20) 
2024-09-30 00:02:45 [[91mERROR[39m] () | constructSysMessage error:  RangeError: premature EOF
    at BinaryReader.assertBounds (file:///app/napcat/napcat.mjs:17042:19)
    at BinaryReader.bytes (file:///app/napcat/napcat.mjs:17131:14)
    at BinaryReader.string (file:///app/napcat/napcat.mjs:17138:45)
    at ReflectionBinaryReader.scalar (file:///app/napcat/napcat.mjs:18570:31)
    at ReflectionBinaryReader.read (file:///app/napcat/napcat.mjs:18493:50)
    at MessageType.internalBinaryRead (file:///app/napcat/napcat.mjs:19183:27)
    at ReflectionBinaryReader.read (file:///app/napcat/napcat.mjs:18498:45)
    at MessageType.internalBinaryRead (file:///app/napcat/napcat.mjs:19183:27)
    at decodeSysMessage (file:///app/napcat/napcat.mjs:19342:25)
    at OneBotMsgApi.parseSysMessage (file:///app/napcat/napcat.mjs:23986:20) 
2024-09-30 00:02:46 [[91mERROR[39m] () | constructSysMessage error:  RangeError: premature EOF
    at BinaryReader.assertBounds (file:///app/napcat/napcat.mjs:17042:19)
    at BinaryReader.bytes (file:///app/napcat/napcat.mjs:17131:14)
    at BinaryReader.string (file:///app/napcat/napcat.mjs:17138:45)
    at ReflectionBinaryReader.scalar (file:///app/napcat/napcat.mjs:18570:31)
    at ReflectionBinaryReader.read (file:///app/napcat/napcat.mjs:18493:50)
    at MessageType.internalBinaryRead (file:///app/napcat/napcat.mjs:19183:27)
    at ReflectionBinaryReader.read (file:///app/napcat/napcat.mjs:18498:45)
    at MessageType.internalBinaryRead (file:///app/napcat/napcat.mjs:19183:27)
    at decodeSysMessage (file:///app/napcat/napcat.mjs:19342:25)
    at OneBotMsgApi.parseSysMessage (file:///app/napcat/napcat.mjs:23986:20) 
2024-09-30 00:02:46 [[91mERROR[39m] () | constructSysMessage error:  RangeError: premature EOF
    at BinaryReader.assertBounds (file:///app/napcat/napcat.mjs:17042:19)
    at BinaryReader.bytes (file:///app/napcat/napcat.mjs:17131:14)
    at BinaryReader.string (file:///app/napcat/napcat.mjs:17138:45)
    at ReflectionBinaryReader.scalar (file:///app/napcat/napcat.mjs:18570:31)
    at ReflectionBinaryReader.read (file:///app/napcat/napcat.mjs:18493:50)
    at MessageType.internalBinaryRead (file:///app/napcat/napcat.mjs:19183:27)
    at ReflectionBinaryReader.read (file:///app/napcat/napcat.mjs:18498:45)
    at MessageType.internalBinaryRead (file:///app/napcat/napcat.mjs:19183:27)
    at decodeSysMessage (file:///app/napcat/napcat.mjs:19342:25)
    at OneBotMsgApi.parseSysMessage (file:///app/napcat/napcat.mjs:23986:20) 
2024-09-30 00:02:47 [[91mERROR[39m] () | constructSysMessage error:  RangeError: premature EOF
    at BinaryReader.assertBounds (file:///app/napcat/napcat.mjs:17042:19)
    at BinaryReader.bytes (file:///app/napcat/napcat.mjs:17131:14)
    at BinaryReader.string (file:///app/napcat/napcat.mjs:17138:45)
    at ReflectionBinaryReader.scalar (file:///app/napcat/napcat.mjs:18570:31)
    at ReflectionBinaryReader.read (file:///app/napcat/napcat.mjs:18493:50)
    at MessageType.internalBinaryRead (file:///app/napcat/napcat.mjs:19183:27)
    at ReflectionBinaryReader.read (file:///app/napcat/napcat.mjs:18498:45)
    at MessageType.internalBinaryRead (file:///app/napcat/napcat.mjs:19183:27)
    at decodeSysMessage (file:///app/napcat/napcat.mjs:19342:25)
    at OneBotMsgApi.parseSysMessage (file:///app/napcat/napcat.mjs:23986:20) 
2024-09-30 00:02:48 [[91mERROR[39m] () | constructSysMessage error:  RangeError: premature EOF
    at BinaryReader.assertBounds (file:///app/napcat/napcat.mjs:17042:19)
    at BinaryReader.bytes (file:///app/napcat/napcat.mjs:17131:14)
    at BinaryReader.string (file:///app/napcat/napcat.mjs:17138:45)
    at ReflectionBinaryReader.scalar (file:///app/napcat/napcat.mjs:18570:31)
    at ReflectionBinaryReader.read (file:///app/napcat/napcat.mjs:18493:50)
    at MessageType.internalBinaryRead (file:///app/napcat/napcat.mjs:19183:27)
    at ReflectionBinaryReader.read (file:///app/napcat/napcat.mjs:18498:45)
    at MessageType.internalBinaryRead (file:///app/napcat/napcat.mjs:19183:27)
    at decodeSysMessage (file:///app/napcat/napcat.mjs:19342:25)
    at OneBotMsgApi.parseSysMessage (file:///app/napcat/napcat.mjs:23986:20) 
2024-09-30 00:02:48 [[91mERROR[39m] () | constructSysMessage error:  RangeError: premature EOF
    at BinaryReader.assertBounds (file:///app/napcat/napcat.mjs:17042:19)
    at BinaryReader.bytes (file:///app/napcat/napcat.mjs:17131:14)
    at BinaryReader.string (file:///app/napcat/napcat.mjs:17138:45)
    at ReflectionBinaryReader.scalar (file:///app/napcat/napcat.mjs:18570:31)
    at ReflectionBinaryReader.read (file:///app/napcat/napcat.mjs:18493:50)
    at MessageType.internalBinaryRead (file:///app/napcat/napcat.mjs:19183:27)
    at ReflectionBinaryReader.read (file:///app/napcat/napcat.mjs:18498:45)
    at MessageType.internalBinaryRead (file:///app/napcat/napcat.mjs:19183:27)
    at decodeSysMessage (file:///app/napcat/napcat.mjs:19342:25)
    at OneBotMsgApi.parseSysMessage (file:///app/napcat/napcat.mjs:23986:20) 
2024-09-30 00:02:48 [[91mERROR[39m] () | constructSysMessage error:  RangeError: premature EOF
    at BinaryReader.assertBounds (file:///app/napcat/napcat.mjs:17042:19)
    at BinaryReader.bytes (file:///app/napcat/napcat.mjs:17131:14)
    at BinaryReader.string (file:///app/napcat/napcat.mjs:17138:45)
    at ReflectionBinaryReader.scalar (file:///app/napcat/napcat.mjs:18570:31)
    at ReflectionBinaryReader.read (file:///app/napcat/napcat.mjs:18493:50)
    at MessageType.internalBinaryRead (file:///app/napcat/napcat.mjs:19183:27)
    at ReflectionBinaryReader.read (file:///app/napcat/napcat.mjs:18498:45)
    at MessageType.internalBinaryRead (file:///app/napcat/napcat.mjs:19183:27)
    at decodeSysMessage (file:///app/napcat/napcat.mjs:19342:25)
    at OneBotMsgApi.parseSysMessage (file:///app/napcat/napcat.mjs:23986:20) 
2024-09-30 00:02:48 [[91mERROR[39m] () | constructSysMessage error:  RangeError: premature EOF
    at BinaryReader.assertBounds (file:///app/napcat/napcat.mjs:17042:19)
    at BinaryReader.bytes (file:///app/napcat/napcat.mjs:17131:14)
    at BinaryReader.string (file:///app/napcat/napcat.mjs:17138:45)
    at ReflectionBinaryReader.scalar (file:///app/napcat/napcat.mjs:18570:31)
    at ReflectionBinaryReader.read (file:///app/napcat/napcat.mjs:18493:50)
    at MessageType.internalBinaryRead (file:///app/napcat/napcat.mjs:19183:27)
    at ReflectionBinaryReader.read (file:///app/napcat/napcat.mjs:18498:45)
    at MessageType.internalBinaryRead (file:///app/napcat/napcat.mjs:19183:27)
    at decodeSysMessage (file:///app/napcat/napcat.mjs:19342:25)
    at OneBotMsgApi.parseSysMessage (file:///app/napcat/napcat.mjs:23986:20)
```

**Comment by MliKiowa** [comment]
已修复
