### ISSUE TITLE
[BUG] 发生错误和新消息事件HTTP上报失败

### ISSUE THREAD

**Issue by bianyuan456** [NapNeko/NapCatQQ#433]
### 系统版本

windows 11

### QQNT 版本

9.9.15.28418

### NapCat 版本

2.6.25

### OneBot 客户端

无

### 发生了什么?

NapCat.Shell。无头模式。发消息后报错。一共反馈2个问题，第1个是日志显示发生错误，第2个是日志显示 新消息事件HTTP上报失败
![截图20241012083334](https://github.com/user-attachments/assets/42608a28-6f75-4d01-b618-33d346dcf0fe)
![截图20241012083629](https://github.com/user-attachments/assets/1b906789-3259-474d-837e-b0bff11e272b)
![截图20241012083715](https://github.com/user-attachments/assets/fe01c9d3-01c6-4770-b0c7-4a08cae3c452)

### 如何复现

不清楚

### 期望的结果?

应该不报错

### NapCat 运行日志

```shell
发生错误的CMD命令行中的日志：

2024-10-12 08:29:37 [[32mINFO[39m] 北部(2768885004) | 接收 <- 群聊 [机器人测试(928119404)] [‭(763797223)] 111
2024-10-12 08:30:12 [[91mERROR[39m] 北部(2768885004) | 发生错误 Error: Recall failed
    at DeleteMsg._handle (file:///D:/ProgramFiles/NapCat/NapCatQQ/napcat.mjs:31142:13)
    at DeleteMsg.handle (file:///D:/ProgramFiles/NapCat/NapCatQQ/napcat.mjs:30606:34)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async OB11PassiveHttpAdapter.handleRequest (file:///D:/ProgramFiles/NapCat/NapCatQQ/napcat.mjs:13414:24)
2024-10-12 08:30:13 [[32mINFO[39m] 北部(2768885004) | 发送 -> 群聊 [机器人测试(928119404)] [北部(2768885004)] @‭ (7637 ... )   未成功登录！可尝试重新输入指令！











----------
发生错误的logs文件夹中的日志

2024-10-12 08:29:37 [INFO] 北部(2768885004) | 接收 <- 群聊 [机器人测试(928119404)] [‭(763797223)] 111 
2024-10-12 08:29:37 [DEBUG] 北部(2768885004) | 收到新消息 RawMessage {"msgId":"7424679801985976972","msgRandom":"3158470831","msgSeq":"20941","cntSeq":"0","chatType":2,"msgType":2,"subMsgType":1,"sendType":0,"senderUid":"u_1ic89cfIimEMDkMQ8obg_w","peerUid":"928119404","channelId":"","guildId":"","guildCode":"0","fromUid":"0","fromAppid":"0","msgTime":"1728692976","msgMeta":{},"sendStatus":2,"sendRemarkName":"","sendMemberName":"","sendNickName":"‭","guildName":"","channelName":"","elements":[{"elementType":1,"elementId":"7424679801985976971","elementGroupId":0,"extBufForUI":{},"textElement":{"content":"111","atType":0,"atUid":"0","atTinyId":"0","atNtUid":"","subElementType":0,"atChannelId":"0","linkInfo":null,"atRoleId":"0","atRoleColor":0,"atRoleName":"","needNotify":0},"faceElement":null,"marketFaceElement":null,"replyElement":null,"picElement":null,"pttElement":null,"videoElement":null,"grayTipElement":null,"arkElement":null,"fileElement":null,"liveGiftElement":null,"markdownElement":null,"structLongMsgElement":null,"multiForwardMsgElement":null,"giphyElement":null,"walletElement":null,"inlineKeyboardElement":null,"textGiftElement":null,"calendarElement":null,"yoloGameResultElement":null,"avRecordElement":null,"structMsgElement":null,"faceBubbleElement":null,"shareLocationElement":null,"tofuRecordElement":null,"taskTopMsgElement":null,"recommendedMsgElement":null,"actionBarElement":null,"prologueMsgElement":null}],"records":[],"emojiLikesList":[],"commentCnt":"0","directMsgFlag":0,"directMsgMembers":[],"peerName":"机器人测试","freqLimitInfo":null,"editable":false,"avatarMeta":"","avatarPendant":"","feedId":"","roleId":"0","timeStamp":"0","clientIdentityInfo":null,"isImportMsg":false,"atType":0,"roleType":0,"fromChannelRoleInfo":{"roleId":"0","name":"","color":0},"fromGuildRoleInfo":{"roleId":"0","name":"","color":0},"levelRoleInfo":{"roleId":"0","name":"","color":0},"recallTime":"0","isOnlineMsg":true,"generalFlags":{},"clientSeq":"0","fileGroupSize":null,"foldingInfo":null,"multiTransInfo":null,"senderUin":"763797223","peerUin":"928119404","msgAttrs":{},"anonymousExtInfo":null,"nameType":0,"avatarFlag":0,"extInfoForUI":null,"personalMedal":null,"categoryManage":0,"msgEventInfo":null,"sourceType":1,"id":1972387509} 
2024-10-12 08:29:37 [DEBUG] 北部(2768885004) | 转化为 OB11Message {"self_id":2768885004,"user_id":763797223,"time":1728692976,"message_id":1972387509,"message_seq":1972387509,"real_id":1972387509,"message_type":"group","sender":{"user_id":763797223,"nickname":"‭","card":"","role":"owner"},"raw_message":"111","font":14,"sub_type":"normal","message":[{"type":"text","data":{"text":"111"}}],"message_format":"array","post_type":"message","group_id":928119404} 
2024-10-12 08:30:12 [ERROR] 北部(2768885004) | 发生错误 Error: Recall failed
    at DeleteMsg._handle (file:///D:/ProgramFiles/NapCat/NapCatQQ/napcat.mjs:31142:13)
    at DeleteMsg.handle (file:///D:/ProgramFiles/NapCat/NapCatQQ/napcat.mjs:30606:34)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async OB11PassiveHttpAdapter.handleRequest (file:///D:/ProgramFiles/NapCat/NapCatQQ/napcat.mjs:13414:24) 
2024-10-12 08:30:13 [INFO] 北部(2768885004) | 发送 -> 群聊 [机器人测试(928119404)] [北部(2768885004)] @‭ (763797223) 	 未成功登录！可尝试重新输入指令！
 ... 
2024-10-12 08:30:14 [DEBUG] 北部(2768885004) | 收到新消息 RawMessage {"msgId":"7498896992117403087","msgRandom":"2834054","msgSeq":"20942","cntSeq":"0","chatType":2,"msgType":2,"subMsgType":1,"sendType":1,"senderUid":"u_AW1mPxO2BR1MSh5Fb4Mfqg","peerUid":"928119404","channelId":"","guildId":"7498896992117403086","guildCode":"0","fromUid":"0","fromAppid":"0","msgTime":"1728693013","msgMeta":{},"sendStatus":2,"sendRemarkName":"","sendMemberName":"","sendNickName":"北部","guildName":"","channelName":"","elements":[{"elementType":1,"elementId":"7424679955851830445","elementGroupId":0,"extBufForUI":{},"textElement":{"content":"@‭","atType":2,"atUid":"763797223","atTinyId":"0","atNtUid":"u_1ic89cfIimEMDkMQ8obg_w","subElementType":0,"atChannelId":"0","linkInfo":null,"atRoleId":"0","atRoleColor":0,"atRoleName":"","needNotify":0},"faceElement":null,"marketFaceElement":null,"replyElement":null,"picElement":null,"pttElement":null,"videoElement":null,"grayTipElement":null,"arkElement":null,"fileElement":null,"liveGiftElement":null,"markdownElement":null,"structLongMsgElement":null,"multiForwardMsgElement":null,"giphyElement":null,"walletElement":null,"inlineKeyboardElement":null,"textGiftElement":null,"calendarElement":null,"yoloGameResultElement":null,"avRecordElement":null,"structMsgElement":null,"faceBubbleElement":null,"shareLocationElement":null,"tofuRecordElement":null,"taskTopMsgElement":null,"recommendedMsgElement":null,"actionBarElement":null,"prologueMsgElement":null},{"elementType":1,"elementId":"7424679955851830446","elementGroupId":0,"extBufForUI":{},"textElement":{"content":"\t 未成功登录！可尝试重新输入指令！\r\nptuiCB('65','0','','0','二维码已失效。', '')^","atType":0,"atUid":"0","atTinyId":"0","atNtUid":"","subElementType":0,"atChannelId":"0","linkInfo":null,"atRoleId":"0","atRoleColor":0,"atRoleName":"","needNotify":0},"faceElement":null,"marketFaceElement":null,"replyElement":null,"picElement":null,"pttElement":null,"videoElement":null,"grayTipElement":null,"arkElement":null,"fileElement":null,"liveGiftElement":null,"markdownElement":null,"structLongMsgElement":null,"multiForwardMsgElement":null,"giphyElement":null,"walletElement":null,"inlineKeyboardElement":null,"textGiftElement":null,"calendarElement":null,"yoloGameResultElement":null,"avRecordElement":null,"structMsgElement":null,"faceBubbleElement":null,"shareLocationElement":null,"tofuRecordElement":null,"taskTopMsgElement":null,"recommendedMsgElement":null,"actionBarElement":null,"prologueMsgElement":null}],"records":[],"emojiLikesList":[],"commentCnt":"0","directMsgFlag":0,"directMsgMembers":[],"peerName":"机器人测试","freqLimitInfo":null,"editable":true,"avatarMeta":"","avatarPendant":"","feedId":"","roleId":"0","timeStamp":"0","clientIdentityInfo":null,"isImportMsg":false,"atType":2,"roleType":0,"fromChannelRoleInfo":{"roleId":"0","name":"","color":0},"fromGuildRoleInfo":{"roleId":"0","name":"","color":0},"levelRoleInfo":{"roleId":"0","name":"","color":0},"recallTime":"0","isOnlineMsg":false,"generalFlags":{},"clientSeq":"22007","fileGroupSize":null,"foldingInfo":null,"multiTransInfo":null,"senderUin":"2768885004","peerUin":"928119404","msgAttrs":{},"anonymousExtInfo":null,"nameType":0,"avatarFlag":0,"extInfoForUI":null,"personalMedal":null,"categoryManage":0,"msgEventInfo":null,"sourceType":0,"id":2016670976} 
2024-10-12 08:30:14 [DEBUG] 北部(2768885004) | 转化为 OB11Message {"self_id":2768885004,"user_id":2768885004,"time":1728693013,"message_id":2016670976,"message_seq":2016670976,"real_id":2016670976,"message_type":"group","sender":{"user_id":2768885004,"nickname":"北部","card":"","role":"admin"},"raw_message":"[CQ:at,qq=763797223]\t 未成功登录！可尝试重新输入指令！\r\nptuiCB('65','0','','0','二维码已失效。', '')^","font":14,"sub_type":"normal","message":[{"type":"at","data":{"qq":"763797223"}},{"type":"text","data":{"text":"\t 未成功登录！可尝试重新输入指令！\r\nptuiCB('65','0','','0','二维码已失效。', '')^"}}],"message_format":"array","post_type":"message_sent","message_sent_type":"self","group_id":928119404} 
2024-10-12 08:31:09 [INFO] 北部(2768885004) | 接收 <- 群聊 [机器人测试(928119404)] [‭(763797223)] 111 
2024-10-12 08:31:09 [DEBUG] 北部(2768885004) | 收到新消息 RawMessage {"msgId":"7424679990451623011","msgRandom":"3353796144","msgSeq":"20943","cntSeq":"0","chatType":2,"msgType":2,"subMsgType":1,"sendType":0,"senderUid":"u_1ic89cfIimEMDkMQ8obg_w","peerUid":"928119404","channelId":"","guildId":"","guildCode":"0","fromUid":"0","fromAppid":"0","msgTime":"1728693021","msgMeta":{},"sendStatus":2,"sendRemarkName":"","sendMemberName":"","sendNickName":"‭","guildName":"","channelName":"","elements":[{"elementType":1,"elementId":"7424679990451623010","elementGroupId":0,"extBufForUI":{},"textElement":{"content":"111","atType":0,"atUid":"0","atTinyId":"0","atNtUid":"","subElementType":0,"atChannelId":"0","linkInfo":null,"atRoleId":"0","atRoleColor":0,"atRoleName":"","needNotify":0},"faceElement":null,"marketFaceElement":null,"replyElement":null,"picElement":null,"pttElement":null,"videoElement":null,"grayTipElement":null,"arkElement":null,"fileElement":null,"liveGiftElement":null,"markdownElement":null,"structLongMsgElement":null,"multiForwardMsgElement":null,"giphyElement":null,"walletElement":null,"inlineKeyboardElement":null,"textGiftElement":null,"calendarElement":null,"yoloGameResultElement":null,"avRecordElement":null,"structMsgElement":null,"faceBubbleElement":null,"shareLocationElement":null,"tofuRecordElement":null,"taskTopMsgElement":null,"recommendedMsgElement":null,"actionBarElement":null,"prologueMsgElement":null}],"records":[],"emojiLikesList":[],"commentCnt":"0","directMsgFlag":0,"directMsgMembers":[],"peerName":"机器人测试","freqLimitInfo":null,"editable":false,"avatarMeta":"","avatarPendant":"","feedId":"","roleId":"0","timeStamp":"0","clientIdentityInfo":null,"isImportMsg":false,"atType":0,"roleType":0,"fromChannelRoleInfo":{"roleId":"0","name":"","color":0},"fromGuildRoleInfo":{"roleId":"0","name":"","color":0},"levelRoleInfo":{"roleId":"0","name":"","color":0},"recallTime":"0","isOnlineMsg":true,"generalFlags":{},"clientSeq":"0","fileGroupSize":null,"foldingInfo":null,"multiTransInfo":null,"senderUin":"763797223","peerUin":"928119404","msgAttrs":{},"anonymousExtInfo":null,"nameType":0,"avatarFlag":0,"extInfoForUI":null,"personalMedal":null,"categoryManage":0,"msgEventInfo":null,"sourceType":1,"id":266768234} 
2024-10-12 08:31:09 [DEBUG] 北部(2768885004) | 转化为 OB11Message {"self_id":2768885004,"user_id":763797223,"time":1728693021,"message_id":266768234,"message_seq":266768234,"real_id":266768234,"message_type":"group","sender":{"user_id":763797223,"nickname":"‭","card":"","role":"owner"},"raw_message":"111","font":14,"sub_type":"normal","message":[{"type":"text","data":{"text":"111"}}],"message_format":"array","post_type":"message","group_id":928119404} 
2024-10-12 08:31:09 [INFO] 北部(2768885004) | 接收 <- 群聊 [机器人测试(928119404)] [‭(763797223)] 222 
2024-10-12 08:31:09 [DEBUG] 北部(2768885004) | 收到新消息 RawMessage {"msgId":"7424680193713218609","msgRandom":"3262160857","msgSeq":"20944","cntSeq":"0","chatType":2,"msgType":2,"subMsgType":1,"sendType":0,"senderUid":"u_1ic89cfIimEMDkMQ8obg_w","peerUid":"928119404","channelId":"","guildId":"","guildCode":"0","fromUid":"0","fromAppid":"0","msgTime":"1728693023","msgMeta":{},"sendStatus":2,"sendRemarkName":"","sendMemberName":"","sendNickName":"‭","guildName":"","channelName":"","elements":[{"elementType":1,"elementId":"7424680193713218608","elementGroupId":0,"extBufForUI":{},"textElement":{"content":"222","atType":0,"atUid":"0","atTinyId":"0","atNtUid":"","subElementType":0,"atChannelId":"0","linkInfo":null,"atRoleId":"0","atRoleColor":0,"atRoleName":"","needNotify":0},"faceElement":null,"marketFaceElement":null,"replyElement":null,"picElement":null,"pttElement":null,"videoElement":null,"grayTipElement":null,"arkElement":null,"fileElement":null,"liveGiftElement":null,"markdownElement":null,"structLongMsgElement":null,"multiForwardMsgElement":null,"giphyElement":null,"walletElement":null,"inlineKeyboardElement":null,"textGiftElement":null,"calendarElement":null,"yoloGameResultElement":null,"avRecordElement":null,"structMsgElement":null,"faceBubbleElement":null,"shareLocationElement":null,"tofuRecordElement":null,"taskTopMsgElement":null,"recommendedMsgElement":null,"actionBarElement":null,"prologueMsgElement":null}],"records":[],"emojiLikesList":[],"commentCnt":"0","directMsgFlag":0,"directMsgMembers":[],"peerName":"机器人测试","freqLimitInfo":null,"editable":false,"avatarMeta":"","avatarPendant":"","feedId":"","roleId":"0","timeStamp":"0","clientIdentityInfo":null,"isImportMsg":false,"atType":0,"roleType":0,"fromChannelRoleInfo":{"roleId":"0","name":"","color":0},"fromGuildRoleInfo":{"roleId":"0","name":"","color":0},"levelRoleInfo":{"roleId":"0","name":"","color":0},"recallTime":"0","isOnlineMsg":true,"generalFlags":{},"clientSeq":"0","fileGroupSize":null,"foldingInfo":null,"multiTransInfo":null,"senderUin":"763797223","peerUin":"928119404","msgAttrs":{},"anonymousExtInfo":null,"nameType":0,"avatarFlag":0,"extInfoForUI":null,"personalMedal":null,"categoryManage":0,"msgEventInfo":null,"sourceType":1,"id":287877460} 
2024-10-12 08:31:09 [DEBUG] 北部(2768885004) | 转化为 OB11Message {"self_id":2768885004,"user_id":763797223,"time":1728693023,"message_id":287877460,"message_seq":287877460,"real_id":287877460,"message_type":"group","sender":{"user_id":763797223,"nickname":"‭","card":"","role":"owner"},"raw_message":"222","font":14,"sub_type":"normal","message":[{"type":"text","data":{"text":"222"}}],"message_format":"array","post_type":"message","group_id":928119404} 
2024-10-12 08:31:33 [INFO] 北部(2768885004) | [Native] 群消息撤回 Peer: 928119404 / MsgSeq:20940 
2024-10-12 08:31:33 [INFO] 北部(2768885004) | 发送 -> 群聊 [机器人测试(928119404)] [北部(2768885004)] @‭ (763797223) 	 未成功登录！可尝试重新输入指令！
 ... 

------------------------
新消息事件HTTP上报失败的CMD命令行日志
2024-10-12 08:32:30 [[32mINFO[39m] 北部(2768885004) | 接收 <- 群聊 [机器人测试(928119404)] [‭(763797223)] 666666666
2024-10-12 08:33:32 [[32mINFO[39m] 北部(2768885004) | [Native] 群消息撤回 Peer: 928119404 / MsgSeq:20945
2024-10-12 08:34:34 [[91mERROR[39m] 北部(2768885004) | [OneBot] [Http Client] 新消息事件HTTP上报失败 TypeError: fetch failed
    at node:internal/deps/undici/undici:12502:13
2024-10-12 08:34:36 [[91mERROR[39m] 北部(2768885004) | [OneBot] [Http Client] 新消息事件HTTP上报失败 TypeError: fetch failed
    at node:internal/deps/undici/undici:12502:13
2024-10-12 08:34:39 [[91mERROR[39m] 北部(2768885004) | [OneBot] [Http Client] 新消息事件HTTP上报失败 TypeError: fetch failed
    at node:internal/deps/undici/undici:12502:13
2024-10-12 08:35:15 [[91mERROR[39m] 北部(2768885004) | [OneBot] [Http Client] 新消息事件HTTP上报失败 TypeError: fetch failed
----------------------------------
新消息事件HTTP上报失败的logs文件夹日志
2024-10-12 08:32:30 [DEBUG] 北部(2768885004) | 转化为 OB11Message {"self_id":2768885004,"user_id":763797223,"time":1728693149,"message_id":196737751,"message_seq":196737751,"real_id":196737751,"message_type":"group","sender":{"user_id":763797223,"nickname":"‭","card":"","role":"owner"},"raw_message":"666666666","font":14,"sub_type":"normal","message":[{"type":"text","data":{"text":"666666666"}}],"message_format":"array","post_type":"message","group_id":928119404} 
2024-10-12 08:33:32 [INFO] 北部(2768885004) | [Native] 群消息撤回 Peer: 928119404 / MsgSeq:20945 
2024-10-12 08:34:34 [ERROR] 北部(2768885004) | [OneBot] [Http Client] 新消息事件HTTP上报失败 TypeError: fetch failed
    at node:internal/deps/undici/undici:12502:13 
2024-10-12 08:34:36 [ERROR] 北部(2768885004) | [OneBot] [Http Client] 新消息事件HTTP上报失败 TypeError: fetch failed
    at node:internal/deps/undici/undici:12502:13 
2024-10-12 08:34:39 [ERROR] 北部(2768885004) | [OneBot] [Http Client] 新消息事件HTTP上报失败 TypeError: fetch failed
    at node:internal/deps/undici/undici:12502:13 
2024-10-12 08:35:15 [ERROR] 北部(2768885004) | [OneBot] [Http Client] 新消息事件HTTP上报失败 TypeError: fetch failed
    at node:internal/deps/undici/undici:12502:13 
2024-10-12 08:36:10 [ERROR] 北部(2768885004) | [OneBot] [Http Client] 新消息事件HTTP上报失败 TypeError: fetch failed
    at node:internal/deps/undici/undici:12502:13 
2024-10-12 08:36:10 [ERROR] 北部(2768885004) | [OneBot] [Http Client] 新消息事件HTTP上报失败 TypeError: fetch failed
    at node:internal/deps/undici/undici:12502:13 
2024-10-12 08:36:34 [ERROR] 北部(2768885004) | [OneBot] [Http Client] 新消息事件HTTP上报失败 TypeError: fetch failed
    at node:internal/deps/undici/undici:12502:13 
2024-10-12 08:36:35 [ERROR] 北部(2768885004) | [OneBot] [Http Client] 新消息事件HTTP上报失败 TypeError: fetch failed
    at node:internal/deps/undici/undici:12502:13 
2024-10-12 08:37:13 [ERROR] 北部(2768885004) | [OneBot] [Http Client] 新消息事件HTTP上报失败 TypeError: fetch failed
    at node:internal/deps/undici/undici:12502:13 
2024-10-12 08:37:13 [ERROR] 北部(2768885004) | [OneBot] [Http Client] 新消息事件HTTP上报失败 TypeError: fetch failed
```

**Comment by MliKiowa** [comment]
上报失败是自己问题 recall撤回失败很正常 客户端有时候都不能撤回某些消息

**Comment by MliKiowa** [comment]
由于没有跟进close
