### ISSUE TITLE
[BUG] 希望能够跳过异常图片而非抛出错误

### ISSUE THREAD

**Issue by EvolvedGhost** [NapNeko/NapCatQQ#462]
### 系统版本

Debian GNU/Linux 12

### QQNT 版本

我不道啊，跑的Docker，mlikiowa/napcat-docker:latest（3.1.3）

### NapCat 版本

3.1.3

### OneBot 客户端

Overflow 1.0.0

### 发生了什么?

直接抛出了错误

### 如何复现

以Base64形式上传异常图片

### 期望的结果?

和Mirai、Shamrock、Lagrange等一样，越过错误的图片发送剩余的信息，而不是直接抛出错误，目前很多插件并没有严格判断图片是否存在，并且一些API也并不够稳定

大概看了下判断函数是lookup，如果既然能判断出来应该也可以直接剔除吧？
```
	/**
	 * Return size information based on an Uint8Array
	 *
	 * @param {Uint8Array} input
	 * @param {String} filepath
	 * @returns {Object}
	 */
	function lookup(input, filepath) {
	    // detect the file type.. don't rely on the extension
	    const type = (0, detector_1.detector)(input);
	    if (typeof type !== 'undefined') {
	        if (globalOptions.disabledTypes.indexOf(type) > -1) {
	            throw new TypeError('disabled file type: ' + type);
	        }
	        // find an appropriate handler for this file type
	        if (type in index_1.typeHandlers) {
	            const size = index_1.typeHandlers[type].calculate(input, filepath);
	            if (size !== undefined) {
	                size.type = size.type ?? type;
	                return size;
	            }
	        }
	    }
	    // throw up, if we don't understand the file
	    throw new TypeError('unsupported file type: ' + type + ' (file: ' + filepath + ')');
	}
```

### NapCat 运行日志

```shell
TypeError: unsupported file type: undefined (file: /root/.config/QQ/NapCat/temp/4db2df10-fde5-4bf4-91e0-48fab475b6c5)
    at lookup (file:///app/napcat/napcat.mjs:5219:12)
    at file:///app/napcat/napcat.mjs:5285:64, retJson={"status":"failed","retcode":1200,"data":null,"message":"TypeError: unsupported file type: undefined (file: /root/.config/QQ/NapCat/temp/4db2df10-fde5-4bf4-91e0-48fab475b6c5)\n    at lookup (file:///app/napcat/napcat.mjs:5219:12)\n    at file:///app/napcat/napcat.mjs:5285:64","wording":"TypeError: unsupported file type: undefined (file: /root/.config/QQ/NapCat/temp/4db2df10-fde5-4bf4-91e0-48fab475b6c5)\n    at lookup (file:///app/napcat/napcat.mjs:5219:12)\n    at file:///app/napcat/napcat.mjs:5285:64","echo":145}
```
```


### OneBot 客户端运行日志

```shell
2024-10-23 16:56:29 W/Onebot: 请求失败: [send_group_forward_msg] 请求失败: app=NapCat.Onebot v3.1.3, message=TypeError: unsupported file type: undefined (file: /root/.config/QQ/NapCat/temp/4db2df10-fde5-4bf4-91e0-48fab475b6c5)
```
```

**Comment by MliKiowa** [comment]
这个本身就是错误的不完整消息 发出来没意义 reject是合理的 不管其余框架 如何实现 抛出拒绝是合理的

**Comment by EvolvedGhost** [comment]
> 这个本身就是错误的不完整消息 发出来没意义 reject是合理的 不管其余框架 如何实现 抛出拒绝是合理的

好的，主要是同样的逻辑在Lagrange和老mirai上都是正常的，napcat直接拒绝发送，所以我才问问

**Comment by MliKiowa** [comment]
> > 这个本身就是错误的不完整消息 发出来没意义 reject是合理的 不管其余框架 如何实现 抛出拒绝是合理的
> 
> 好的，主要是同样的逻辑在Lagrange和老mirai上都是正常的，napcat直接拒绝发送，所以我才问问

图片如果其余能发 nc不能发这种问题可以提

如果是插件发送了错误图片 应该给插件提issue 而不是协议端

**Comment by EvolvedGhost** [comment]
> > > 这个本身就是错误的不完整消息 发出来没意义 reject是合理的 不管其余框架 如何实现 抛出拒绝是合理的
> > 
> > 
> > 好的，主要是同样的逻辑在Lagrange和老mirai上都是正常的，napcat直接拒绝发送，所以我才问问
> 
> 图片如果其余能发 nc不能发这种问题可以提
> 
> 如果是插件发送了错误图片 应该给插件提issue 而不是协议端

我知道，但是几乎所有插件都会有这种不判断文件信息直接发送的问题，那么很多插件可能都需要再加一套判断逻辑（特别是mirai那边的），而协议端这边因为不管是lagrange、shamrock还是更老的mirai、gocqhttp都能直接越过错误图片或者强制发送，所以以前的开发者并不会认为这是个问题，我只是觉得协议端之间是不是应该保持特性一致，既然协议端可能解决不了的话我看看能不能去Overflow交个PR，我不是很指望很多几年没更新的插件能有人维护issue……
