### ISSUE TITLE
[BUG] 无法发送网络图片

### ISSUE THREAD

**Issue by MQMQgo** [NapNeko/NapCatQQ#471]
### 系统版本

ubuntu22.04

### QQNT 版本

napcat docker带的

### NapCat 版本

v3.3.12

### OneBot 客户端

koishi 4.18.0 

### 发生了什么?

无法正常发送网络图片：发送图片时当图片地址为URL时报错显示 文件下载失败 未知文件类型

### 如何复现

发送图片时图片地址填URL

### 期望的结果?

发送图片

### NapCat 运行日志

```shell
2024-10-28 11:19:22 [DEBUG] 昵称(QQ号) | [OneBot] [WebSocket Client] 收到正向Websocket消息 {"action":"send_group_msg","params":{"group_id":群号,"message":[{"type":"image","data":{"file":["https://g.gtimg.cn/music/photo_new/T053XD01002q0rVs2mzaXv.png"],"cache":0}}]},"echo":20} 
2024-10-28 11:19:22 [ERROR] 昵称(QQ号) | 文件下载失败 未知文件类型 
2024-10-28 11:19:22 [ERROR] 昵称(QQ号) | 发生错误 Error: 文件下载失败未知文件类型
    at OneBotMsgApi.handleOb11FileLikeMessage (file:///app/napcat/napcat.mjs:28431:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Object.image (file:///app/napcat/napcat.mjs:28106:10)
    at async Promise.all (index 0)
    at async OneBotMsgApi.createSendElements (file:///app/napcat/napcat.mjs:28373:17)
    at async SendGroupMsg._handle (file:///app/napcat/napcat.mjs:35149:52)
    at async SendGroupMsg.websocketHandle (file:///app/napcat/napcat.mjs:35039:23)
    at async OB11ActiveWebSocketAdapter.handleMessage (file:///app/napcat/napcat.mjs:20166:21) 
```

### OneBot 客户端运行日志

```shell
2024-10-28 11:19:22 [W] bot Error: Error with request send_group_msg, args: {"group_id":801755587,"message":[{"type":"image","data":{"file":["https://g.gtimg.cn/music/photo_new/T053XD01002q0rVs2mzaXv.png"],"cache":0}}]}, retcode: 1200
                            at _Internal._get (/koishi/node_modules/koishi-plugin-adapter-onebot/lib/index.js:119:11)
                            at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
                            at async _Internal.<computed> [as sendGroupMsg] (/koishi/node_modules/koishi-plugin-adapter-onebot/lib/index.js:162:20)
                            at async OneBotMessageEncoder.flush (/koishi/node_modules/koishi-plugin-adapter-onebot/lib/index.js:761:330)
                            at async OneBotMessageEncoder.send (/koishi/node_modules/@satorijs/core/lib/index.cjs:620:5)
                            at async Proxy.sendMessage (/koishi/node_modules/@satorijs/core/lib/index.cjs:355:22)
                            at async Proxy.broadcast (/koishi/node_modules/@koishijs/core/lib/index.cjs:2262:49)
                            at async _Command.eval (eval at <anonymous> (/koishi/node_modules/koishi-plugin-blockly-null/lib/index.js:197:32), <anonymous>:12:5)
                            at async Array.<anonymous> (/koishi/node_modules/@koishijs/core/lib/index.cjs:1078:14)
                            at async _Command.execute (/koishi/node_modules/@koishijs/core/lib/index.cjs:1092:22)
```

**Comment by MliKiowa** [comment]
["https://g.gtimg.cn/music/photo_new/T053XD01002q0rVs2mzaXv.png"] 改成 "https://g.gtimg.cn/music/photo_new/T053XD01002q0rVs2mzaXv.png"

**Comment by MliKiowa** [comment]
napcat无问题 出现此问题为插件或者ob适配器问题
