### ISSUE TITLE
[BUG] 调用 mark_msg_as_read 时，报错：缺少参数 group_id 或 user_id

### ISSUE THREAD

**Issue by azqmdqbl** [NapNeko/NapCatQQ#509]
### 系统版本

Ubuntu 22.04.2

### QQNT 版本

3.2.13-29456

### NapCat 版本

3.6.9

### OneBot 客户端

zerobot

### 发生了什么?

没有头绪

### 如何复现

运行napcat和bot就会出现

### 期望的结果?

运行正常

### NapCat 运行日志

```shell
发生错误 Error: 缺少参数 group_id 或 user_id                                                                                         at GoCQHTTPMarkMsgAsRead.getPeer (file:///opt/QQ/resources/app/app_launcher/napcat/napcat.mjs:36584:13)                                                                         at GoCQHTTPMarkMsgAsRead._handle (file:///opt/QQ/resources/app/app_launcher/napcat/napcat.mjs:36589:67)                                                                         at GoCQHTTPMarkMsgAsRead.websocketHandle (file:///opt/QQ/resources/app/app_launcher/napcat/napcat.mjs:35547:34)                                                                 at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
at async OB11PassiveWebSocketAdapter.handleMessage (file:///opt/QQ/resources/app/app_launcher/napcat/napcat.mjs:21579:21)
```

### OneBot 客户端运行日志

```shell
ERRO[0123] [api] 调用 mark_msg_as_read 时出现错误, 返回值: 1200 , 信息:  解释: Error: 缺少参数 group_id 或 user_id                                                                  at GoCQHTTPMarkMsgAsRead.getPeer (file:///opt/QQ/resources/app/app_launcher/napcat/napcat.mjs:36584:13)                                                                         at GoCQHTTPMarkMsgAsRead._handle (file:///opt/QQ/resources/app/app_launcher/napcat/napcat.mjs:36589:67)                                                                         at GoCQHTTPMarkMsgAsRead.websocketHandle (file:///opt/QQ/resources/app/app_launcher/napcat/napcat.mjs:35547:34)                                                                 at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
at async OB11PassiveWebSocketAdapter.handleMessage (file:///opt/QQ/resources/app/app_launcher/napcat/napcat.mjs:21579:21)
```

**Comment by MliKiowa** [comment]
接口实现无法完美达到标准实现 未来考虑移除本接口 作为扩展

**Comment by MliKiowa** [comment]
下个版本兼容标准实现 但是行为不是单条消息已读 消息对应的会话设置全部已读
