### ISSUE TITLE
[BUG] 发送转发消息至群聊失败

### ISSUE THREAD

**Issue by manipEgo** [NapNeko/NapCatQQ#554]
### 系统版本

`Linux version 6.1.0-27-amd64 (debian-kernel@lists.debian.org) (gcc-12 (Debian 12.2.0-14) 12.2.0, GNU ld (GNU Binutils for Debian) 2.40) #1 SMP PREEMPT_DYNAMIC Debian 6.1.115-1 (2024-11-01)`

### QQNT 版本

`linuxqq/now 3.2.13-29456 amd64`

### NapCat 版本

`4.1.12`

### OneBot 客户端

`koishi-plugin-adapter-onebot 6.7.4`

### 发生了什么?

发送转发消息至群聊失败，错误信息见下方运行日志。

转发消息内容为多条单个气泡内的 图片+文字 混合消息。

同样内容在私聊窗口内可以正常发送，只在群聊窗口内会报错，不限于某个特定群聊。测试发现仅当转发消息内包含特定消息时会无法发送。详细列于复现部分。

### 如何复现

**我的 NapCat 部署环境为[第三方 Docker 容器](https://github.com/NapNeko/NapCat-Docker)**。因为错误似乎是由 NapCat 产生故提交 Issue 至这个仓库。抱歉没有先尝试在官方文档环境下复现。

我的对接客户端为 `Koishi`，连接方式为 `ws`，产生错误的插件为 [SVE 卡查插件](https://github.com/manipEgo/koishi-plugin-sve-helper?tab=readme-ov-file)。

---

一个可以在群聊窗口内触发错误的查询指令为：`sve 叮当天使`。该指令的响应内包含推测会导致发送失败的一条消息，其内容为：

> ![叮当天使的卡图，可在此处查看](https://shadowverse-evolve.com/wordpress/wp-content/images/cardlist/BP01/bp01_159.png)
> 叮当天使
> 《进化》《消费2》：使这张卡进化。
> 【守护】
> 《谢幕曲》抽取1张卡。

一个在群聊窗口内响应正常的查询指令为：`sve`。

### 期望的结果?

期望 NapCat 正常发送转发消息，形式与上述响应正常的内容一致。

### NapCat 运行日志

```shell
time="2024-11-20T20:16:30+08:00" level=warning msg="/Compose/NapCatQQ/NapCatQQ.yml: the attribute `version` is obsolete, it will be ignored, please remove it to avoid potential confusion"
napcat  | usermod: no changes
napcat  | usermod: no changes
napcat  | [preload] succeeded. /opt/QQ/resources/app/major.node
napcat  | [preload] succeeded. /opt/QQ/resources/app/major.node
napcat  | [33:1120/201623.439145:ERROR:bus.cc(407)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
napcat  | [33:1120/201623.572820:ERROR:bus.cc(407)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
napcat  | [33:1120/201623.572871:ERROR:bus.cc(407)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
napcat  | [33:1120/201623.573817:ERROR:bus.cc(407)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix")
napcat  | [33:1120/201623.573838:ERROR:bus.cc(407)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix")
napcat  | [33:1120/201623.573844:ERROR:bus.cc(407)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix")
napcat  | [33:1120/201623.573849:ERROR:bus.cc(407)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix")
napcat  | [65:1120/201623.653311:ERROR:gl_surface_egl.cc(302)] No suitable EGL configs found.
napcat  | [65:1120/201623.654351:ERROR:gl_context_egl.cc(160)] eglGetConfigAttrib failed with error EGL_BAD_CONFIG
napcat  | [65:1120/201623.654478:ERROR:gl_surface_egl.cc(302)] No suitable EGL configs found.
napcat  | [65:1120/201623.654545:ERROR:gl_surface_egl.cc(1040)] eglCreatePbufferSurface failed with error EGL_BAD_CONFIG
napcat  | [65:1120/201623.654608:ERROR:gpu_info_collector.cc(86)] gl::GLContext::CreateOffscreenGLSurface failed
napcat  | [65:1120/201623.654663:ERROR:gpu_info_collector.cc(584)] Could not create surface for info collection.
napcat  | [65:1120/201623.654727:ERROR:gpu_init.cc(107)] CollectGraphicsInfo failed.
napcat  | [65:1120/201623.656163:ERROR:viz_main_impl.cc(166)] Exiting GPU process due to errors during initialization
napcat  | [107:1120/201623.754656:ERROR:gl_surface_egl.cc(302)] No suitable EGL configs found.
napcat  | [107:1120/201623.754755:ERROR:gl_context_egl.cc(160)] eglGetConfigAttrib failed with error EGL_BAD_CONFIG
napcat  | [107:1120/201623.754867:ERROR:gl_surface_egl.cc(302)] No suitable EGL configs found.
napcat  | [107:1120/201623.754914:ERROR:gl_surface_egl.cc(1040)] eglCreatePbufferSurface failed with error EGL_BAD_CONFIG
napcat  | [107:1120/201623.754960:ERROR:gpu_info_collector.cc(86)] gl::GLContext::CreateOffscreenGLSurface failed
napcat  | [107:1120/201623.754999:ERROR:gpu_info_collector.cc(584)] Could not create surface for info collection.
napcat  | [107:1120/201623.755043:ERROR:gpu_init.cc(107)] CollectGraphicsInfo failed.
napcat  | [107:1120/201623.756391:ERROR:viz_main_impl.cc(166)] Exiting GPU process due to errors during initialization
napcat  | NapCat Shell App Loading...
napcat  | 11-20 20:16:23 [info] [NapCat] [Core] NapCat.Core Version: 4.1.12
napcat  | 11-20 20:16:23 [info] [NapCat] [WebUi] Current WebUi is running at http://0.0.0.0:6099
napcat  | 11-20 20:16:23 [info] [NapCat] [WebUi] Login Token is 
napcat  | 11-20 20:16:23 [info] [NapCat] [WebUi] WebUi User  Panel Url: http://0.0.0.0:6099/webui?token=
napcat  | 11-20 20:16:23 [info] [NapCat] [WebUi] WebUi Local Panel Url: http://127.0.0.1:6099/webui?token=
napcat  | 11-20 20:16:23 [info] 核心登录服务连接成功!
napcat  | 11-20 20:16:23 [info] 正在快速登录  
napcat  | [166:1120/201623.910680:ERROR:gl_surface_egl.cc(302)] No suitable EGL configs found.
napcat  | [166:1120/201623.910757:ERROR:gl_context_egl.cc(160)] eglGetConfigAttrib failed with error EGL_BAD_CONFIG
napcat  | [166:1120/201623.910835:ERROR:gl_surface_egl.cc(302)] No suitable EGL configs found.
napcat  | [166:1120/201623.910870:ERROR:gl_surface_egl.cc(1040)] eglCreatePbufferSurface failed with error EGL_BAD_CONFIG
napcat  | [166:1120/201623.910905:ERROR:gpu_info_collector.cc(86)] gl::GLContext::CreateOffscreenGLSurface failed
napcat  | [166:1120/201623.910936:ERROR:gpu_info_collector.cc(584)] Could not create surface for info collection.
napcat  | [166:1120/201623.910970:ERROR:gpu_init.cc(107)] CollectGraphicsInfo failed.
napcat  | [166:1120/201623.911886:ERROR:viz_main_impl.cc(166)] Exiting GPU process due to errors during initialization
napcat  | 11-20 20:16:24 [info] [NapCat] [WebUi] WebUi Publish Panel Url: http://209.9.201.203:6099/webui/?token=
napcat  | linux-bugly: init bugly ...
napcat  | InitBuglyManager
napcat  | SetLogger
napcat  | fatalSetup
napcat  | GetDllPath: 33
napcat  | pub_key_path: /opt/QQ/resources/app/pub.key
napcat  | [BuglyManager.cpp][InitBuglyManager][212]InitBuglyManager path: /app/.config/QQ/crash_files/
napcat  | BuglyManager/opt/QQ/resources/app/pub.key
napcat  | [BuglyService.cpp][registBugly][589]set signal stack
napcat  | [BuglyService.cpp][registSignalHandler][520]regist native handler
napcat  | registBugly/opt/QQ/resources/app/pub.key
napcat  | [BuglyService.cpp][setParam][618]setParam, key:appVersion, value:3.2.13-29456..
napcat  | setParam/opt/QQ/resources/app/pub.key
napcat  | StartWithOptions s/opt/QQ/resources/app/pub.key
napcat  | StartWithOptions e/opt/QQ/resources/app/pub.key
napcat  | PostDelayedTask s/opt/QQ/resources/app/pub.key
napcat  | PostDelayedTask e/opt/QQ/resources/app/pub.key
napcat  | linux-bugly: init bugly done.
napcat  | 11-20 20:16:25 [debug] 本账号数据/缓存目录： /app/.config/QQ/NapCat/data
napcat  | 11-20 20:16:25 [debug] [Core] [Config] 配置文件/app/napcat/config/napcat_.json加载 {"fileLog":true,"consoleLog":true,"fileLogLevel":"debug","consoleLogLevel":"info"}
napcat  | 11-20 20:16:25 [warn] [Core] [Packet] wsPacketClient 未配置服务器地址
napcat  | 11-20 20:16:25 [info] [Core] [Packet] 自动选择 NativePacketClient 作为后端
napcat  | 11-20 20:16:25 [info] [Notice] [OneBot11] [network] 配置加载
napcat  | HTTP服务: :3000, : 未启动
napcat  | WebSocket服务: :3001, : 已启动
napcat  | 
napcat  | 11-20 20:16:25 [info] [OneBot] [WebSocket Server] Server Started :::3001
napcat  | 11-20 20:16:33 [info] TCN | 接收 <- 群聊 [测试()] [()] /sve 叮当天使
napcat  | 11-20 20:16:34 [info] TCN | [Core] [Packet] 上传资源4个，失败0个
napcat  | 11-20 20:16:34 [info] TCN | 发送 -> 群聊 [测试()] [()] [卡片消息]
napcat  | [BuglyManager.cpp][UploadBugly][107]!!!in UploadBugly.
napcat  | [NativeCrashHandler.cpp][getCrashDetailBeanFromRecord][52]!!!! in NativeCrashHandler getCrashDetailBeanFromRecord, open file error!!!,dumpFilePath:/app/.config/QQ/crash_files/rqd_record.eup.
napcat  | [NativeCrashHandler.cpp][uploadCrashEvent][331]get null crashDetailBean, return!
napcat  | api call returning 0
napcat  | 11-20 20:16:44 [error] TCN | 发生错误 Error: 发送转发消息（res_id：65c57qOKpy2BxohNosqNLaOstr1nw9hBuy3l+xS2nJzqBPiMQsR5pHG7g00qMPeV 失败
napcat  |     at GoCQHTTPSendGroupForwardMsg._handle (file:///app/napcat/napcat.mjs:50494:15)
napcat  |     at async GoCQHTTPSendGroupForwardMsg.websocketHandle (file:///app/napcat/napcat.mjs:41923:23)
napcat  |     at async OB11PassiveWebSocketAdapter.handleMessage (file:///app/napcat/napcat.mjs:43041:21)
napcat  | 11-20 20:16:51 [info] TCN | 接收 <- 群聊 [测试()] [()] /sve 叮当天使
napcat  | 11-20 20:16:52 [info] TCN | [Core] [Packet] 上传资源4个，失败0个
napcat  | 11-20 20:16:52 [info] TCN | 发送 -> 群聊 [测试()] [()] [卡片消息]
napcat  | 11-20 20:17:02 [error] TCN | 发生错误 Error: 发送转发消息（res_id：5Xr4KzAKeno0qZ97i+7wccvbLPr165Oa1fBxC+33jKXFL2Gk8vc7Jf6n6OtizaqA 失败
napcat  |     at GoCQHTTPSendGroupForwardMsg._handle (file:///app/napcat/napcat.mjs:50494:15)
napcat  |     at async GoCQHTTPSendGroupForwardMsg.websocketHandle (file:///app/napcat/napcat.mjs:41923:23)
napcat  |     at async OB11PassiveWebSocketAdapter.handleMessage (file:///app/napcat/napcat.mjs:43041:21)
```

### OneBot 客户端运行日志

```shell
N/A
```

**Comment by pk5ls20** [comment]
1. 升级最新版NapCat
2. 重新复现并上传完整日志

**Comment by manipEgo** [comment]
> 1. 升级最新版NapCat
> 2. 重新复现并上传完整日志

你好，感谢回复！

NapCat 版本为 `4.1.12`，应该已为本仓库内 release 最新

从重启至复现后完整日志已更新上传

**Comment by pk5ls20** [comment]
经过本地对比测试，怀疑是合并转发中的图片存在问题，触发了拦截机制，导致无法发送。
如确有问题，请重新打开此 issue。
