### ISSUE TITLE
[BUG] 图片较多时构建合并转发消息易失败

### ISSUE THREAD

**Issue by Elan114514** [NapNeko/NapCatQQ#564]
### 系统版本

 Windows Server 2016

### QQNT 版本

9.9.16-29740

### NapCat 版本

4.1.18

### OneBot 客户端

Nonebot2 2.3.2

### 发生了什么?

构建合并转发消息时，如果内容中的图片较多（3--5张），则构建合并转发消息很可能会失败，并抛出错误：发生错误 Error: 发送伪造合并转发消息失败: ConnectTimeoutError: Connect Timeout Error
    at onConnectTimeout (node:internal/deps/undici/undici:6635:28)
    at node:internal/deps/undici/undici:6587:50
    at Immediate._onImmediate (node:internal/deps/undici/undici:6617:37)
    at process.processImmediate (node:internal/timers:478:21)
    at GoCQHTTPSendForwardMsg._handle (file:///E:/Napcat/Shell/NapCat/napcat.mjs:50668:15)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at runNextTicks (node:internal/process/task_queues:64:3)
    at process.processImmediate (node:internal/timers:449:9)
    at async GoCQHTTPSendForwardMsg.websocketHandle (file:///E:/Napcat/Shell/NapCat/napcat.mjs:42107:23)
    at async OB11ActiveWebSocketAdapter.handleMessage (file:///E:/Napcat/Shell/NapCat/napcat.mjs:42259:21)

这种情况在当图片由网络请求得到时由为明显。使用本地图片时，也有较大概率发生该错误。

补充：回滚至napcat4.0.3，发现可以正常发送合并转发消息。再次更新至最新版4.1.18，再次出现该错误 。
先后在服务器、本地电脑尝试，均符合此种情况，排除是网络环境不稳定导致。

### 如何复现

1.构建一条包含多图的合并转发消息（3--5张图片）
2.napcat和onebot客户端均抛出错误：发生错误 Error: 发送伪造合并转发消息失败: ConnectTimeoutError: Connect Timeout Error
    at onConnectTimeout (node:internal/deps/undici/undici:6635:28)
    at node:internal/deps/undici/undici:6587:50
    at Immediate._onImmediate (node:internal/deps/undici/undici:6617:37)
    at process.processImmediate (node:internal/timers:478:21)
    at GoCQHTTPSendForwardMsg._handle (file:///E:/Napcat/Shell/NapCat/napcat.mjs:50668:15)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at runNextTicks (node:internal/process/task_queues:64:3)
    at process.processImmediate (node:internal/timers:449:9)
    at async GoCQHTTPSendForwardMsg.websocketHandle (file:///E:/Napcat/Shell/NapCat/napcat.mjs:42107:23)
    at async OB11ActiveWebSocketAdapter.handleMessage (file:///E:/Napcat/Shell/NapCat/napcat.mjs:42259:21)

### 期望的结果?

可正常构建合并转发消息

### NapCat 运行日志

```shell
11-25 10:24:45 [info] | [Core] [Packet] 上传资源4个，失败4个
11-25 10:24:45 [error] | [Core] [Packet] 上传第1个资源失败：Error: sendCommand timed out after 20000 ms for HttpConn.0x6ff_501 with trace_id s642f29840fb27c2cfcd500554c3
    at Timeout._onTimeout (file:///C:/Users/Administrator/Desktop/NapCat/napcat.mjs:30236:16)
    at listOnTimeout (node:internal/timers:573:17)
    at process.processTimers (node:internal/timers:514:7)
11-25 10:24:45 [error] 仙贝（备用机#1） | [Core] [Packet] 上传第2个资源失败：Error: sendCommand timed out after 20000 ms for HttpConn.0x6ff_501 with trace_id s642f29840fb27c2cfcd500554c3
    at Timeout._onTimeout (file:///C:/Users/Administrator/Desktop/NapCat/napcat.mjs:30236:16)
    at listOnTimeout (node:internal/timers:573:17)
    at process.processTimers (node:internal/timers:514:7)
11-25 10:24:45 [error]  | [Core] [Packet] 上传第3个资源失败：Error: sendCommand timed out after 20000 ms for HttpConn.0x6ff_501 with trace_id s642f29840fb27c2cfcd500554c3
    at Timeout._onTimeout (file:///C:/Users/Administrator/Desktop/NapCat/napcat.mjs:30236:16)
    at listOnTimeout (node:internal/timers:573:17)
    at process.processTimers (node:internal/timers:514:7)
11-25 10:24:45 [error] 仙贝（备用机#1） | [Core] [Packet] 上传第4个资源失败：Error: sendCommand timed out after 20000 ms for HttpConn.0x6ff_501 with trace_id s642f29840fb27c2cfcd500554c3
    at Timeout._onTimeout (file:///C:/Users/Administrator/Desktop/NapCat/napcat.mjs:30236:16)
    at listOnTimeout (node:internal/timers:573:17)
    at process.processTimers (node:internal/timers:514:7)
11-25 10:25:05 [error] 仙贝（备用机#1） | 发生错误 Error: 发送伪造合并转发消息失败: Error: sendCommand timed out after 20000 ms for trpc.group.long_msg_interface.MsgService.SsoSendLongMsg with trace_id 18yi084124834409ca20f8414e786d26422912ad030801121a1218755f5745704933706d583657784f73646b5f3368355f62671800228a031f8b080000000000000a13dac7c2c5e15b9a5392e95b9c2eb491856b1d0b9723c7bbae9607bc420c4612a5f1e1ae059ec605b91166e115fec529d9f1c619a6f149e956b246d24f772c7b3eb7e1f9d4554f3b973f9d3defd9dca5cf67b53cd93df3c596b942db19393805582458148edd5831895ba3e3d8edd98c0637f7f7ef62b3607460f060a89ac6c8c120c020c1a4e596515252506ca5af5fa85798939f9eaf979ca7
    at Timeout._onTimeout (file:///C:/Users/Administrator/Desktop/NapCat/napcat.mjs:30236:16)
    at listOnTimeout (node:internal/timers:573:17)
    at process.processTimers (node:internal/timers:514:7)
    at GoCQHTTPSendForwardMsg._handle (file:///C:/Users/Administrator/Desktop/NapCat/napcat.mjs:50668:15)
    at async GoCQHTTPSendForwardMsg.websocketHandle (file:///C:/Users/Administrator/Desktop/NapCat/napcat.mjs:42107:23)
    at async OB11ActiveWebSocketAdapter.handleMessage (file:///C:/Users/Administrator/Desktop/NapCat/napcat.mjs:42259:21)
```

### OneBot 客户端运行日志

```shell
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\multiprocessing\spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\multiprocessing\spawn.py", line 129, in _main
    return self._bootstrap(parent_sentinel)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\multiprocessing\process.py", line 314, in _bootstrap
    self.run()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "E:\senbei310\lib\site-packages\nonebot_plugin_reboot\reloader.py", line 27, in _run
    _nb_run(*args, **kwargs)
  File "E:\senbei310\lib\site-packages\nonebot\__init__.py", line 335, in run
    get_driver().run(*args, **kwargs)
  File "E:\senbei310\lib\site-packages\nonebot\drivers\fastapi.py", line 186, in run
    uvicorn.run(
  File "E:\senbei310\lib\site-packages\uvicorn\main.py", line 587, in run
    server.run()
  File "E:\senbei310\lib\site-packages\uvicorn\server.py", line 62, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 636, in run_until_complete
    self.run_forever()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 603, in run_forever
    self._run_once()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 1909, in _run_once
    handle._run()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "E:\senbei310\lib\site-packages\nonebot\message.py", line 476, in check_and_run_matcher
    await _run_matcher(
> File "E:\senbei310\lib\site-packages\nonebot\message.py", line 428, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "E:\senbei310\lib\site-packages\nonebot\internal\matcher\matcher.py", line 850, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "E:\senbei310\lib\site-packages\nonebot\internal\matcher\matcher.py", line 825, in simple_run
    await handler(
  File "E:\senbei310\lib\site-packages\nonebot\dependencies\__init__.py", line 94, in __call__
    return await cast(Callable[..., Awaitable[R]], self.call)(**values)
  File "E:\mcbot\senbeibot\src\plugins\moyucal.py", line 322, in handle_first_receive
    await bot.send_forward_msg(
  File "E:\senbei310\lib\site-packages\nonebot\internal\adapter\bot.py", line 122, in call_api
    raise exception
  File "E:\senbei310\lib\site-packages\nonebot\internal\adapter\bot.py", line 97, in call_api
    result = await self.adapter._call_api(self, api, **data)
  File "E:\senbei310\lib\site-packages\nonebot\adapters\onebot\v11\adapter.py", line 147, in _call_api
    return handle_api_result(await self._result_store.fetch(seq, timeout))
  File "E:\senbei310\lib\site-packages\nonebot\adapters\onebot\v11\utils.py", line 58, in handle_api_result
    raise ActionFailed(**result)
nonebot.adapters.onebot.v11.exception.ActionFailed: ActionFailed(status='failed', retcode=1200, data=None, message='发送伪造合并转发消息失败: Error: read ECONNRESET\n    at TLSWrap.onStreamRead (node:internal/stream_base_commons:218:20)', wording='发送伪造合并转发消息失败: Error: read ECONNRESET\n    at TLSWrap.onStreamRead (node:internal/stream_base_commons:218:20)', echo='481')
```

**Comment by MliKiowa** [comment]
进入官方群来

**Comment by pk5ls20** [comment]
1. NapCat 4.1.18 + QQ 9.9.16-29456 未复现此问题
2. QQ似乎没有`9.9.15-29740`这个版本

**Comment by HadalFauna** [comment]
我也是从3.6.10更到4.1.21后出现了同样的问题，QQ一直是使用9.9.16-29456版本
然后我在这台机子上用QQNT客户端正常流程登录了一下bot账号再关掉，再用NapCat时就神奇地好了……如果你还是受这个问题困扰的话可以试试？

**Comment by Elan114514** [comment]
> 我也是从3.6.10更到4.1.21后出现了同样的问题，QQ一直是使用9.9.16-29456版本 然后我在这台机子上用QQNT客户端正常流程登录了一下bot账号再关掉，再用NapCat时就神奇地好了……如果你还是受这个问题困扰的话可以试试？

似乎没有显著效果x
