### ISSUE TITLE
[BUG] text 较多时发送合并转发消息失败

### ISSUE THREAD

**Issue by ForkKILLET** [NapNeko/NapCatQQ#568]
### 系统版本

NixOS 25.05beta710087.23e89b7da85c (Warbler)

### QQNT 版本

9

### NapCat 版本

4.1.6

### OneBot 客户端

Koishi v4.18.0

### 发生了什么?

消息段中 text 元素过多时，发送合并转发消息失败。

### 如何复现

发送失败的消息如下

[1.json](https://github.com/user-attachments/files/17922180/1.json)

### 期望的结果?

可以和 v2 一样正常发送这类合并转发消息。

### NapCat 运行日志

```shell
napcat  | 11-26 23:28:56 [info] WillBot | [Core] [Packet] 上传资源0个，失败0个
napcat  | 11-26 23:28:56 [info] WillBot | 发送 -> 群聊 [5d图书馆二群(960930385)] [(3825175885)] [卡片消息]
napcat  | 11-26 23:28:56 [error] WillBot | 发生错误 Error: 发送转发消息（res_id：5zUov1ZUII+qZrLQJZ+behW9ImpXZBERSwdGckPzfIF9kA7NL5cC9beDVb1uvUYH 失败
napcat  |     at GoCQHTTPSendGroupForwardMsg._handle (file:///app/napcat/napcat.mjs:50441:15)
napcat  |     at async GoCQHTTPSendGroupForwardMsg.websocketHandle (file:///app/napcat/napcat.mjs:50334:23)
napcat  |     at async OB11PassiveWebSocketAdapter.handleMessage (file:///app/napcat/napcat.mjs:36394:21)
```

### OneBot 客户端运行日志

```shell
willbot-1  | 2024-11-26 22:59:43 [W] session Error: Error with request send_group_forward_msg, args: {"group_id":960930385,"messages":[{"type":"node","data":{"name":"WillBot","uin":"3825175885","content":[{"type":"text","data":{"text":"在 z-lib.fm 找到 50 条符合 \"中国叙事学\" 的结果（第 1/8 页），用时 1.56 秒（已登录：ForkKILLET）"}},{"type":"text","data":{"text":"\n"}},{"type":"text","data":{"text":"\n"}},{"type":"text","data":{"text":"[#1]"}},{"type":"text","data":{"text":"\n"}},{"type":"text","data":{"text":" [标题] 小说写作：叙事技巧指南（第十版）（创意写作书系）"}},{"type":"text","data":{"text":"\n"}},{"type":"text","data":{"text":"[作者] 珍妮特·伯罗薇 & 伊丽莎白·斯塔基-弗伦奇"}},{"type":"text","data":{"text":"\n"}},{"type":"text","data":{"text":"[年份] 2021 [语言] Chinese"}},{"type":"text","data":{"text":"\n"}},{"type":"text","data":{"text":"[评分] ★★★★★ [质量] ★★★★★"}},{"type":"text","data":{"text":"\n"}},{"type":"text","data":{"text":"[详情] "}},{"type":"text","data":{"text":"（https://z-lib.fm/book/16652268/969cef/小说写作叙事技巧指南第十版创意写作书系.html）"}},{"type":"text","data":{"text":"\n"}},{"type":"text","data":{"text":"[大小] 652 KB [类型] epub [下载] "}},{"type":"text","data":{"text":"（https://z-lib.fm/dl/16652268/6282ef）"}},{"type":"text","data":{"text":"\n"}},{"type":"text","data":{"text":"\n"}},{"type":"text","data":{"text":"[#2]"}},{"type":"text","data":{"text":"\n"}},{"type":"text","data":{"text":" [标题] 故事与话语: 小说和电影的叙事结构"}},{"type":"text","data":{"text":"\n"}},{"type":"text","data":{"text":"[作者] 查特曼;  徐强"}},{"type":"text","data":{"text":"\n"}},{"type":"text","data":{"text":"[年份] 2013 [语言] Chinese"}},{"type":"text","data":{"text":"\n"}},{"type":"text","data":{"text":"[评分] ★★★★★ [质量] ☆"}},{"type":"text","data":{"text":"\n"}},{"type":"text","data":{"text":"[详情] "}},{"type":"text","data":{"text":"（https://z-lib.fm/book/5232905/959519/故事与话语-小说和电影的叙事结构.html）"}},{"type":"text","data":{"text":"\n"}},{"type":"text","data":{"text":"[大小] 24.06 MB [类型] pdf [下载]"}},{"type":"text","data":{"text":"（https://z-lib.fm/dl/5232905/1ecb86）"}},{"type":"text","data":{"text":"\n"}},{"type":"text","data":{"text":"\n"}},{"type":"text","data":{"text":"[#3]"}},{"type":"text","data":{"text":"\n"}},{"type":"text","data":{"text":" [标题] “读书的料”及其文化生产——当代农家子弟成长叙事研究"}},{"type":"text","data":{"text":"\n"}},{"type":"text","data":{"text":"[作者] 程猛"}},{"type":"text","data":{"text":"\n"}},{"type":"text","data":{"text":"[年份] 2018 [语言] Chinese"}},{"type":"text","data":{"text":"\n"}},{"type":"text","data":{"text":"[评分] ★★★★★ [质量] ★★★"}},{"type":"text","data":{"text":"\n"}},{"type":"text","data":{"text":"[详情] "}},{"type":"text","data":{"text":"（https://z-lib.fm/book/11971918/79842d/读书的料及其文化生产当代农家子弟成长叙事研究.html）"}},{"type":"text","data":{"text":"\n"}},{"type":"text","data":{"text":"[大小] 29.13 MB [类型] pdf [下载] "}},{"type":"text","data":{"text":"（https://z-lib.fm/dl/11971918/faec68）"}},{"type":"text","data":{"text":"\n"}},{"type":"text","data":{"text":"\n"}},{"type":"text","data":{"text":"[#4]"}},{"type":"text","data":{"text":"\n"}},{"type":"text","data":{"text":" [标题] 叙述学: 叙事理论导论"}},{"type":"text","data":{"text":"\n"}},{"type":"text","data":{"text":"[作者] 米克·巴尔（Mieke Bal）"}},{"type":"text","data":{"text":"\n"}},{"type":"text","data":{"text":"[年份] 2003 [语言] Chinese"}},{"type":"text","data":{"text":"\n"}},{"type":"text","data":{"text":"[评分] ☆ [质量] ☆"}},{"type":"text","data":{"text":"\n"}},{"type":"text","data":{"text":"[详情] "}},{"type":"text","data":{"text":"（https://z-lib.fm/book/5232907/03d377/叙述学-叙事理论导论.html）"}},{"type":"text","data":{"text":"\n"}},{"type":"text","data":{"text":"[大小] 3.79 MB [类型] pdf [下载] "}},{"type":"text","data":{"text":"（https://z-lib.fm/dl/5232907/ede9f8）"}},{"type":"text","data":{"text":"\n"}},{"type":"text","data":{"text":"\n"}},{"type":"text","data":{"text":"[#5]"}},{"type":"text","data":{"text":"\n"}},{"type":"text","data":{"text":" [标题] 叙事话语 新叙事话语: Figures III (Discours du récit): Nouveau discours du récit"}},{"type":"text","data":{"text":"\n"}},{"type":"text","data":{"text":"[作者] 热拉尔·热奈特"}},{"type":"text","data":{"text":"\n"}},{"type":"text","data":{"text":"[年份] 1990 [语言] Chinese"}},{"type":"text","data":{"text":"\n"}},{"type":"text","data":{"text":"[评分] ☆ [质量] ☆"}},{"type":"text","data":{"text":"\n"}},{"type":"text","data":{"text":"[详情] "}},{"type":"text","data":{"text":"（https://z-lib.fm/book/5987152/d657ee/叙事话语-新叙事话语-figures-iii-discours-du-récit-nouveau-discours-du-récit.html）"}},{"type":"text","data":{"text":"\n"}},{"type":"text","data":{"text":"[大小] 37.31 MB [类型] pdf [下载] "}},{"type":"text","data":{"text":"（https://z-lib.fm/dl/5987152/52bade）"}},{"type":"text","data":{"text":"\n"}},{"type":"text","data":{"text":"\n"}},{"type":"text","data":{"text":"[#6]"}},{"type":"text","data":{"text":"\n"}},{"type":"text","data":{"text":" [标题] 中国小说叙事模式的转变"}},{"type":"text","data":{"text":"\n"}},{"type":"text","data":{"text":"[作者] 陈平原"}},{"type":"text","data":{"text":"\n"}},{"type":"text","data":{"text":"[年份] 2003 [语言] Chinese"}},{"type":"text","data":{"text":"\n"}},{"type":"text","data":{"text":"[评分] ★★★★★ [质量] ★"}},{"type":"text","data":{"text":"\n"}},{"type":"text","data":{"text":"[详情] "}},{"type":"text","data":{"text":"（https://z-lib.fm/book/5420151/3ecf68/中国小说叙事模式的转变.html）"}},{"type":"text","data":{"text":"\n"}},{"type":"text","data":{"text":"[大小] 8.04 MB [类型] pdf [下载] "}},{"type":"text","data":{"text":"（https://z-lib.fm/dl/5420151/05a8cd）"}},{"type":"text","data":{"text":"\n"}},{"type":"text","data":{"text":"\n"}},{"type":"text","data":{"text":"[#7]"}},{"type":"text","data":{"text":"\n"}},{"type":"text","data":{"text":" [标题] “读书的料”及其文化生产——当代农家子弟成长叙事研究"}},{"type":"text","data":{"text":"\n"}},{"type":"text","data":{"text":"[作者] 程猛"}},{"type":"text","data":{"text":"\n"}},{"type":"text","data":{"text":"[年份] 2018 [语言] Chinese"}},{"type":"text","data":{"text":"\n"}},{"type":"text","data":{"text":"[评分] ★★★★★ [质量] ★★★"}},{"type":"text","data":{"text":"\n"}},{"type":"text","data":{"text":"[详情] "}},{"type":"text","data":{"text":"（https://z-lib.fm/book/18993686/3e7960/读书的料及其文化生产当代农家子弟成长叙事研究.html）"}},{"type":"text","data":{"text":"\n"}},{"type":"text","data":{"text":"[大小] 36.89 MB [类型] pdf [下载] "}},{"type":"text","data":{"text":"（https://z-lib.fm/dl/18993686/b61824）"}},{"type":"text","data":{"text":"\n"}},{"type":"text","data":{"text":"\n"}},{"type":"text","data":{"text":"[#8]"}},{"type":"text","data":{"text":"\n"}},{"type":"text","data":{"text":" [标题] 世界史的故事（套装共6册）（美国博雅教育传奇人物，以高超的叙事天赋、广博的学识，赋予尘封的历史血肉精神，让历史成为普通人通往博与雅的钥匙。）"}},{"type":"text","data":{"text":"\n"}},{"type":"text","data":{"text":"[作者] 苏珊·怀斯·鲍尔 [苏珊·怀斯·鲍尔]"}},{"type":"text","data":{"text":"\n"}},{"type":"text","data":{"text":"[年份] 2020 [语言] Chinese"}},{"type":"text","data":{"text":"\n"}},{"type":"text","data":{"text":"[评分] ★★★★★ [质量] ☆"}},{"type":"text","data":{"text":"\n"}},{"type":"text","data":{"text":"[详情] "}},{"type":"text","data":{"text":"（https://z-lib.fm/book/5786299/b40f9d/世界史的故事套装共6册美国博雅教育传奇人物以高超的叙事天赋广博的学识赋予尘封的历史血肉精神让历史成为普通人通往博与雅的钥匙.html）"}},{"type":"text","data":{"text":"\n"}},{"type":"text","data":{"text":"[大小] 57.95 MB [类型] epub [下载] "}},{"type":"text","data":{"text":"（https://z-lib.fm/dl/5786299/9b0c62）"}},{"type":"text","data":{"text":"\n"}},{"type":"text","data":{"text":"\n"}},{"type":"text","data":{"text":"[#9]"}},{"type":"text","data":{"text":"\n"}},{"type":"text","data":{"text":" [标题] 故事技巧 叙事性非虚构文学写作指南"}},{"type":"text","data":{"text":"\n"}},{"type":"text","data":{"text":"[作者] Jack Hart"}},{"type":"text","data":{"text":"\n"}},{"type":"text","data":{"text":"[年份] 2019 [语言] Chinese"}},{"type":"text","data":{"text":"\n"}},{"type":"text","data":{"text":"[评分] ★★★ [质量] ★"}},{"type":"text","data":{"text":"\n"}},{"type":"text","data":{"text":"[详情] "}},{"type":"text","data":{"text":"（https://z-lib.fm/book/17793537/155f59/故事技巧-叙事性非虚构文学写作指南.html）"}},{"type":"text","data":{"text":"\n"}},{"type":"text","data":{"text":"[大小] 22.12 MB [类型] epub [下载] "}},{"type":"text","data":{"text":"（https://z-lib.fm/dl/17793537/dd1a52）"}},{"type":"text","data":{"text":"\n"}},{"type":"text","data":{"text":"\n"}},{"type":"text","data":{"text":"[#10]"}},{"type":"text","data":{"text":"\n"}},{"type":"text","data":{"text":" [标题] 故事与话语：小说和电影的叙事结构"}},{"type":"text","data":{"text":"\n"}},{"type":"text","data":{"text":"[作者] （美）西摩·查特曼"}},{"type":"text","data":{"text":"\n"}},{"type":"text","data":{"text":"[年份] 2012 [语言] Chinese"}},{"type":"text","data":{"text":"\n"}},{"type":"text","data":{"text":"[评分] ★★★★★ [质量] ★★★★★"}},{"type":"text","data":{"text":"\n"}},{"type":"text","data":{"text":"[详情] "}},{"type":"text","data":{"text":"（https://z-lib.fm/book/11960553/d297bf/故事与话语小说和电影的叙事结构.html）"}},{"type":"text","data":{"text":"\n"}},{"type":"text","data":{"text":"[大小] 8.21 MB [类型] epub [下载] "}},{"type":"text","data":{"text":"（https://z-lib.fm/dl/11960553/cfc066）"}},{"type":"text","data":{"text":"\n"}},{"type":"text","data":{"text":"\n"}},{"type":"text","data":{"text":"[#11]"}},{"type":"text","data":{"text":"\n"}},{"type":"text","data":{"text":" [标题] 后现代历史叙事学"}},{"type":"text","data":{"text":"\n"}},{"type":"text","data":{"text":"[作者] 海登・怀特"}},{"type":"text","data":{"text":"\n"}},{"type":"text","data":{"text":"[年份] 2003 [语言] Chinese"}},{"type":"text","data":{"text":"\n"}},{"type":"text","data":{"text":"[评分] ★★★★ [质量] ★★★★"}},{"type":"text","data":{"text":"\n"}},{"type":"text","data":{"text":"[详情] "}},{"type":"text","data":{"text":"（https://z-lib.fm/book/5986205/027730/后现代历史叙事学.html）"}},{"type":"text","data":{"text":"\n"}},{"type":"text","data":{"text":"[大小] 9.34 MB [类型] pdf [下载] "}},{"type":"text","data":{"text":"（https://z-lib.fm/dl/5986205/a51213）"}},{"type":"text","data":{"text":"\n"}},{"type":"text","data":{"text":"\n"}},{"type":"text","data":{"text":"[#12]"}},{"type":"text","data":{"text":"\n"}},{"type":"text","data":{"text":" [标题] 世界史的故事（套装共6册）（美国博雅教育传奇人物，以高超的叙事天赋、广博的学识，赋予尘封的历史血肉精神，让历史成为普通人通往博与雅的钥匙。）"}},{"type":"text","data":{"text":"\n"}},{"type":"text","data":{"text":"[作者] 苏珊·怀斯·鲍尔 [苏珊·怀斯·鲍尔]"}},{"type":"text","data":{"text":"\n"}},{"type":"text","data":{"text":"[年份] 2020 [语言] Chinese"}},{"type":"text","data":{"text":"\n"}},{"type":"text","data":{"text":"[评分] ★★★★★ [质量] ★★★★★"}},{"type":"text","data":{"text":"\n"}},{"type":"text","data":{"text":"[详情] "}},{"type":"text","data":{"text":"（https://z-lib.fm/book/8568892/43e1b5/世界史的故事套装共6册美国博雅教育传奇人物以高超的叙事天赋广博的学识赋予尘封的历史血肉精神让历史...
willbot-1  |                             at _Internal._get (/koishi/node_modules/koishi-plugin-adapter-onebot/lib/index.js:119:11)
willbot-1  |                             at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
willbot-1  |                             at async _Internal.<computed> [as sendGroupForwardMsg] (/koishi/node_modules/koishi-plugin-adapter-onebot/lib/index.js:162:20)
willbot-1  |                             at async OneBotMessageEncoder.forward (/koishi/node_modules/koishi-plugin-adapter-onebot/lib/index.js:714:232)
willbot-1  |                             at async OneBotMessageEncoder.visit (/koishi/node_modules/koishi-plugin-adapter-onebot/lib/index.js:901:9)
willbot-1  |                             at async OneBotMessageEncoder.render (/koishi/node_modules/@satorijs/core/lib/index.cjs:593:7)
willbot-1  |                             at async OneBotMessageEncoder.visit (/koishi/node_modules/koishi-plugin-adapter-onebot/lib/index.js:910:7)
willbot-1  |                             at async OneBotMessageEncoder.render (/koishi/node_modules/@satorijs/core/lib/index.cjs:593:7)
willbot-1  |                             at async OneBotMessageEncoder.visit (/koishi/node_modules/koishi-plugin-adapter-onebot/lib/index.js:910:7)
willbot-1  |                             at async OneBotMessageEncoder.render (/koishi/node_modules/@satorijs/core/lib/index.cjs:593:7)
```

**Comment by MliKiowa** [comment]
暂时没有头绪 可能消息带有敏感信息
