### ISSUE TITLE
[BUG] 无法发送本地图片

### ISSUE THREAD

**Issue by Elan114514** [NapNeko/NapCatQQ#572]
### 系统版本

 Windows Server 2016

### QQNT 版本

9.9.16-29927

### NapCat 版本

4.2.2

### OneBot 客户端

Nonebot2 2.3.2

### 发生了什么?

发送本地图片时报错：发生错误 Error: ENOENT: no such file or directory, copyfile 'E:\E:\bot\bot\data\s\over\over15.png' -> 'C:\Users\Administrator\Documents\Tencent Files\NapCat\temp\909adb3b-242b-43e9-99a8-f377570bf592.png'
    at Object.copyFileSync (node:fs:3013:11)
    at Object.func [as copyFileSync] (node:electron/js2c/node_init:2:2967)
    at uri2local (file:///E:/Napcat/Shell/NapCat2/napcat.mjs:20900:17)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async OneBotMsgApi.handleOb11FileLikeMessage (file:///E:/Napcat/Shell/NapCat2/napcat.mjs:48034:9)
    at async image (file:///E:/Napcat/Shell/NapCat2/napcat.mjs:47662:10)
    at async Promise.all (index 1)
    at async OneBotMsgApi.createSendElements (file:///E:/Napcat/Shell/NapCat2/napcat.mjs:47971:17)
    at async SendMsg._handle (file:///E:/Napcat/Shell/NapCat2/napcat.mjs:48180:52)
    at async SendMsg.websocketHandle (file:///E:/Napcat/Shell/NapCat2/napcat.mjs:43085:23)

### 如何复现

1.让机器人发送一张本体图片
2.报错

### 期望的结果?

能够正常发送本地图片

### NapCat 运行日志

```shell
发生错误 Error: ENOENT: no such file or directory, copyfile 'E:\E:\mcbot\senbeibot\data\senbei\over\over15.png' -> 'C:\Users\Administrator\Documents\Tencent Files\NapCat\temp\909adb3b-242b-43e9-99a8-f377570bf592.png'
    at Object.copyFileSync (node:fs:3013:11)
    at Object.func [as copyFileSync] (node:electron/js2c/node_init:2:2967)
    at uri2local (file:///E:/Napcat/Shell/NapCat2/napcat.mjs:20900:17)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async OneBotMsgApi.handleOb11FileLikeMessage (file:///E:/Napcat/Shell/NapCat2/napcat.mjs:48034:9)
    at async image (file:///E:/Napcat/Shell/NapCat2/napcat.mjs:47662:10)
    at async Promise.all (index 1)
    at async OneBotMsgApi.createSendElements (file:///E:/Napcat/Shell/NapCat2/napcat.mjs:47971:17)
    at async SendMsg._handle (file:///E:/Napcat/Shell/NapCat2/napcat.mjs:48180:52)
    at async SendMsg.websocketHandle (file:///E:/Napcat/Shell/NapCat2/napcat.mjs:43085:23)
```

**Comment by MliKiowa** [comment]
无法复现

**Comment by Suica0w0** [comment]
![图片](https://github.com/user-attachments/assets/8d3b2a6d-566c-45fd-9113-b129d0b7c03e)
情况相同

**Comment by MliKiowa** [comment]
能否给出原始请求

> ![图片](https://private-user-images.githubusercontent.com/21064134/390614397-8d3b2a6d-566c-45fd-9113-b129d0b7c03e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI3NjExMzQsIm5iZiI6MTczMjc2MDgzNCwicGF0aCI6Ii8yMTA2NDEzNC8zOTA2MTQzOTctOGQzYjJhNmQtNTY2Yy00NWZkLTkxMTMtYjEyOWQwYjdjMDNlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTI4VDAyMjcxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRiODQ1M2E0OTY0NDZhMjJhNGYyMzg0NzMzNjk0NzU1MjE3Nzc4ZGVmYzc2MGFjZmFiNTc5MWFlZDBjYWQ4OTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.LF13qzggCCvvV7BnwbONy-DUXphfI7JUR2_opj5ONys) 情况相同

**Comment by MliKiowa** [comment]
> 确实是有这个问题, 盘符重复了

给出原始请求json

**Comment by MliKiowa** [comment]
> ### 系统版本
> Windows Server 2016
> 
> ### QQNT 版本
> 9.9.16-29927
> 
> ### NapCat 版本
> 4.2.2
> 
> ### OneBot 客户端
> Nonebot2 2.3.2
> 
> ### 发生了什么?
> 发送本地图片时报错：发生错误 Error: ENOENT: no such file or directory, copyfile 'E:\E:\bot\bot\data\s\over\over15.png' -> 'C:\Users\Administrator\Documents\Tencent Files\NapCat\temp\909adb3b-242b-43e9-99a8-f377570bf592.png' at Object.copyFileSync (node:fs:3013:11) at Object.func [as copyFileSync] (node:electron/js2c/node_init:2:2967) at uri2local (file:///E:/Napcat/Shell/NapCat2/napcat.mjs:20900:17) at process.processTicksAndRejections (node:internal/process/task_queues:95:5) at async OneBotMsgApi.handleOb11FileLikeMessage (file:///E:/Napcat/Shell/NapCat2/napcat.mjs:48034:9) at async image (file:///E:/Napcat/Shell/NapCat2/napcat.mjs:47662:10) at async Promise.all (index 1) at async OneBotMsgApi.createSendElements (file:///E:/Napcat/Shell/NapCat2/napcat.mjs:47971:17) at async SendMsg._handle (file:///E:/Napcat/Shell/NapCat2/napcat.mjs:48180:52) at async SendMsg.websocketHandle (file:///E:/Napcat/Shell/NapCat2/napcat.mjs:43085:23)
> 
> ### 如何复现
> 1.让机器人发送一张本体图片 2.报错
> 
> ### 期望的结果?
> 能够正常发送本地图片
> 
> ### NapCat 运行日志
> ```shell
> 发生错误 Error: ENOENT: no such file or directory, copyfile 'E:\E:\mcbot\senbeibot\data\senbei\over\over15.png' -> 'C:\Users\Administrator\Documents\Tencent Files\NapCat\temp\909adb3b-242b-43e9-99a8-f377570bf592.png'
>     at Object.copyFileSync (node:fs:3013:11)
>     at Object.func [as copyFileSync] (node:electron/js2c/node_init:2:2967)
>     at uri2local (file:///E:/Napcat/Shell/NapCat2/napcat.mjs:20900:17)
>     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
>     at async OneBotMsgApi.handleOb11FileLikeMessage (file:///E:/Napcat/Shell/NapCat2/napcat.mjs:48034:9)
>     at async image (file:///E:/Napcat/Shell/NapCat2/napcat.mjs:47662:10)
>     at async Promise.all (index 1)
>     at async OneBotMsgApi.createSendElements (file:///E:/Napcat/Shell/NapCat2/napcat.mjs:47971:17)
>     at async SendMsg._handle (file:///E:/Napcat/Shell/NapCat2/napcat.mjs:48180:52)
>     at async SendMsg.websocketHandle (file:///E:/Napcat/Shell/NapCat2/napcat.mjs:43085:23)
> ```
> 
> ### OneBot 客户端运行日志
> _No response_

给出原始请求json
