### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by tianyage** [NapNeko/NapCatQQ#600]
### 系统版本

windows server 2022

### QQNT 版本

9.9.16

### NapCat 版本

4.2.23

### OneBot 客户端

-

### 发生了什么?

发送消息失败时，无法得到正常的报错信息。

### 如何复现

调用 /send_private_msg 和 /send_group_msg
给非好友发送私聊，给非所在群发送群聊

### 期望的结果?

优化返回的错误详情

### NapCat 运行日志

```shell
#私聊报错
Error: Timeout: NTEvent serviceAndMethod:NodeIKernelMsgService/sendMsg ListenerName:NodeIKernelMsgListener/onMsgInfoListUpdate EventRet:
{}

    at sendDataCallback (file:///C:/NapCat/NapCat/napcat.mjs:23021:11)
    at Timeout._onTimeout (file:///C:/NapCat/NapCat/napcat.mjs:23034:45)
    at listOnTimeout (node:internal/timers:573:17)
    at process.processTimers (node:internal/timers:514:7)


#群聊报错
Error: EventChecker Failed: NTEvent serviceAndMethod:NodeIKernelMsgService/sendMsg ListenerName:NodeIKernelMsgListener/onMsgInfoListUpdate EventRet:
{
    "result": 110,
    "errMsg": "发送失败，你已被移出该群，请重新加群。"
}

    at eventRetHandle (file:///C:/NapCat/NapCat/napcat.mjs:23062:15)
    at file:///C:/NapCat/NapCat/napcat.mjs:23070:13
```

### OneBot 客户端运行日志

```shell
#私聊
{"status":"failed","retcode":200,"data":null,"message":"Timeout: NTEvent serviceAndMethod:NodeIKernelMsgService/sendMsg ListenerName:NodeIKernelMsgListener/onMsgInfoListUpdate EventRet:\n{}\n","wording":"Timeout: NTEvent serviceAndMethod:NodeIKernelMsgService/sendMsg ListenerName:NodeIKernelMsgListener/onMsgInfoListUpdate EventRet:\n{}\n","echo":null}

# 群聊
{"status":"failed","retcode":200,"data":null,"message":"EventChecker Failed: NTEvent serviceAndMethod:NodeIKernelMsgService/sendMsg ListenerName:NodeIKernelMsgListener/onMsgInfoListUpdate EventRet:\n{\n    \"result\": 110,\n    \"errMsg\": \"发送失败，你已被移出该群，请重新加群。\"\n}\n","wording":"EventChecker Failed: NTEvent serviceAndMethod:NodeIKernelMsgService/sendMsg ListenerName:NodeIKernelMsgListener/onMsgInfoListUpdate EventRet:\n{\n    \"result\": 110,\n    \"errMsg\": \"发送失败，你已被移出该群，请重新加群。\"\n}\n","echo":null}
```

**Comment by sisi0318** [comment]
不支持主动临时聊天

**Comment by tianyage** [comment]
> 不支持主动临时聊天

这个issues是在说报错内容的问题哈，并不是要发送临时消息。

**Comment by sisi0318** [comment]
如果不需要用到主动临时聊天 可以忽略该报错

**Comment by MliKiowa** [comment]
这个错误信息是QQ客户端给出来的 他是这么设计的

**Comment by tianyage** [comment]
> 这个错误信息是QQ客户端给出来的 他是这么设计的

好的，感谢大佬答疑解惑。

![image](https://github.com/user-attachments/assets/d73005e4-6192-42b1-9296-82aa91bb9735)

那可以简化在onebot接口中的报错信息吗，message字段直接返回 retEvent 不包含 serviceAndMethod 和 listenerAndMethod

**Comment by MliKiowa** [comment]
> > 这个错误信息是QQ客户端给出来的 他是这么设计的
> 
> 好的，感谢大佬答疑解惑。
> 
> ![image](https://private-user-images.githubusercontent.com/47635970/392464106-d73005e4-6192-42b1-9296-82aa91bb9735.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMzNjUxNzAsIm5iZiI6MTczMzM2NDg3MCwicGF0aCI6Ii80NzYzNTk3MC8zOTI0NjQxMDYtZDczMDA1ZTQtNjE5Mi00MmIxLTkyOTYtODJhYTkxYmI5NzM1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA1VDAyMTQzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRiMmQxZDI3OWVkYTZkMTg1ZmI3OWIyNjg2MzYyMWJkZDk5MzYyYWEwODg0YTA0ZWY4MTg4YTFmNGE4YmY4OTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.g_HbBQ-If9Z9WJgrxn7rVnXeyc2PoFheWEVMwqvRaKs)
> 
> 那可以简化在onebot接口中的报错信息吗，message字段直接返回 retEvent 不包含 serviceAndMethod 和 listenerAndMethod

这样对错误排查感觉不太好 简化的方法 可以说 提取message字段 然后带上serviceAndMethod/listenerAndMethod
