### ISSUE TITLE
[BUG] Python发送失败

### ISSUE THREAD

**Issue by wzhy19** [NapNeko/NapCatQQ#606]
### 系统版本

Ubuntu 24.04

### QQNT 版本

3.2.13-29927

### NapCat 版本

4.2.24 使用无头Docker运行

### OneBot 客户端

无

### 发生了什么?

curl post正常，python报错
```
{"status":"failed","retcode":200,"data":null,"message":"Cannot read properties of undefined (reading 'toString')","wording":"Cannot read properties of undefined (reading 'toString')","echo":null}
```
python用request或者http.client方法都一样
```
import requests
import json

url = "http://prod-cn.your-api-server.com/send_group_msg"

payload = json.dumps({
   "group_id": "123456",
   "message": [
      {
         "type": "at",
         "data": {
            "text": "123456789"
         }
      },
      {
         "type": "text",
         "data": {
            "text": "napcat"
         }
      }
   ]
})
headers = {
   'Content-Type': 'application/json'
}

response = requests.request("POST", url, headers=headers, data=payload)

print(response.text)
```

Python 3.12.3 和 3.6.15都是一样的结果。如果message里只有一组消息类型的话就可以发送

### 如何复现

1.docker-compose up
2.python3 demo.py

### 期望的结果?

正常发送信息为``@甲乙丙napcat``

### NapCat 运行日志

```shell
napcat    | 12-06 16:05:16 [error] 甲乙丙丁| 发生错误 TypeError: Cannot read properties of undefined (reading 'toString')
napcat    |     at NTQQGroupApi.getGroupMember (file:///app/napcat/napcat.mjs:21744:46)
napcat    |     at at (file:///app/napcat/napcat.mjs:47306:54)
napcat    |     at OneBotMsgApi.createSendElements (file:///app/napcat/napcat.mjs:47691:26)
napcat    |     at SendGroupMsg._handle (file:///app/napcat/napcat.mjs:47933:85)
napcat    |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
napcat    |     at async SendGroupMsg.handle (file:///app/napcat/napcat.mjs:42848:23)
napcat    |     at async OB11PassiveHttpAdapter.handleRequest (file:///app/napcat/napcat.mjs:43644:24)
napcat    |     at async file:///app/napcat/napcat.mjs:43607:7
```
```


### OneBot 客户端运行日志

```shell
无
```

**Comment by MliKiowa** [comment]
先尝试到 NapCat V4.2.27

**Comment by wzhy19** [comment]
OK那等docker镜像更新之后我再试试吧

**Comment by MliKiowa** [comment]
![image](https://github.com/user-attachments/assets/60bff4b4-9734-4453-9841-cf31436c0912)
如果新版仍有问题 再补上错误

**Comment by wzhy19** [comment]
更新到4.2.27了，相同报错
```
napcat    | 12-06 16:58:39 [error] 甲乙丙丁| 发生错误 TypeError: Cannot read properties of undefined (reading 'toString')
napcat    |     at NTQQGroupApi.getGroupMember (file:///app/napcat/napcat.mjs:21769:46)
napcat    |     at at (file:///app/napcat/napcat.mjs:47296:54)
napcat    |     at OneBotMsgApi.createSendElements (file:///app/napcat/napcat.mjs:47681:26)
napcat    |     at SendGroupMsg._handle (file:///app/napcat/napcat.mjs:47925:85)
napcat    |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
napcat    |     at async SendGroupMsg.handle (file:///app/napcat/napcat.mjs:42839:23)
napcat    |     at async OB11PassiveHttpAdapter.handleRequest (file:///app/napcat/napcat.mjs:43635:24)
napcat    |     at async file:///app/napcat/napcat.mjs:43598:7

```

**Comment by MliKiowa** [comment]
at是错误的吧

**Comment by MliKiowa** [comment]
```python
payload = json.dumps({
   "group_id": "123456",
   "message": [
      {
         "type": "at",
         "data": {
            "qq": "123456789"
         }
      },
      {
         "type": "text",
         "data": {
            "text": "napcat"
         }
      }
   ]
})
```

**Comment by wzhy19** [comment]
确实，at的text换成qq就没事了。sorry复制上去看漏忘改了
