### ISSUE TITLE
[BUG] get_profile_like时账号转换失败

### ISSUE THREAD

**Issue by jxi-wy134d887hex** [NapNeko/NapCatQQ#608]
### 系统版本

Windows 10 22H2

### QQNT 版本

9.9.15-28498

### NapCat 版本

3.0.1

### OneBot 客户端

nonebot2  2.3.3    python  3.10

### 发生了什么?

使用 get_profile_like  获取 点赞列表失败

### 如何复现

在群聊或私聊中让机器人 发送 点赞列表

### 期望的结果?

至少没有error

### NapCat 运行日志

```shell
2024-12-07 19:54:28 [DEBUG] ​(2013297336) | [OneBot] [WebSocket Client] 收到正向Websocket消息 {"action":"get_profile_like","params":{},"echo":"28"} 
2024-12-07 19:54:28 [INFO] ​(2013297336) | 接收 <- 群聊 [bot_test(973831627)] [A(3831539102)] 999 
2024-12-07 19:54:28 [DEBUG] ​(2013297336) | 收到新消息 RawMessage {"msgId":"7445637047534521740","msgRandom":"800974591","msgSeq":"4771","cntSeq":"0","chatType":2,"msgType":2,"subMsgType":1,"sendType":0,"senderUid":"u_9RbK_aafLShRUwZJLQd67w","peerUid":"973831627","channelId":"","guildId":"","guildCode":"0","fromUid":"0","fromAppid":"0","msgTime":"1733572466","msgMeta":{},"sendStatus":2,"sendRemarkName":"A","sendMemberName":"","sendNickName":"A","guildName":"","channelName":"","elements":[{"elementType":1,"elementId":"7445637047534521739","elementGroupId":0,"extBufForUI":{},"textElement":{"content":"999","atType":0,"atUid":"0","atTinyId":"0","atNtUid":"","subElementType":0,"atChannelId":"0","linkInfo":null,"atRoleId":"0","atRoleColor":0,"atRoleName":"","needNotify":0},"faceElement":null,"marketFaceElement":null,"replyElement":null,"picElement":null,"pttElement":null,"videoElement":null,"grayTipElement":null,"arkElement":null,"fileElement":null,"liveGiftElement":null,"markdownElement":null,"structLongMsgElement":null,"multiForwardMsgElement":null,"giphyElement":null,"walletElement":null,"inlineKeyboardElement":null,"textGiftElement":null,"calendarElement":null,"yoloGameResultElement":null,"avRecordElement":null,"structMsgElement":null,"faceBubbleElement":null,"shareLocationElement":null,"tofuRecordElement":null,"taskTopMsgElement":null,"recommendedMsgElement":null,"actionBarElement":null,"prologueMsgElement":null}],"records":[],"emojiLikesList":[],"commentCnt":"0","directMsgFlag":0,"directMsgMembers":[],"peerName":"bot_test","freqLimitInfo":null,"editable":false,"avatarMeta":"","avatarPendant":"","feedId":"","roleId":"0","timeStamp":"0","clientIdentityInfo":null,"isImportMsg":false,"atType":0,"roleType":0,"fromChannelRoleInfo":{"roleId":"0","name":"","color":0},"fromGuildRoleInfo":{"roleId":"0","name":"","color":0},"levelRoleInfo":{"roleId":"0","name":"","color":0},"recallTime":"0","isOnlineMsg":true,"generalFlags":{},"clientSeq":"0","fileGroupSize":null,"foldingInfo":null,"multiTransInfo":null,"senderUin":"3831539102","peerUin":"973831627","msgAttrs":{},"anonymousExtInfo":null,"nameType":0,"avatarFlag":0,"extInfoForUI":null,"personalMedal":null,"categoryManage":0,"msgEventInfo":null,"sourceType":1,"id":689265161} 
2024-12-07 19:54:28 [DEBUG] ​(2013297336) | 转化为 OB11Message {"self_id":2013297336,"user_id":3831539102,"time":1733572466,"message_id":689265161,"message_seq":689265161,"real_id":689265161,"message_type":"group","sender":{"user_id":3831539102,"nickname":"A","card":"","role":"owner"},"raw_message":"999","font":14,"sub_type":"normal","message":[{"type":"text","data":{"text":"999"}}],"message_format":"array","post_type":"message","group_id":973831627} 
2024-12-07 19:54:33 [DEBUG] ​(2013297336) | [NapCat] [Mark] getUserDetailInfo Mode1 Failed. 
2024-12-07 19:54:38 [ERROR] ​(2013297336) | 发生错误 Error: Timeout: NTEvent serviceAndMethod:NodeIKernelProfileService/fetchUserDetailInfo ListenerName:NodeIKernelProfileListener/onUserDetailInfoChanged EventRet:
{
    "result": 116,
    "errMsg": "账号转换失败",
    "source": 1,
    "detail": {}
}

    at Timeout.sendDataCallback [as _onTimeout] (file:///C:/Users/1/Documents/LiteloaderQQNT/plugins/NapCat.Framework_72252%20/napcat.mjs:7732:15)
    at listOnTimeout (node:internal/timers:573:17)
    at process.processTimers (node:internal/timers:514:7)
```

### OneBot 客户端运行日志

```shell
Traceback (most recent call last):
  File "<string>", line 15, in <module>
  File "C:\Users\1\autoplay\.venv\lib\site-packages\nonebot\__init__.py", line 337, in run
    get_driver().run(*args, **kwargs)
  File "C:\Users\1\autoplay\.venv\lib\site-packages\nonebot\drivers\fastapi.py", line 188, in run
    uvicorn.run(
  File "C:\Users\1\autoplay\.venv\lib\site-packages\uvicorn\main.py", line 579, in run
    server.run()
  File "C:\Users\1\autoplay\.venv\lib\site-packages\uvicorn\server.py", line 65, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "C:\Users\1\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\1\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 628, in run_until_complete
    self.run_forever()
  File "C:\Users\1\AppData\Local\Programs\Python\Python310\lib\asyncio\windows_events.py", line 316, in run_forever
    super().run_forever()
  File "C:\Users\1\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 595, in run_forever
    self._run_once()
  File "C:\Users\1\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 1881, in _run_once
    handle._run()
  File "C:\Users\1\AppData\Local\Programs\Python\Python310\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\1\autoplay\.venv\lib\site-packages\nonebot\utils.py", line 254, in run_coro_with_shield
    return await coro
  File "C:\Users\1\autoplay\.venv\lib\site-packages\nonebot\message.py", line 506, in check_and_run_matcher
    await _run_matcher(
> File "C:\Users\1\autoplay\.venv\lib\site-packages\nonebot\message.py", line 458, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "C:\Users\1\autoplay\.venv\lib\site-packages\nonebot\internal\matcher\matcher.py", line 900, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "C:\Users\1\autoplay\.venv\lib\site-packages\nonebot\internal\matcher\matcher.py", line 837, in simple_run
    await handler(
  File "C:\Users\1\autoplay\.venv\lib\site-packages\nonebot\dependencies\__init__.py", line 113, in __call__
    return await cast(Callable[..., Awaitable[R]], self.call)(**values)
  File "C:\Users\1\autoplay\src\plugins\test\__init__.py", line 27, in bbbbb
    ccccc = await bot.get_profile_like()
  File "C:\Users\1\autoplay\.venv\lib\site-packages\nonebot\internal\adapter\bot.py", line 176, in call_api
    raise exception
  File "C:\Users\1\autoplay\.venv\lib\site-packages\nonebot\internal\adapter\bot.py", line 128, in call_api
    result = await self.adapter._call_api(self, api, **data)
  File "C:\Users\1\autoplay\.venv\lib\site-packages\nonebot\adapters\onebot\v11\adapter.py", line 175, in _call_api
    return handle_api_result(await self._result_store.fetch(seq, timeout))
  File "C:\Users\1\autoplay\.venv\lib\site-packages\nonebot\adapters\onebot\v11\utils.py", line 58, in handle_api_result
    raise ActionFailed(**result)
nonebot.adapters.onebot.v11.exception.ActionFailed: ActionFailed(status='failed', retcode=1200, data=None, message='Error: Timeout: NTEvent serviceAndMethod:NodeIKernelProfileService/fetchUserDetailInfo ListenerName:NodeIKernelProfileListener/onUserDetailInfoChanged EventRet:\n{\n    "result": 116,\n    "errMsg": "账号转换失败",\n    "source": 1,\n    "detail": {}\n}\n\n    at Timeout.sendDataCallback [as _onTimeout] (file:///C:/Users/1/Documents/LiteloaderQQNT/plugins/NapCat.Framework_72252%20/napcat.mjs:7732:15)\n    at listOnTimeout (node:internal/timers:573:17)\n    at process.processTimers (node:internal/timers:514:7)', wording='Error: Timeout: NTEvent serviceAndMethod:NodeIKernelProfileService/fetchUserDetailInfo ListenerName:NodeIKernelProfileListener/onUserDetailInfoChanged EventRet:\n{\n    "result": 116,\n    "errMsg": "账号转换失败",\n    "source": 1,\n    "detail": {}\n}\n\n    at Timeout.sendDataCallback [as _onTimeout] (file:///C:/Users/1/Documents/LiteloaderQQNT/plugins/NapCat.Framework_72252%20/napcat.mjs:7732:15)\n    at listOnTimeout (node:internal/timers:573:17)\n    at process.processTimers (node:internal/timers:514:7)', echo='53')
```

**Comment by MliKiowa** [comment]
更新版本 并确认参数传递 陌生人不可获取 至少存在相同群聊或好友 如仍有问题请补充
