### ISSUE TITLE
[BUG] 点赞失败 账号转换失败

### ISSUE THREAD

**Issue by TLBLL** [NapNeko/NapCatQQ#617]
### 系统版本

Window11

### QQNT 版本

9.9.16-29927

### NapCat 版本

1.0.0

### OneBot 客户端

win绿色无头

### 发生了什么?

使用的绿色无头版本，登录正常，在使用send_like的时候，会出现
{"status":"failed","retcode":200,"data":null,"message":"点赞失败 账号转换失败","wording":"点赞失败 账号转换失败","echo":null}

### 如何复现

1.登录绿色无头qq
2.运行使用url = "http://localhost:3000/send_like"
3.运行结果为{"status":"failed","retcode":200,"data":null,"message":"点赞失败 账号转换失败","wording":"点赞失败 账号转换失败","echo":null}

### 期望的结果?

我的账号可以正常通过api接口进行点赞操作

### NapCat 运行日志

```shell
12-10 19:21:33 [error] 蒸 | 发生错误 Error: 点赞失败 账号转换失败
    at SendLike._handle (file:///D:/Application/QQ.NatCatQQ/napcat.29927.onekey/versions/9.9.16-29927/resources/app/napcat/napcat.mjs:52089:13)
    at async SendLike.handle (file:///D:/Application/QQ.NatCatQQ/napcat.29927.onekey/versions/9.9.16-29927/resources/app/napcat/napcat.mjs:42844:23)
    at async OB11PassiveHttpAdapter.handleRequest (file:///D:/Application/QQ.NatCatQQ/napcat.29927.onekey/versions/9.9.16-29927/resources/app/napcat/napcat.mjs:43640:24)
    at async file:///D:/Application/QQ.NatCatQQ/napcat.29927.onekey/versions/9.9.16-29927/resources/app/napcat/napcat.mjs:43603:7
```

### OneBot 客户端运行日志

```shell
{"status":"failed","retcode":200,"data":null,"message":"点赞失败 账号转换失败","wording":"点赞失败 账号转换失败","echo":null}
```

**Comment by sisi0318** [comment]
无法给陌生人点赞

**Comment by TLBLL** [comment]
> 无法给陌生人点赞

应该是可以的，至少我其他的号是可以的

**Comment by sisi0318** [comment]
这里的陌生人指的是你的机器人从未见过的账号 而不是没添加过好友

**Comment by TLBLL** [comment]
> 这里的陌生人指的是你的机器人从未见过的账号 而不是没添加过好友

明白了，感谢感谢，问题解决了
