### ISSUE TITLE
[BUG] 连接超时

### ISSUE THREAD

**Issue by Snog1e** [NapNeko/NapCatQQ#638]
### 系统版本

Windows 10 222H

### QQNT 版本

29927

### NapCat 版本

4.2.37

### OneBot 客户端

/

### 发生了什么?

收到了消息但是不能返回内容

### 如何复现

私聊消息/群聊@bot消息

### 期望的结果?

应该要连接到腾讯元器智能体，返回内容

### NapCat 运行日志

```shell
发生错误 Error: Timeout: NTEvent serviceAndMethod:NodeIKernelGroupService/getGroupDetailInfo ListenerName:NodeIKernelGroupListener/onGroupDetailInfoChange EventRet:
{
    "result": 0,
    "errMsg": "success"
}

    at sendDataCallback (file:///E:/NTQQ/versions/9.9.16-29927/resources/app/napcat/napcat.mjs:22996:11)
    at Timeout._onTimeout (file:///E:/NTQQ/versions/9.9.16-29927/resources/app/napcat/napcat.mjs:23009:45)
    at listOnTimeout (node:internal/timers:573:17)
    at process.processTimers (node:internal/timers:514:7)
```

**Comment by MliKiowa** [comment]
与bot交互?

**Comment by MliKiowa** [comment]
无法复现你的问题 请补充信息 如果确认复现再开启issue
