### ISSUE TITLE
[BUG] get_file 发生错误 RangeError [ERR_BUFFER_OUT_OF_BOUNDS]: Attempt to access memory outside buffer bounds

### ISSUE THREAD

**Issue by EtherealAirRhyme** [NapNeko/NapCatQQ#649]
### 系统版本

Windows 10 22H2

### QQNT 版本

9.9.16-29927

### NapCat 版本

4.2.38

### OneBot 客户端

System:     OS: Windows 10 10.0.19045     CPU: (6) x64 AMD Ryzen 5 3500X 6-Core Processor               Binaries:     Node: 20.17.0     npm: 10.8.3  Koishi:     Core: 4.18.3     Console: 5.30.2

### 发生了什么?

使用的是napcat.29927.onekey.framework.zip

### 如何复现

ctx.command('aod.read', '[id:string]', { authority: 0 })
        .action(async ({ session }, id) => {
            const fileid = session.quote.elements[0].attrs.fileId
            const file = await session.bot.internal._request("get_file", { fileId: `${fileid}` })
            console.log(file)
})

### 期望的结果?

将私聊的文件保存到本地

### NapCat 运行日志

```shell
接收 <- 私聊 (1270946922) [回复消息 私聊 (1270946922) [文件 README.md]] aod.read
收到新消息 RawMessage {"msgId":"7450500100930951805","msgRandom":"1630846365","msgSeq":"120","cntSeq":"0","chatType":1,"msgType":9,"subMsgType":161,"sendType":0,"senderUid":"u_PHVYVnTPEt2vhGxjne_SsA","peerUid":"u_PHVYVnTPEt2vhGxjne_SsA","channelId":"","guildId":"","guildCode":"0","fromUid":"0","fromAppid":"0","msgTime":"1734704733","msgMeta":{},"sendStatus":2,"sendRemarkName":"","sendMemberName":"","sendNickName":"","guildName":"","channelName":"","elements":[{"elementType":7,"elementId":"7450500100930951799","elementGroupId":0,"extBufForUI":{},"textElement":null,"faceElement":null,"marketFaceElement":null,"replyElement":{"replayMsgId":"0","replayMsgSeq":"109","replayMsgRootSeq":"0","replayMsgRootMsgId":"0","replayMsgRootCommentCnt":"0","sourceMsgIdInRecords":"7450500100930951806","sourceMsgText":"","sourceMsgTextElems":[{"replyAbsElemType":3,"textElemContent":null,"faceElem":null,"picElem":{"picWidth":0,"picHeight":0,"picText":"[文件]"}}],"senderUid":"1270946922","senderUidStr":"u_PHVYVnTPEt2vhGxjne_SsA","replyMsgClientSeq":"23579","replyMsgTime":"1734701475","replyMsgRevokeType":0,"sourceMsgIsIncPic":false,"sourceMsgExpired":false,"anonymousNickName":null,"originalMsgState":null},"picElement":null,"pttElement":null,"videoElement":null,"grayTipElement":null,"arkElement":null,"fileElement":null,"liveGiftElement":null,"markdownElement":null,"structLongMsgElement":null,"multiForwardMsgElement":null,"giphyElement":null,"walletElement":null,"inlineKeyboardElement":null,"textGiftElement":null,"calendarElement":null,"yoloGameResultElement":null,"avRecordElement":null,"structMsgElement":null,"faceBubbleElement":null,"shareLocationElement":null,"tofuRecordElement":null,"taskTopMsgElement":null,"recommendedMsgElement":null,"actionBarElement":null,"prologueMsgElement":null},{"elementType":1,"elementId":"7450500100930951804","elementGroupId":0,"extBufForUI":{},"textElement":{"content":"aod.read","atType":0,"atUid":"0","atTinyId":"0","atNtUid":"","subElementType":1,"atChannelId":"0","linkInfo":{"title":null,"icon":null,"desc":null,"richStatus":2,"tencentDocType":null},"atRoleId":"0","atRoleColor":0,"atRoleName":"","needNotify":0},"faceElement":null,"marketFaceElement":null,"replyElement":null,"picElement":null,"pttElement":null,"videoElement":null,"grayTipElement":null,"arkElement":null,"fileElement":null,"liveGiftElement":null,"markdownElement":null,"structLongMsgElement":null,"multiForwardMsgElement":null,"giphyElement":null,"walletElement":null,"inlineKeyboardElement":null,"textGiftElement":null,"calendarElement":null,"yoloGameResultElement":null,"avRecordElement":null,"structMsgElement":null,"faceBubbleElement":null,"shareLocationElement":null,"tofuRecordElement":null,"taskTopMsgElement":null,"recommendedMsgElement":null,"actionBarElement":null,"prologueMsgElement":null}],"records":[{"msgId":"7450500100930951806","msgRandom":"816294989","msgSeq":"109","cntSeq":"0","chatType":1,"msgType":3,"subMsgType":1,"sendType":0,"senderUid":"u_PHVYVnTPEt2vhGxjne_SsA","peerUid":"u_PHVYVnTPEt2vhGxjne_SsA","channelId":"","guildId":"","guildCode":"0","fromUid":"0","fromAppid":"0","msgTime":"1734701475","msgMeta":{},"sendStatus":2,"sendRemarkName":"","sendMemberName":"","sendNickName":"白溟墨韵d祈祷nia","guildName":"","channelName":"","elements":[{"elementType":3,"elementId":"7450500100930951807","elementGroupId":0,"extBufForUI":{},"textElement":null,"faceElement":null,"marketFaceElement":null,"replyElement":null,"picElement":null,"pttElement":null,"videoElement":null,"grayTipElement":null,"arkElement":null,"fileElement":{"fileMd5":"","fileName":"README.md","filePath":"","fileSize":"308","picHeight":0,"picWidth":0,"picThumbPath":{},"expireTime":"1735306274","file10MMd5":"2695991c630249e0f436a40d81cf7d82","fileSha":"","fileSha3":"","videoDuration":0,"transferStatus":1,"progress":0,"invalidState":0,"fileUuid":"6a1cc14bf95b09df4de35ea1c783c368_af1e2a04-bed6-11ef-aece-8f9414a65ec5","fileSubId":"D6EAT4BICOq4hN4EEhSIfkpICILbte4wDqnHndTVhDVMCxia0AiaChHyiaia45W7BjC5uibgDOImQ4roMQANIAQY","thumbFileSize":0,"fileBizId":null,"thumbMd5":null,"folderId":null,"fileGroupIndex":0,"fileTransType":null,"subElementType":0,"storeID":0},"liveGiftElement":null,"markdownElement":null,"structLongMsgElement":null,"multiForwardMsgElement":null,"giphyElement":null,"walletElement":null,"inlineKeyboardElement":null,"textGiftElement":null,"calendarElement":null,"yoloGameResultElement":null,"avRecordElement":null,"structMsgElement":null,"faceBubbleElement":null,"shareLocationElement":null,"tofuRecordElement":null,"taskTopMsgElement":null,"recommendedMsgElement":null,"actionBarElement":null,"prologueMsgElement":null}],"records":[],"emojiLikesList":[],"commentCnt":"0","directMsgFlag":0,"directMsgMembers":[],"peerName":"","freqLimitInfo":null,"editable":false,"avatarMeta":"","avatarPendant":"","feedId":"","roleId":"0","timeStamp":"0","clientIdentityInfo":null,"isImportMsg":false,"atType":0,"roleType":0,"fromChannelRoleInfo":{"roleId":"0","name":"","color":0},"fromGuildRoleInfo":{"roleId":"0","name":"","color":0},"levelRoleInfo":{"roleId":"0","name":"","color":0},"recallTime":"0","isOnlineMsg":false,"generalFlags":{},"clientSeq":"23579","fileGroupSize":null,"foldingInfo":null,"multiTransInfo":null,"senderUin":"1270946922","peerUin":"1270946922","msgAttrs":{},"anonymousExtInfo":null,"nameType":0,"avatarFlag":0,"extInfoForUI":null,"personalMedal":null,"categoryManage":0,"msgEventInfo":null,"sourceType":0}],"emojiLikesList":[],"commentCnt":"0","directMsgFlag":0,"directMsgMembers":[],"peerName":"","freqLimitInfo":null,"editable":false,"avatarMeta":"","avatarPendant":"","feedId":"","roleId":"0","timeStamp":"0","clientIdentityInfo":null,"isImportMsg":false,"atType":0,"roleType":0,"fromChannelRoleInfo":{"roleId":"0","name":"","color":0},"fromGuildRoleInfo":{"roleId":"0","name":"","color":0},"levelRoleInfo":{"roleId":"0","name":"","color":0},"recallTime":"0","isOnlineMsg":true,"generalFlags":{},"clientSeq":"57135","fileGroupSize":null,"foldingInfo":null,"multiTransInfo":null,"senderUin":"1270946922","peerUin":"1270946922","msgAttrs":{},"anonymousExtInfo":null,"nameType":0,"avatarFlag":0,"extInfoForUI":null,"personalMedal":null,"categoryManage":0,"msgEventInfo":null,"sourceType":1,"id":697557461}
转化为 OB11Message {"stringMsg":{"self_id":3951441492,"user_id":1270946922,"time":1734704733,"message_id":697557461,"message_seq":697557461,"real_id":697557461,"message_type":"private","sender":{"user_id":1270946922,"nickname":"白溟墨韵d祈祷nia","card":""},"raw_message":"[CQ:reply,id=2022087279]aod.read","font":14,"sub_type":"friend","message":"[CQ:reply,id=2022087279]aod.read","message_format":"string","post_type":"message"},"arrayMsg":{"self_id":3951441492,"user_id":1270946922,"time":1734704733,"message_id":697557461,"message_seq":697557461,"real_id":697557461,"message_type":"private","sender":{"user_id":1270946922,"nickname":"白溟墨韵d祈祷nia","card":""},"raw_message":"[CQ:reply,id=2022087279]aod.read","font":14,"sub_type":"friend","message":[{"type":"reply","data":{"id":"2022087279"}},{"type":"text","data":{"text":"aod.read"}}],"message_format":"array","post_type":"message"}}
[OneBot] [WebSocket Client] 收到正向Websocket消息 {"action":"get_msg","params":{"message_id":2022087279},"echo":186}
[OneBot] [WebSocket Client] 收到正向Websocket消息 {"action":"get_file","params":{"fileId":"0000013a4e61704361744f6e65426f747c4d736746696c657c317c755f50485659566e5450457432766847786a6e655f5373417c373435303438363130333931343937373831367c373435303438363130333931343937373831357c36613163633134626639356230396466346465333565613163373833633336385f61663165326130342d626564362d313165662d616563652d386639343134613635656335.README.md"},"echo":188}
发生错误 RangeError [ERR_BUFFER_OUT_OF_BOUNDS]: Attempt to access memory outside buffer bounds
    at boundsError (node:internal/buffer:86:11)
    at Buffer.readUInt32BE (node:internal/buffer:311:5)
    at FileNapCatOneBotUUID.decode (file:///G:/napcat.29927.onekey.framework/versions/9.9.16-29927/resources/app/LiteLoader/plugins/NapCatQQ/napcat.mjs:15636:57)
    at GetFile._handle (file:///G:/napcat.29927.onekey.framework/versions/9.9.16-29927/resources/app/LiteLoader/plugins/NapCatQQ/napcat.mjs:49032:49)
    at GetFile.websocketHandle (file:///G:/napcat.29927.onekey.framework/versions/9.9.16-29927/resources/app/LiteLoader/plugins/NapCatQQ/napcat.mjs:39565:34)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async OB11ActiveWebSocketAdapter.handleMessage (file:///G:/napcat.29927.onekey.framework/versions/9.9.16-29927/resources/app/LiteLoader/plugins/NapCatQQ/napcat.mjs:39710:21)
```

**Comment by MliKiowa** [comment]
1. 尝试到其他设置 关闭file转base64功能
2. 使用gocq风格的get_group_file_url接口(没记错的话) 直接获取下载链接 然后自己下载
