### ISSUE TITLE
[BUG] 接受群聊邀请报错

### ISSUE THREAD

**Issue by RexQian** [NapNeko/NapCatQQ#651]
### 系统版本

Linux Docker

### QQNT 版本

linuxqq_3.2.13-29927

### NapCat 版本

4.2.38

### OneBot 客户端

aiocqhttp

### 发生了什么?

flag没有找到对应的通知导致了失败

### 如何复现

1. 邀请机器人加群
2. 机器人接受邀请

### 期望的结果?

正常接受邀请

### NapCat 运行日志

```shell
napcat_1  | 12-21 07:51:28 [error] *** | 发生错误 Error: No such request
napcat_1  |     at SetGroupAddRequest._handle (file:///app/napcat/napcat.mjs:52193:13)
napcat_1  |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
napcat_1  |     at async SetGroupAddRequest.websocketHandle (file:///app/napcat/napcat.mjs:42884:23)
napcat_1  |     at async OB11ActiveWebSocketAdapter.handleMessage (file:///app/napcat/napcat.mjs:43029:21)
```

### OneBot 客户端运行日志

```shell
接收的事件内容（bot和group信息隐藏了)
<Event, 
{'time': 1734738688, 'self_id': xxxxx, 'post_type': 'request', 'group_id': xxxxx, 
'user_id': xxxxx, 'request_type': 'group', 'comment': '', 'flag': '1734738688386176', 'sub_type': 'invite'}

接受邀请时，提示失败
<ActionFailed status='failed', retcode=1200, data=None, message='No such request', wording='No such request', echo={'seq': 55}>
```

**Comment by MliKiowa** [comment]
https://github.com/NapNeko/NapCatQQ/commit/c94936d3dc188fe8e58eb0d8935e8b0cea30b716

尝试下 https://github.com/NapNeko/NapCatQQ/actions/runs/12442810675

**Comment by RexQian** [comment]
能正常工作了
