### ISSUE TITLE
[BUG] 某人被邀请进群时，传递的邀请人为0

### ISSUE THREAD

**Issue by LinFeng520-1** [NapNeko/NapCatQQ#655]
### 系统版本

Windows 10

### QQNT 版本

9.9.16-29927

### NapCat 版本

V4.2.39 LTS

### OneBot 客户端

V4.2.39 LTS

### 发生了什么?

当某人被邀请进群时，传递的参数：operator_id为0
以下是接收到的信息：
{"time":1735010518,"self_id":1538409963,"post_type":"notice","group_id":822929598,"user_id":2911606375,"notice_type":"group_increase","operator_id":0,"sub_type":"invite"}

### 如何复现

邀请任意人进任意群

### 期望的结果?

恢复邀请人QQ参数

### NapCat 运行日志

```shell
12-24 11:22:03 [info] 爱腾讯 爱生活 | 发送 -> 群聊 [萌宝功能演示群(822929598)] [(1538409963)] [图片]
12-24 11:22:05 [info] 爱腾讯 爱生活 | 发送 -> 群聊 [萌宝功能演示群(822929598)] [(1538409963)] @凌峰 (2911606375) [图片] 
 ... @凌峰 (2911606375) 
 ...
12-24 11:22:08 [error] 爱腾讯 爱生活 | 发生错误 Error: Timeout: NTEvent serviceAndMethod:NodeIKernelProfileService/fetchUserDetailInfo ListenerName:NodeIKernelProfileListener/onUserDetailInfoChanged EventRet:
{
    "result": 30008,
    "errMsg": "kReqUinNil",
    "source": 1,
    "detail": {}
}

    at sendDataCallback (file:///D:/Cat/NapCat/napcat.mjs:23182:11)
    at Timeout._onTimeout (file:///D:/Cat/NapCat/napcat.mjs:23195:45)
    at listOnTimeout (node:internal/timers:573:17)
    at process.processTimers (node:internal/timers:514:7)
```

### OneBot 客户端运行日志

```shell
12-24 11:22:03 [info] 爱腾讯 爱生活 | 发送 -> 群聊 [萌宝功能演示群(822929598)] [(1538409963)] [图片]
12-24 11:22:05 [info] 爱腾讯 爱生活 | 发送 -> 群聊 [萌宝功能演示群(822929598)] [(1538409963)] @凌峰 (2911606375) [图片] 
 ... @凌峰 (2911606375) 
 ...
12-24 11:22:08 [error] 爱腾讯 爱生活 | 发生错误 Error: Timeout: NTEvent serviceAndMethod:NodeIKernelProfileService/fetchUserDetailInfo ListenerName:NodeIKernelProfileListener/onUserDetailInfoChanged EventRet:
{
    "result": 30008,
    "errMsg": "kReqUinNil",
    "source": 1,
    "detail": {}
}

    at sendDataCallback (file:///D:/Cat/NapCat/napcat.mjs:23182:11)
    at Timeout._onTimeout (file:///D:/Cat/NapCat/napcat.mjs:23195:45)
    at listOnTimeout (node:internal/timers:573:17)
    at process.processTimers (node:internal/timers:514:7)
```

**Comment by MliKiowa** [comment]
在群里私聊我 以便进一步测试 这里怀疑uid解析出了问题
