### ISSUE TITLE
[BUG] get_group_member_info调用发生错误 Error: Uin2Uid Error: 用户ID 0 不存在

### ISSUE THREAD

**Issue by HanamiSeishin** [NapNeko/NapCatQQ#663]
### 系统版本

openEuler 24.03 (LTS)

### QQNT 版本

linuxqq 3.2.15_30899

### NapCat 版本

4.2.42

### OneBot 客户端

overflow v1.0.1.541

### 发生了什么?

接收到overflow调用get_group_member_info报错：发生错误 Error: Uin2Uid Error: 用户ID 0 不存在

从版本v2.6.23搭配linuxqq_3.2.12-28418升级而来，搭配该版本overflow无此问题

### 如何复现

邀请成员入群

### 期望的结果?

overflow调用get_group_member_info查询成功并上报MemberJoinEvent事件

### NapCat 运行日志

```shell
12月 28 05:27:37 xvfb-run[3802333]: 12-28 05:27:37 [error] bot | 发生错误 Error: Uin2Uid Error: 用户ID 0 不存在
12月 28 05:27:37 xvfb-run[3802333]:     at GetGroupMemberInfo.getUid (file:///opt/QQ/resources/app/app_launcher/napcat/napcat.mjs:52256:21)
12月 28 05:27:37 xvfb-run[3802333]:     at async GetGroupMemberInfo._handle (file:///opt/QQ/resources/app/app_launcher/napcat/napcat.mjs:52261:17)
12月 28 05:27:37 xvfb-run[3802333]:     at async GetGroupMemberInfo.websocketHandle (file:///opt/QQ/resources/app/app_launcher/napcat/napcat.mjs:43091:23)
12月 28 05:27:37 xvfb-run[3802333]:     at async OB11ActiveWebSocketAdapter.handleMessage (file:///opt/QQ/resources/app/app_launcher/napcat/napcat.mjs:43236:21)
```

### OneBot 客户端运行日志

```shell
2024-12-28 05:27:37 W/Onebot: 请求失败: [get_group_member_info] 请求失败: app=NapCat.Onebot v4.2.42, message=Uin2Uid Error: 用户ID 0 不存在, retJson={"status":"failed","retcode":1200,"data":null,"message":"Uin2Uid Error: 用户ID 0 不存在","wording":"Uin2Uid Error: 用户ID 0 不存在","echo":6}。如果你认为这是 Overflow 的问题，请带上 logs/onebot 中的日志来反馈。
2024-12-28 05:27:37 E/Onebot: 处理 Onebot 事件时出现异常: 
java.lang.IllegalStateException: 无法找到群 (群号) 的成员 0
        at top.mrxiaom.overflow.internal.listener.GroupIncreaseNoticeListener.onMessage(group.kt:235)
        at top.mrxiaom.overflow.internal.listener.GroupIncreaseNoticeListener$onMessage$1.invokeSuspend(group.kt)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:33)
        at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
```

**Comment by MliKiowa** [comment]
与 #655 一样 由于近期时间关系 修复时间为下个月
