### ISSUE TITLE
[BUG] 疑似音乐签名服务器不生效？

### ISSUE THREAD

**Issue by SiriNatsume** [NapNeko/NapCatQQ#671]
### 系统版本

Ubuntu 20.04 LTS

### QQNT 版本

3.2.15-30899

### NapCat 版本

4.2.42

### OneBot 客户端

nonebot

### 发生了什么?

音乐卡片无法正常发送

### 如何复现

尝试生成音乐卡片并发送

### 期望的结果?

正常发送音乐卡片

### NapCat 运行日志

```shell
12-29 19:22:32 [error] Bot | 生成音乐消息失败 Error: Unexpected status code: 522
    at IncomingMessage.<anonymous> (file:///opt/QQ/resources/app/app_launcher/napcat/napcat.mjs:20852:22)
    at IncomingMessage.emit (node:events:531:35)
    at endReadableNT (node:internal/streams/readable:1696:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
12-29 19:22:32 [error] Bot | 发生错误 Error: 消息体无法解析, 请检查是否发送了不支持的消息类型
    at OneBotMsgApi.sendMsgWithOb11UniqueId (file:///opt/QQ/resources/app/app_launcher/napcat/napcat.mjs:47932:13)
    at SendMsg._handle (file:///opt/QQ/resources/app/app_launcher/napcat/napcat.mjs:48228:56)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async SendMsg.websocketHandle (file:///opt/QQ/resources/app/app_launcher/napcat/napcat.mjs:43091:23)
    at async OB11ActiveWebSocketAdapter.handleMessage (file:///opt/QQ/resources/app/app_launcher/napcat/napcat.mjs:43236:21)
```

### OneBot 客户端运行日志

```shell
Traceback (most recent call last):
  File "<string>", line 21, in <module>
  File "/home/ubuntu/anaconda3/envs/potato/lib/python3.10/site-packages/nonebot/__init__.py", line 335, in run
    get_driver().run(*args, **kwargs)
  File "/home/ubuntu/anaconda3/envs/potato/lib/python3.10/site-packages/nonebot/drivers/fastapi.py", line 186, in run
    uvicorn.run(
  File "/home/ubuntu/anaconda3/envs/potato/lib/python3.10/site-packages/uvicorn/main.py", line 587, in run
    server.run()
  File "/home/ubuntu/anaconda3/envs/potato/lib/python3.10/site-packages/uvicorn/server.py", line 62, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/home/ubuntu/anaconda3/envs/potato/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/home/ubuntu/anaconda3/envs/potato/lib/python3.10/site-packages/nonebot/message.py", line 476, in check_and_run_matcher
    await _run_matcher(
> File "/home/ubuntu/anaconda3/envs/potato/lib/python3.10/site-packages/nonebot/message.py", line 428, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "/home/ubuntu/anaconda3/envs/potato/lib/python3.10/site-packages/nonebot/internal/matcher/matcher.py", line 850, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "/home/ubuntu/anaconda3/envs/potato/lib/python3.10/site-packages/nonebot/internal/matcher/matcher.py", line 825, in simple_run
    await handler(
  File "/home/ubuntu/anaconda3/envs/potato/lib/python3.10/site-packages/nonebot/dependencies/__init__.py", line 94, in __call__
    return await cast(Callable[..., Awaitable[R]], self.call)(**values)
  File "/home/ubuntu/potato/src/plugins/potato_plugin_ncm/__init__.py", line 77, in search_receive
    await search.finish(card)
  File "/home/ubuntu/anaconda3/envs/potato/lib/python3.10/site-packages/nonebot/internal/matcher/matcher.py", line 582, in finish
    await cls.send(message, **kwargs)
  File "/home/ubuntu/anaconda3/envs/potato/lib/python3.10/site-packages/nonebot/internal/matcher/matcher.py", line 566, in send
    return await bot.send(event=event, message=_message, **kwargs)
  File "/home/ubuntu/anaconda3/envs/potato/lib/python3.10/site-packages/nonebot/adapters/onebot/v11/bot.py", line 228, in send
    return await self.__class__.send_handler(self, event, message, **kwargs)
  File "/home/ubuntu/anaconda3/envs/potato/lib/python3.10/site-packages/nonebot/adapters/onebot/v11/bot.py", line 181, in send
    return await bot.send_msg(**params)
  File "/home/ubuntu/anaconda3/envs/potato/lib/python3.10/site-packages/nonebot/internal/adapter/bot.py", line 122, in call_api
    raise exception
  File "/home/ubuntu/anaconda3/envs/potato/lib/python3.10/site-packages/nonebot/internal/adapter/bot.py", line 97, in call_api
    result = await self.adapter._call_api(self, api, **data)
  File "/home/ubuntu/anaconda3/envs/potato/lib/python3.10/site-packages/nonebot/adapters/onebot/v11/adapter.py", line 149, in _call_api
    raise NetworkError(f"WebSocket call api {api} timeout") from None
nonebot.adapters.onebot.v11.exception.NetworkError: NetWorkError(message='WebSocket call api send_msg timeout')
```

**Comment by MliKiowa** [comment]
现在呢 音乐sign远程服务如果崩了其实和napcat没有太大关系 你可以找其余代替接口切换
